# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `1.knowledge_base/1.3_knowledge_validation_and_negative_constraints/build_error_feedback.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    'from __future__ import annotations',
    '',
    'import json',
    'import os',
    'from pathlib import Path',
    'from typing import Any, Dict, List, Set, Tuple',
    '',
    '# === domain_term_c26f937881：domain_term_d59d3030a9 / domain_term_36ad5d2f62 / domain_term_d0bda4e4f9 ===',
    'BASE_DIR = Path(__file__).resolve().parent.parent',
    '',
    '# domain_term_8ab8950011（dataset_exe_result.json）',
    'INPUT_PATH = Path("D:/Desktop/domain_term_bc29091d1b/domain_term_95517a6370/domain_term_d4b4f08c89/error_source/13.95-12.13.json")',
    '',
    '# domain_term_30b12310a6 sql_id domain_term_d46f82fdf0（domain_term_8dac093b66）',
    "WRONG_IDS: List[str] = ['sql_1', 'sql_2', 'sql_3', 'sql_4', 'sql_6', 'sql_7', 'sql_8', 'sql_9', 'sql_10', 'sql_11', 'sql_13', 'sql_14', 'sql_15', 'sql_16', 'sql_18', 'sql_19', 'sql_20', 'sql_22', 'sql_23', 'sql_24', 'sql_26', 'sql_27', 'sql_29', 'sql_31', 'sql_32', 'sql_40', 'sql_41', 'sql_42', 'sql_43', 'sql_44', 'sql_47', 'sql_50', 'sql_51', 'sql_52', 'sql_53', 'sql_54', 'sql_55', 'sql_58', 'sql_60', 'sql_61', 'sql_62', 'sql_64', 'sql_65', 'sql_67', 'sql_68', 'sql_69', 'sql_70', 'sql_71', 'sql_73', 'sql_74', 'sql_75', 'sql_77', 'sql_78', 'sql_80', 'sql_82', 'sql_83', 'sql_84', 'sql_85', 'sql_87', 'sql_88', 'sql_89', 'sql_90', 'sql_91', 'sql_93', 'sql_98', 'sql_99', 'sql_100', 'sql_108', 'sql_109', 'sql_110', 'sql_111', 'sql_115', 'sql_117', 'sql_120']",
    'OUTPUT_PATH = BASE_DIR / "data" / "error_feedback.json"',
    '',
    '',
    'def load_dataset(path: Path) -> List[Dict[str, Any]]:',
    ' if not path.exists():',
    ' raise FileNotFoundError(f"domain_term_ad4e37af05: {path}")',
    ' with path.open("r", encoding="utf-8") as f:',
    ' try:',
    ' data = json.load(f)',
    ' except json.JSONDecodeError:',
    ' # domain_term_9dedc88840 JSONL',
    ' f.seek(0)',
    ' data = [json.loads(line) for line in f if line.strip()]',
    '',
    ' if not isinstance(data, list):',
    ' raise ValueError("domain_term_e8850440f2 JSON domain_term_bc530188ec list[dict]")',
    ' return data',
    '',
    '',
    'def normalize_batch(rows: List[Dict[str, Any]]) -> str:',
    ' """',
    ' domain_term_00334bcb1b（Batch）domain_term_64a1e7a519，domain_term_178ffdabd3。',
    ' domain_term_f26c2b4e8a：domain_term_5d14e2b527 -> domain_term_89c0923c9d -> domain_term_1c6e0da7b0。',
    ' domain_term_450280d2e8。',
    ' """',
    ' if not rows:',
    ' return ""',
    ' # 1. domain_term_f5935c86f8 (Sort keys domain_term_6a2516d70f)',
    ' row_strs = [json.dumps(r, sort_keys=True, ensure_ascii=False) for r in rows]',
    ' # 2. domain_term_3fe6e9d7ab (domain_term_f934cd780c)',
    ' row_strs.sort()',
    ' # 3. domain_term_ca877df2ae',
    ' return json.dumps(row_strs, ensure_ascii=False)',
    '',
    '',
    'def build_error_feedback(',
    ' dataset: List[Dict[str, Any]], wrong_ids: Set[str]',
    ') -> Dict[str, Dict[str, Any]]:',
    ' """',
    ' domain_term_55cea275f9。',
    ' domain_term_74070b81cd sql_id domain_term_3fe64336d4 batch (domain_term_bcd5b598a3 dataset_exe_result.json domain_term_0c4317c0a2)。',
    ' """',
    ' feedback: Dict[str, Dict[str, Any]] = {}',
    '',
    ' for item in dataset:',
    ' sid = str(item.get("sql_id") or "").strip()',
    ' if not sid or sid not in wrong_ids:',
    ' continue',
    '',
    ' # domain_term_2637beae6f（Batch）',
    ' batch = item.get("result")',
    '',
    ' # domain_term_8639be0721 result domain_term_57689fba27（null domain_term_30f4d7cfe8 domain_term_a83f38b9ee）',
    ' if not isinstance(batch, list):',
    ' batch = []',
    '',
    ' # domain_term_67d38c2f98，domain_term_8be35b2610（domain_term_34616145d2“domain_term_82ca4a6ba6”），domain_term_d3bb7dee4b',
    ' if not batch:',
    ' print(f"[WARN] sql_id={sid} domain_term_cc77f7c566 (0 rows)，domain_term_50bd96217c。")',
    ' continue',
    '',
    ' entry = feedback.setdefault(',
    ' sid,',
    ' {',
    ' "status": "incorrect",',
    ' "history_batches": [],',
    ' },',
    ' )',
    ' entry["history_batches"].append(batch)',
    '',
    ' return feedback',
    '',
    '',
    'def merge_feedback(',
    ' existing: Dict[str, Any], new_fb: Dict[str, Any]',
    ') -> Tuple[Dict[str, Any], int, int]:',
    ' """',
    ' domain_term_5ac5a6c758。',
    ' domain_term_11d0241540: (domain_term_4d3e74f0f0, domain_term_0bda44dbd0, domain_term_c9d04de09b)',
    ' """',
    ' added_count = 0',
    ' duplicate_count = 0',
    '',
    ' for sid, entry in new_fb.items():',
    ' new_batches = entry.get("history_batches") or []',
    '',
    ' target = existing.setdefault(',
    ' sid,',
    ' {"status": "incorrect", "history_batches": []}',
    ' )',
    ' existing_batches = target.get("history_batches", [])',
    '',
    ' # domain_term_ae6387ff40',
    ' existing_sigs = set()',
    ' for b in existing_batches:',
    ' if isinstance(b, list):',
    ' existing_sigs.add(normalize_batch(b))',
    '',
    ' # domain_term_10f9ee075a',
    ' for batch in new_batches:',
    ' if not isinstance(batch, list):',
    ' continue',
    '',
    ' sig = normalize_batch(batch)',
    ' if sig in existing_sigs:',
    ' duplicate_count += 1',
    ' else:',
    ' existing_batches.append(batch)',
    ' existing_sigs.add(sig)',
    ' added_count += 1',
    '',
    ' target["history_batches"] = existing_batches',
    ' target["status"] = "incorrect"',
    '',
    ' return existing, added_count, duplicate_count',
    '',
    '',
    'def main() -> None:',
    ' if not WRONG_IDS:',
    ' raise ValueError("WRONG_IDS domain_term_44fa2a2c69，domain_term_b7f0b9f717 sql_id domain_term_d46f82fdf0。")',
    '',
    ' wrong_ids_set = {x.strip() for x in WRONG_IDS if x.strip()}',
    ' print(f"[INFO] domain_term_72efa82e32: {len(wrong_ids_set)}")',
    '',
    ' try:',
    ' dataset = load_dataset(INPUT_PATH)',
    ' except Exception as e:',
    ' print(f"[FATAL] domain_term_f78ffd13c8: {e}")',
    ' return',
    '',
    ' # 1. domain_term_f3a9cfb6f7',
    ' new_feedback = build_error_feedback(dataset, wrong_ids_set)',
    ' if not new_feedback:',
    ' print("[WARN] domain_term_35b1f2ded8（domain_term_f30b9ff1fcIDdomain_term_24d6f535b3）。")',
    ' return',
    '',
    ' # 2. domain_term_1c64dbad88',
    ' existing = {}',
    ' if OUTPUT_PATH.exists() and OUTPUT_PATH.stat().st_size > 0:',
    ' try:',
    ' with OUTPUT_PATH.open("r", encoding="utf-8") as f:',
    ' existing = json.load(f)',
    ' except Exception as e:',
    ' print(f"[WARN] domain_term_c337ce937f ({e})，domain_term_d9e1dc0722。")',
    '',
    ' # 3. domain_term_ed361cf783',
    ' merged, added_cnt, dup_cnt = merge_feedback(existing, new_feedback)',
    '',
    ' # 4. domain_term_e620fd4b1f',
    ' OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)',
    ' with OUTPUT_PATH.open("w", encoding="utf-8") as f:',
    ' json.dump(merged, f, ensure_ascii=False, indent=2)',
    '',
    ' print("/n" + "="*40)',
    ' print(f"domain_term_65f1dfa164: {OUTPUT_PATH}")',
    ' print(f"domain_term_b6fd94a28e: {len(new_feedback)}")',
    ' print(f"➕ domain_term_682c5a2ea4: {added_cnt} domain_term_f7b2a6ee68")',
    ' print(f"♻️ domain_term_59d7290106: {dup_cnt} domain_term_f7b2a6ee68 (domain_term_bd172c8dcb)")',
    ' print("="*40 + "/n")',
    '',
    '',
    'if __name__ == "__main__":',
    ' main()',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
