# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `1.knowledge_base/1.3_knowledge_validation_and_negative_constraints/data_detective_agent.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    '',
    '',
    '',
    '',
    'from __future__ import annotations',
    '',
    'import sys',
    'import io',
    'import argparse',
    'import json',
    'import os',
    'import sys',
    'from dataclasses import dataclass',
    'from datetime import datetime',
    'from pathlib import Path',
    'from typing import Any, Dict, List, Optional, Tuple',
    '',
    'import time',
    'import pymysql',
    'from openai import OpenAI',
    '',
    '# --- domain_term_13d4ef38be：domain_term_bbae5a1472 run/agent/config.py ---',
    'BASE_DIR = Path(__file__).resolve().parent.parent',
    'T2SQL_DIR = BASE_DIR',
    'AGENT_DIR = T2SQL_DIR / "run" / "agent"',
    'if str(BASE_DIR) not in sys.path:',
    ' sys.path.insert(0, str(BASE_DIR))',
    'if str(AGENT_DIR) not in sys.path:',
    ' sys.path.insert(0, str(AGENT_DIR))',
    '',
    'from config import ( # type: ignore',
    ' DATA_DIR,',
    ' SCHEMA_PATH,',
    ' COMMON_KNOWLEDGE_PATH,',
    ' FINAL_DATASET_PATH,',
    ' ADDED_KNOWLEDGE_LIST_PATH,',
    ' DB_CONFIG,',
    ' LLM_PROVIDER,',
    ' OPENAI_API_KEY,',
    ' OPENAI_BASE_URL,',
    ' OPENAI_MODEL,',
    ' GEMINI_API_KEY,',
    ' GEMINI_BASE_URL,',
    ' GEMINI_MODEL,',
    ' DETECTIVE_VERIFIED_KB_PATH,',
    ' GEMINI_API_KEYS as CFG_GEMINI_API_KEYS,',
    ')',
    'from evaluation import OfflineEvaluator, load_json_as_dict # type: ignore',
    '',
    '',
    'SYSTEM_PROMPT = """You are a Senior Data Detective & SQL Expert.',
    '',
    'Your goal is to answer business questions with 100% executable and logically verified SQL.',
    '',
    'Core principles:',
    '- Empiricism (domain_term_8178ac699e): never guess, always verify on real data.',
    '- Do not trust schema or task description blindly.',
    '- Do not guess data formats or business definitions.',
    '- You must verify specific hypotheses against actual data before giving the final SQL.',
    '- You must only generate read-only SQL (SELECT ...). Never modify data.',
    ' - **Time Columns Strategy**: Tables often have multiple time columns (e.g., `dteventtime` vs `tdbank_imp_date`). You MUST PROBE BOTH to determine which one contains the correct business data. Do not blindly default to one. Partition time (`tdbank_imp_date`) is often delayed compared to event time (`dteventtime`).',
    'domain_term_1cf0408b11“domain_term_636be42b72”domain_term_634158bbfc“domain_term_5d92add882”，domain_term_f8f4a1bfae。',
    '',
    'Protocol:',
    '1) You work in phases. Valid values of the field `phase` in your JSON output are:',
    ' - "PROBE": diagnostic / hypothesis-testing queries.',
    ' - "SOLVE": candidate final solution SQL.',
    ' - "CONFIRM": confirmation that the last executed SOLVE SQL is logically correct.',
    '',
    '2) Phase PROBE (hypothesis testing loop)',
    ' - Goal: eliminate ambiguity about granularity, time logic, join conditions, status codes, etc.',
    ' - Typical traps to check:',
    ' * Granularity / summary rows, e.g. platform-level aggregates like platid = 255.',
    ' * Time format & range: is date string or int... which range is actually present...',
    ' * Column semantics: what do status codes 0/1/2 mean... any special markers...',
    ' - You MUST output small, information-dense diagnostic SQLs (Smart Probes), not the final solution.',
    ' - Always group / aggregate or use DISTINCT to understand distributions.',
    ' - Prefer queries with LIMIT and GROUP BY to avoid huge result sets.',
    ' - JSON format for PROBE:',
    ' {',
    ' "phase": "PROBE",',
    ' "thought": "your reasoning about the ambiguity and hypothesis",',
    ' "sql": "SELECT ..." // read-only SQL',
    ' }',
    '',
    '3) Phase SOLVE (candidate final solution)',
    ' - Only when key ambiguities are resolved, produce a full solution SQL.',
    ' - Encode in `verified_logic` what rules and business assumptions you have already checked.',
    ' - JSON format for SOLVE:',
    ' {',
    ' "phase": "SOLVE",',
    ' "thought": "why this SQL solves the question and how it uses verified logic",',
    ' "sql": "SELECT ...", // read-only SQL',
    ' "verified_logic": "bullet-point style summary of business rules and pitfalls avoided"',
    ' }',
    '',
    '4) Phase CONFIRM (result sanity check)',
    ' - After the environment executes your last SOLVE SQL, you will see:',
    ' * Row count',
    ' * A few sample rows',
    ' * Basic aggregates on numeric columns',
    ' - You must decide whether the magnitude and filtering are reasonable.',
    ' - JSON format for CONFIRM:',
    ' {',
    ' "phase": "CONFIRM",',
    ' "thought": "why the result is logically consistent with the question",',
    ' "verified_logic": "final refined description of the data logic and pitfalls avoided"',
    ' }',
    '',
    '5) General rules for ALL phases',
    ' - Always return a single JSON object, no extra text.',
    ' - The top-level keys must include at least: `phase`, `thought`.',
    ' - SQL must be valid for a MySQL/StarRocks-like dialect.',
    ' - NEVER use DDL or DML (NO INSERT/UPDATE/DELETE/CREATE/DROP). Only SELECT.',
    '',
    '',
    '6) **Few-Shot Examples (Follow these patterns strictly)**',
    '',
    '**Example 1: Safe Probing (Avoiding Syntax Errors in UNION)**',
    '*User*: "Check the distribution of `platid` in both login and match tables for 20231101."',
    '*Assistant*:',
    '{',
    ' "phase": "PROBE",',
    ' "thought": "I need to check distinct `platid` values to see if they are raw (0,1,2) or aggregated (255). I will use UNION ALL to check both tables in one go. I must wrap subqueries with LIMIT to avoid syntax errors in MySQL/StarRocks.",',
    ' "sql": "SELECT * FROM (SELECT \'login\' as type, platid, count(*) as cnt FROM dws_login_di WHERE date=\'20231101\' GROUP BY platid ORDER BY cnt DESC LIMIT 5) t1 UNION ALL SELECT * FROM (SELECT \'match\' as type, platid, count(*) as cnt FROM dws_match_di WHERE date=\'20231101\' GROUP BY platid ORDER BY cnt DESC LIMIT 5) t2"',
    '}',
    '',
    '**Example 2: Verifying Logic before Solving (Data Empiricism)**',
    '*User*: "Find users retained for 7 days after registering in \'Ranked Mode\' (mode_id=102)."',
    '*Assistant*:',
    '{',
    ' "phase": "PROBE",',
    ' "thought": "Before calculating retention, I must verify: 1) Does `mode_id=102` actually exist in the logs... 2) Is the date format \'YYYYMMDD\' or \'YYYY-MM-DD\' so I can use the correct date function.",',
    ' "sql": "SELECT \'date_format\' as check_type, dtstatdate as sample_val, count(*) FROM dws_match_di GROUP BY dtstatdate LIMIT 3 UNION ALL SELECT \'mode_check\', cast(mode_id as string), count(*) FROM dws_match_di WHERE mode_id=102 GROUP BY mode_id"',
    '}',
    '',
    '**Example 3: Handling Empty Results (Zero Rows is usually a Bug)**',
    '*User*: (System) "**[CRITICAL REJECTION] SQL executed successfully but returned 0 rows.** ... Please review common pitfalls..."',
    '*Assistant*:',
    '{',
    ' "phase": "PROBE",',
    ' "thought": "I received a critical rejection for 0 rows. It\'s likely that my filter `mode_id=102` is incorrect (maybe it\'s a string \'102\'...) or I used the wrong partition key. I need to remove the WHERE clause and check the actual distribution of `mode_id`.",',
    ' "sql": "SELECT mode_id, count(*) FROM dws_match_di GROUP BY mode_id ORDER BY 2 DESC LIMIT 10"',
    '}',
    '"""',
    '',
    '',
    'VERIFIED_KB_PATH = DETECTIVE_VERIFIED_KB_PATH',
    'GOLDEN_RESULT_PATH = BASE_DIR / "data" / "correct_58.json"',
    'ERROR_FEEDBACK_PATH = BASE_DIR / "data" / "error_feedback.json"',
    'STARROCK_KNOWLEDGE_PATH = BASE_DIR / "data" / "starrock_knowledge.md"',
    'FINAL_DATASET_FOR_DETECTIVE = BASE_DIR / "data" / "final_dataset.json"',
    'MAX_TURNS = 150',
    'MAX_ROWS_PER_QUERY = 500',
    "#'sql_2', 'sql_8',",
    "SQL_ID_LIST = [ 'sql_8', 'sql_19', 'sql_20', 'sql_29', 'sql_40', 'sql_44', 'sql_52', 'sql_53', 'sql_54', 'sql_55', 'sql_58', 'sql_61', 'sql_64', 'sql_80', 'sql_84', 'sql_85', 'sql_88', 'sql_89', 'sql_90', 'sql_91', 'sql_93', 'sql_98', 'sql_99', 'sql_100', 'sql_105', 'sql_108', 'sql_110', 'sql_115', 'sql_117', 'sql_120']",
    '',
    '# domain_term_68f7d028b7 run/agent/config.py domain_term_c7798e8397 key domain_term_d46f82fdf0，domain_term_b65e67323f',
    'GEMINI_API_KEYS = [k for k in (CFG_GEMINI_API_KEYS or []) if k]',
    'OPENAI_API_KEYS = [',
    ' "sk-ZMX7aZkrFYYGVyOJHAl4OGlFrxS6dgfEDkiu6nAgroaY2CVE",',
    ' "sk-fOKchz64V6UDYVVPGxt5wEK91m3dWv9TrRfDAtmFNnrU4CBb",',
    ' "sk-S2zVWmDQ6vBgqU8o8NWMYvsNDKq034VOAbFvYc2tVZQm19eW",',
    ']',
    '',
    'DEAD_GEMINI_KEYS: set = set()',
    'DEAD_OPENAI_KEYS: set = set()',
    '',
    '',
    '@dataclass',
    'class SQLResult:',
    ' rows: List[Dict[str, Any]]',
    ' error: Optional[str]',
    '',
    '',
    'class EnhancedJSONEncoder(json.JSONEncoder):',
    ' def default(self, obj: Any) -> Any: # type: ignore[override]',
    ' try:',
    ' import decimal',
    ' import datetime as dt',
    ' if isinstance(obj, decimal.Decimal):',
    ' return float(obj)',
    ' if isinstance(obj, (dt.datetime, dt.date)):',
    ' return obj.isoformat()',
    ' # === domain_term_2cd9e6ce81：domain_term_9263e46a01 TimeDelta (domain_term_cbb89941ac) ===',
    ' if isinstance(obj, dt.timedelta):',
    ' return str(obj)',
    ' except Exception:',
    ' pass',
    ' return super().default(obj)',
    '',
    '',
    'def load_json(path: Path) -> Any:',
    ' with path.open("r", encoding="utf-8") as f:',
    ' return json.load(f)',
    '',
    '',
    'def load_text(path: Path) -> str:',
    ' return path.read_text(encoding="utf-8") if path.exists() else ""',
    '',
    '',
    'def get_llm_client() -> Tuple[OpenAI, str, str]:',
    ' """domain_term_8aa56da804 LLM_PROVIDER domain_term_468c907d32 client / model / provider。',
    '',
    ' provider domain_term_a8700a6156：',
    ' - "gemini": domain_term_0e2d3a3c09 GEMINI_* domain_term_d7d7ce790b',
    ' - domain_term_1a26edf94a: domain_term_0e2d3a3c09 OPENAI_* (domain_term_0e00b819cb)',
    ' """',
    '',
    ' provider = (LLM_PROVIDER or "").lower()',
    ' if provider == "gemini":',
    ' api_key = GEMINI_API_KEY',
    ' base_url = GEMINI_BASE_URL',
    ' model = GEMINI_MODEL',
    ' else:',
    ' api_key = OPENAI_API_KEY',
    ' base_url = OPENAI_BASE_URL',
    ' model = OPENAI_MODEL',
    '',
    ' if not api_key:',
    ' raise RuntimeError("LLM API key is not configured")',
    '',
    ' client = OpenAI(api_key=api_key, base_url=base_url)',
    ' return client, model, provider',
    '',
    '',
    'def _strip_code_fences(text: str) -> str:',
    ' """domain_term_716298579f LLM domain_term_357284211a ```json / ```sql / ``` domain_term_580aa0af33。',
    '',
    ' domain_term_03b795430e：',
    ' ```json',
    ' { ... }',
    ' ```',
    ' domain_term_3fbe3edfc5：',
    ' ```',
    ' { ... }',
    ' ```',
    ' """',
    '',
    ' if not text:',
    ' return text',
    '',
    ' s = text.strip()',
    ' if not s.startswith("```"):',
    ' return s',
    '',
    ' # domain_term_e279e6ea49 ```xxx',
    ' if "\\n" in s:',
    ' first_line, rest = s.split("\\n", 1)',
    ' s = rest',
    ' # domain_term_abe561c205 ```',
    ' s = s.strip()',
    ' if s.endswith("```"):',
    ' s = s[: s.rfind("```")].strip()',
    ' return s',
    '',
    '',
    'def _extract_json_object(text: str) -> Optional[str]:',
    ' """domain_term_ba9ae89de9 + JSON domain_term_9da80fceac {...} JSON domain_term_539cb3b0a6。"""',
    '',
    ' if not text:',
    ' return None',
    '',
    ' s = text.strip()',
    ' # domain_term_13aa7c1b3f ```，domain_term_a894e2ebd0 ``` domain_term_5afc096876，domain_term_9d171cd083',
    ' start_search = 0',
    ' fence_pos = s.find("```")',
    ' if fence_pos != -1:',
    ' start_search = fence_pos',
    '',
    ' start = s.find("{", start_search)',
    ' if start == -1:',
    ' return None',
    '',
    ' depth = 0',
    ' in_string = False',
    ' escape = False',
    ' for i in range(start, len(s)):',
    ' ch = s[i]',
    ' if in_string:',
    ' if escape:',
    ' escape = False',
    ' elif ch == "\\\\":',
    ' escape = True',
    ' elif ch == \'"\':',
    ' in_string = False',
    ' continue',
    ' if ch == \'"\':',
    ' in_string = True',
    ' continue',
    ' if ch == "{":',
    ' depth += 1',
    ' elif ch == "}":',
    ' depth -= 1',
    ' if depth == 0:',
    ' return s[start : i + 1]',
    ' return None',
    '',
    '',
    'def call_llm_json(',
    ' client: OpenAI,',
    ' model: str,',
    ' provider: str,',
    ' messages: List[Dict[str, str]],',
    ') -> Optional[Dict[str, Any]]:',
    ' """domain_term_14bc69f7e5，domain_term_f4309f2934；domain_term_44e4c0b096。',
    '',
    ' domain_term_f26c2b4e8a：',
    ' - domain_term_04c9c89da9 5 domain_term_5e5b8169ee（domain_term_b66103ee05 JSON domain_term_667b9df1d2）。',
    ' - domain_term_312aba2519，domain_term_a98f74ae0c provider domain_term_e5d9c6c8a8 openai，domain_term_0cd750f2e9 OPENAI_* domain_term_5aa32ac1fb 1 domain_term_5e5b8169ee。',
    ' """',
    '',
    ' def _single_call(',
    ' cur_client: OpenAI,',
    ' cur_model: str,',
    ' use_strict_json: bool,',
    ' tag: str,',
    ' ) -> Tuple[Optional[Dict[str, Any]], str]:',
    ' try:',
    ' if use_strict_json:',
    ' # Gemini domain_term_8d66a62f0e JSON：reasoning_effort + response_format',
    ' resp = cur_client.chat.completions.create(',
    ' model=cur_model,',
    ' messages=messages,',
    ' temperature=1,',
    ' # max_tokens=2048,',
    ' reasoning_effort="high",',
    " # thinking_level='high',",
    ' response_format={"type": "json_object"},',
    ' )',
    ' else:',
    ' # domain_term_9c38dc2c45 response_format / reasoning_effort',
    ' resp = cur_client.chat.completions.create(',
    ' model=cur_model,',
    ' messages=messages,',
    ' temperature=1,',
    ' # max_tokens=2048,',
    ' )',
    ' print(resp, f"resp[{tag}]")',
    ' except Exception as e:',
    ' msg = str(e)',
    ' safe_msg = msg.replace("¥", "Y")',
    ' print(f"[LLM][{tag}] domain_term_1d1d87767f: {safe_msg}")',
    ' # domain_term_61d6f0f6e9，domain_term_48eb252165（domain_term_2f8e5c76ce kill domain_term_d695ca5b2c key）',
    ' if "insufficient_user_quota" in msg or "domain_term_4358ab83e8" in msg:',
    ' return None, "quota"',
    ' # domain_term_687bca1701 / domain_term_4bad4a2de0：domain_term_8fa7401e90 kill key，domain_term_95a4409ecc sleep domain_term_c0cb135c24',
    ' busy_keywords = [',
    ' "domain_term_c24344522f",',
    ' "domain_term_58bba2f93f",',
    ' "domain_term_ce20bdc9b1",',
    ' "domain_term_4cf3d3f7c7",',
    ' "Too Many Requests",',
    ' "too many requests",',
    ' "rate limit",',
    ' "Rate limit",',
    ' "429",',
    ' ]',
    ' if any(k in msg for k in busy_keywords):',
    ' return None, "busy"',
    ' return None, "error"',
    '',
    ' text = resp.choices[0].message.content or ""',
    ' raw_text = text',
    ' text = _strip_code_fences(text)',
    ' try:',
    ' return json.loads(text), "ok"',
    ' except Exception as e:',
    ' print(f"[LLM][{tag}] JSON domain_term_0a95106968: {e}\\ndomain_term_00a211a6c1: {raw_text}")',
    ' # domain_term_53622ff3f8：domain_term_28246097f0 JSON domain_term_539cb3b0a6',
    ' candidate = _extract_json_object(raw_text)',
    ' if candidate:',
    ' try:',
    ' return json.loads(candidate), "ok"',
    ' except Exception as e2:',
    ' print(f"[LLM][{tag}] domain_term_503238802f JSON domain_term_6c26caef39: {e2}\\ndomain_term_9247771ea4: {candidate}")',
    ' return None, "parse"',
    '',
    ' def _try_with_keys(',
    ' api_keys: List[str],',
    ' base_url: str,',
    ' model_name: str,',
    ' use_strict_json: bool,',
    ' tag_prefix: str,',
    ' use_initial_client: bool = False,',
    ' provider_name: str = "",',
    ' ) -> Optional[Dict[str, Any]]:',
    ' # domain_term_9c06b7ce03 provider domain_term_96029cf4c9“domain_term_6dcfcd0379 key”domain_term_f8dd3e84b8',
    ' if provider_name == "gemini":',
    ' dead_keys = DEAD_GEMINI_KEYS',
    ' elif provider_name == "openai":',
    ' dead_keys = DEAD_OPENAI_KEYS',
    ' else:',
    ' dead_keys = set()',
    '',
    ' for key_index, api_key in enumerate(api_keys):',
    ' if not api_key or api_key in dead_keys:',
    ' continue',
    ' attempt = 0',
    ' while True:',
    ' attempt += 1',
    ' tag = f"{tag_prefix}-k{key_index + 1}-try{attempt}"',
    ' if use_initial_client and key_index == 0 and attempt == 1:',
    ' cur_client = client',
    ' else:',
    ' try:',
    ' cur_client = OpenAI(api_key=api_key, base_url=base_url)',
    ' except Exception as e:',
    ' print(f"[LLM][{tag}] domain_term_abf1e23b18: {e}")',
    ' break',
    ' action, err_type = _single_call(cur_client, model_name, use_strict_json, tag=tag)',
    ' if action is not None:',
    ' return action',
    ' if err_type == "quota":',
    ' dead_keys.add(api_key)',
    ' print(f"[LLM] Key #{key_index + 1} domain_term_a61b66ab7d，domain_term_dea4dd9f00，domain_term_293aabdff9 key。")',
    ' break',
    ' if err_type == "busy":',
    ' print(f"[LLM] Key #{key_index + 1} domain_term_ce609154cc，30 domain_term_ef0f2e43d7 (domain_term_dae828fe4f {attempt} domain_term_5e5b8169ee)...")',
    ' time.sleep(30)',
    ' continue',
    ' print(f"[LLM] Key #{key_index + 1} domain_term_dae828fe4f {attempt} domain_term_dbdadc5da3，domain_term_7d1e825f50...")',
    ' return None',
    '',
    ' provider_l = (provider or "").lower()',
    ' is_gemini = provider_l == "gemini"',
    '',
    ' # 1) domain_term_3c92783681：domain_term_13648e2575 provider domain_term_0746bd6249 key domain_term_1a52da78df',
    ' if is_gemini:',
    ' primary_keys = [k for k in GEMINI_API_KEYS if k]',
    ' if not primary_keys and GEMINI_API_KEY:',
    ' primary_keys = [GEMINI_API_KEY]',
    ' primary_base_url = GEMINI_BASE_URL',
    ' use_strict_json = True',
    ' else:',
    ' primary_keys = [k for k in OPENAI_API_KEYS if k]',
    ' if not primary_keys and OPENAI_API_KEY:',
    ' primary_keys = [OPENAI_API_KEY]',
    ' primary_base_url = OPENAI_BASE_URL',
    ' use_strict_json = False',
    '',
    ' action = _try_with_keys(',
    ' api_keys=primary_keys,',
    ' base_url=primary_base_url,',
    ' model_name=model,',
    ' use_strict_json=use_strict_json,',
    ' tag_prefix="primary",',
    ' use_initial_client=True,',
    ' provider_name=provider_l,',
    ' )',
    ' if action is not None:',
    ' return action',
    '',
    ' print("[LLM] domain_term_25e74dceac provider domain_term_bfa7d9f9ef API Key domain_term_03b6b1ff09。")',
    '',
    ' # domain_term_3e8fc58688 Gemini，domain_term_47c4801040 key domain_term_babbc0732e，domain_term_3346812f3a OpenAI，domain_term_920d4fd5d7',
    ' if is_gemini:',
    ' all_gem_keys = [k for k in GEMINI_API_KEYS if k]',
    ' if all_gem_keys and all(k in DEAD_GEMINI_KEYS for k in all_gem_keys):',
    ' print("[LLM] domain_term_eba4161da4 Gemini API Key domain_term_31c0925c32，domain_term_533f44619f。")',
    ' return None',
    '',
    ' # 2) domain_term_296d98dd01（OPENAI_* domain_term_d7d7ce790b）。domain_term_aed2c5deca openai，domain_term_37aa5be3e8。',
    ' if provider_l == "openai":',
    ' print("[LLM] domain_term_25e74dceac provider domain_term_663672c541 openai，domain_term_a196709506。")',
    ' return None',
    '',
    ' backup_keys = [k for k in OPENAI_API_KEYS if k]',
    ' if not backup_keys and OPENAI_API_KEY:',
    ' backup_keys = [OPENAI_API_KEY]',
    ' if not backup_keys:',
    ' print("[LLM] domain_term_88a9cb2a0c：OPENAI_API_KEY_LIST domain_term_c7478bb67d。")',
    ' return None',
    '',
    ' action = _try_with_keys(',
    ' api_keys=backup_keys,',
    ' base_url=OPENAI_BASE_URL,',
    ' model_name=OPENAI_MODEL,',
    ' use_strict_json=False,',
    ' tag_prefix="fallback-openai",',
    ' use_initial_client=False,',
    ' provider_name="openai",',
    ' )',
    ' return action',
    '',
    '',
    'def execute_sql(sql: str, max_rows: int = MAX_ROWS_PER_QUERY) -> SQLResult:',
    ' cfg = DB_CONFIG',
    ' conn = None',
    ' try:',
    ' conn = pymysql.connect(',
    ' host=cfg["host"],',
    ' user=cfg["user"],',
    ' password=cfg.get("password", ""),',
    ' db=cfg["db"],',
    ' port=cfg["port"],',
    ' cursorclass=pymysql.cursors.DictCursor,',
    ' charset="utf8mb4",',
    ' )',
    ' with conn.cursor() as cursor:',
    ' cursor.execute(sql)',
    ' # domain_term_202d12fa1e，domain_term_bfe4105236',
    ' rows = cursor.fetchall()',
    ' return SQLResult(rows=list(rows), error=None)',
    ' except Exception as e:',
    ' return SQLResult(rows=[], error=str(e))',
    ' finally:',
    ' if conn is not None:',
    ' try:',
    ' conn.close()',
    ' except Exception:',
    ' pass',
    '',
    '',
    'def summarize_result(rows: List[Dict[str, Any]], max_samples: int = 10) -> str:',
    ' """domain_term_aaa0f25501 LLM（domain_term_202d12fa1e）。',
    '',
    ' domain_term_749d765242 max_samples domain_term_a4d7514c7a，domain_term_6df83d8fe0。',
    ' """',
    ' row_count = len(rows)',
    ' if row_count == 0:',
    ' return "0 rows returned."',
    '',
    ' lines: List[str] = []',
    ' lines.append(f"Row count: {row_count}")',
    ' for idx, r in enumerate(rows, start=1):',
    ' lines.append(f"Row {idx}: {json.dumps(r, ensure_ascii=False, cls=EnhancedJSONEncoder)}")',
    ' return "\\n".join(lines)',
    '',
    '',
    'def get_result_profile(rows: List[Dict[str, Any]], max_samples: int = 3) -> Dict[str, Any]:',
    ' profile: Dict[str, Any] = {"row_count": len(rows)}',
    ' if not rows:',
    ' profile["sample_rows"] = []',
    ' profile["numeric_aggregates"] = {}',
    ' return profile',
    '',
    ' sample_rows = rows[:max_samples]',
    ' profile["sample_rows"] = sample_rows',
    '',
    ' # domain_term_100328cedf',
    ' first = rows[0]',
    ' numeric_keys: List[str] = []',
    ' for k, v in first.items():',
    ' if isinstance(v, (int, float)):',
    ' numeric_keys.append(k)',
    ' aggs: Dict[str, Dict[str, float]] = {}',
    ' for key in numeric_keys:',
    ' vals = [r[key] for r in rows if isinstance(r.get(key), (int, float))]',
    ' if not vals:',
    ' continue',
    ' total = float(sum(vals))',
    ' avg = total / len(vals)',
    ' aggs[key] = {"sum": total, "avg": avg}',
    ' profile["numeric_aggregates"] = aggs',
    ' return profile',
    '',
    '',
    'def load_task(sql_id: str) -> Dict[str, Any]:',
    ' # Data Detective domain_term_cae6d0ef7a final_dataset.json，domain_term_00318ad834 run/agent/config.py domain_term_82bb0947bc FINAL_DATASET_PATH',
    ' data = load_json(FINAL_DATASET_FOR_DETECTIVE)',
    ' for item in data:',
    ' if item.get("sql_id") == sql_id:',
    ' return item',
    ' raise ValueError(f"domain_term_96fe90e78a final_dataset.json domain_term_c8e4e7aa17 sql_id={sql_id} domain_term_a3e99d43e9")',
    '',
    '',
    'def load_added_knowledge(sql_id: str) -> str:',
    ' if not Path(ADDED_KNOWLEDGE_LIST_PATH).exists():',
    ' return ""',
    ' data = load_json(Path(ADDED_KNOWLEDGE_LIST_PATH))',
    ' pieces: List[str] = []',
    ' for item in data:',
    ' if item.get("sql_id") == sql_id and item.get("knowledge"):',
    ' pieces.append(str(item["knowledge"]))',
    ' return "\\n\\n".join(pieces)',
    '',
    '',
    'def build_schema_snippet(table_list: List[str]) -> str:',
    ' """domain_term_ff9dc64f8f，domain_term_81a94d85f0 schema domain_term_047987d2da LLM domain_term_a1880f698b。',
    '',
    ' domain_term_d058cee195 schema domain_term_953c96d7dd：',
    ' - domain_term_930184bb40 schema_long.json: domain_term_0abf4263cd column_name / column_type，domain_term_fd9d044e96 llm_table_long_description。',
    ' - domain_term_bb0a3aea8c schema_all.json: domain_term_0abf4263cd col / type，domain_term_fd9d044e96 table_description_llm_long。',
    ' """',
    '',
    ' schema = load_json(Path(SCHEMA_PATH))',
    ' wanted = set(table_list)',
    ' parts: List[str] = []',
    ' for entry in schema:',
    ' table_name = entry.get("table_name")',
    ' if table_name not in wanted:',
    ' continue',
    '',
    ' # domain_term_67484ee5ba：domain_term_5403e717c7，domain_term_f6c7cfa9e0',
    ' desc = (',
    ' entry.get("table_description_llm_long")',
    ' or entry.get("llm_table_long_description", "")',
    ' )',
    ' cols = entry.get("columns", [])',
    ' lines: List[str] = []',
    ' lines.append(f"[Table] {table_name}")',
    ' if desc:',
    ' lines.append(f"Description: {desc}")',
    ' if cols:',
    ' lines.append("Columns:")',
    ' for c in cols:',
    ' # domain_term_56dc7e14b9/domain_term_132c07d838 schema domain_term_9d2601c843',
    ' cname = c.get("column_name") or c.get("col")',
    ' ctype = c.get("column_type") or c.get("type")',
    ' cdesc = (',
    ' c.get("llm_long_description")',
    ' or c.get("llm_short_description")',
    ' or c.get("description", "")',
    ' )',
    ' if not cname and not cdesc:',
    ' continue',
    ' if ctype:',
    ' lines.append(f"- {cname} ({ctype}): {cdesc}")',
    ' else:',
    ' lines.append(f"- {cname}: {cdesc}")',
    ' parts.append("\\n".join(lines))',
    ' return "\\n\\n".join(parts)',
    '',
    '',
    'def build_initial_user_message(sql_id: str) -> str:',
    ' task = load_task(sql_id)',
    ' question = str(task.get("question", "")).strip()',
    ' table_list: List[str] = list(task.get("table_list", []))',
    ' task_knowledge = str(task.get("knowledge", "")).strip()',
    '',
    ' schema_text = build_schema_snippet(table_list)',
    ' common_knowledge = load_text(Path(COMMON_KNOWLEDGE_PATH))',
    ' starrock_knowledge = load_text(Path(STARROCK_KNOWLEDGE_PATH))',
    ' added_knowledge = load_added_knowledge(sql_id)',
    '',
    ' parts: List[str] = []',
    ' parts.append(f"Task sql_id: {sql_id}")',
    ' parts.append(f"User Question:\\n{question}")',
    ' parts.append(f"Related Tables: {\', \'.join(table_list)}")',
    ' if schema_text:',
    ' parts.append("\\n[Schema for related tables]\\n" + schema_text)',
    ' if common_knowledge:',
    ' parts.append("\\n[Global Common Knowledge]\\n" + common_knowledge)',
    ' if starrock_knowledge:',
    ' parts.append("\\n[StarRocks SQL Dialect Knowledge]\\n" + starrock_knowledge)',
    ' if task_knowledge:',
    ' parts.append("\\n[Task Knowledge from final_dataset]\\n" + task_knowledge)',
    ' if added_knowledge:',
    ' parts.append("\\n[Verified Knowledge from knowledge_add_clean_list]\\n" + added_knowledge)',
    '',
    ' parts.append(',
    ' "\\nPlease start with phase \'PROBE\'. "',
    ' "For each response, output ONLY a single JSON object as specified in the protocol."',
    ' "IMPORTANT: \\n"',
    ' "1. Always check if you need to convert IDs (e.g., qq -> wxid) using mapping tables.\\n"',
    ' "2. Always check if specific partitions (e.g., saccounttype=\'-100\') are required for aggregates."',
    ' )',
    '',
    ' return "\\n\\n".join(parts)',
    '',
    '',
    'def load_verified_kb() -> List[Dict[str, Any]]:',
    ' if not VERIFIED_KB_PATH.exists():',
    ' return []',
    ' try:',
    ' return load_json(VERIFIED_KB_PATH)',
    ' except Exception:',
    ' return []',
    '',
    '',
    'def append_verified_entry(entry: Dict[str, Any]) -> None:',
    ' kb = load_verified_kb()',
    ' kb.append(entry)',
    ' VERIFIED_KB_PATH.parent.mkdir(parents=True, exist_ok=True)',
    ' VERIFIED_KB_PATH.write_text(',
    ' json.dumps(kb, ensure_ascii=False, indent=2, cls=EnhancedJSONEncoder),',
    ' encoding="utf-8",',
    ' )',
    '',
    '',
    'def get_completed_sql_ids() -> set:',
    ' kb = load_verified_kb()',
    ' completed: set = set()',
    ' for entry in kb:',
    ' if not isinstance(entry, dict):',
    ' continue',
    ' sid = entry.get("sql_id")',
    ' if isinstance(sid, str):',
    ' completed.add(sid)',
    ' return completed',
    '',
    '',
    'class HistoryGuard:',
    ' """domain_term_43f6f7c662/domain_term_b584e7571f，domain_term_2f3a5c2f86 SOLVE domain_term_b25052660f。',
    '',
    ' - domain_term_3f526c6792：domain_term_1b94a1ea20，domain_term_a1b4fdddc6。',
    ' - domain_term_35c6f4044b，domain_term_59272c17df：domain_term_d0be373f2f，domain_term_3738e779bb。',
    ' """',
    '',
    ' def __init__(self, golden_path: Path, error_path: Path) -> None:',
    ' self.evaluator = OfflineEvaluator()',
    ' self.golden_map: Dict[str, List[Dict[str, Any]]] = {}',
    ' # sql_id -> List[List[Dict]]，domain_term_b8df8b8090 list domain_term_8cf9dcb8e2',
    ' self.error_batches: Dict[str, List[List[Dict[str, Any]]]] = {}',
    '',
    ' self._load_golden(golden_path)',
    ' self._load_error(error_path)',
    '',
    ' def _load_golden(self, path: Path) -> None:',
    ' if not path.exists():',
    ' print(f"[HistoryGuard] domain_term_cd72e9c9fe: {path}")',
    ' return',
    ' try:',
    ' self.golden_map = load_json_as_dict(str(path))',
    ' except Exception as e:',
    ' print(f"[HistoryGuard] domain_term_6e8a2a29e0: {e}")',
    ' self.golden_map = {}',
    '',
    ' def _load_error(self, path: Path) -> None:',
    ' if not path.exists():',
    ' print(f"[HistoryGuard] domain_term_186f5b03a6: {path}")',
    ' return',
    ' try:',
    ' raw = path.read_text(encoding="utf-8")',
    ' data = json.loads(raw)',
    ' except Exception as e:',
    ' print(f"[HistoryGuard] domain_term_4096ebd1fe: {e}")',
    ' return',
    '',
    ' if not isinstance(data, dict):',
    ' print("[HistoryGuard] domain_term_082911e786 dict，domain_term_d84129b8be。")',
    ' return',
    '',
    ' for sid, rec in data.items():',
    ' if not isinstance(rec, dict):',
    ' continue',
    ' batches_raw = rec.get("history_batches") or []',
    ' if not isinstance(batches_raw, list):',
    ' continue',
    '',
    ' valid_batches: List[List[Dict[str, Any]]] = []',
    ' for b in batches_raw:',
    ' if not isinstance(b, list):',
    ' continue',
    ' rows = [r for r in b if isinstance(r, dict)]',
    ' if rows:',
    ' valid_batches.append(rows)',
    '',
    ' if valid_batches:',
    ' self.error_batches[sid] = valid_batches',
    '',
    ' def check(self, sql_id: str, current_rows: List[Dict[str, Any]]) -> Tuple[bool, str]:',
    ' """domain_term_72fa7545fc，domain_term_11d0241540 (domain_term_dc415262ed, domain_term_61860c9b07)。"""',
    '',
    ' rows = current_rows or []',
    '',
    ' # 1) domain_term_fe239501c6：domain_term_2d635475d5',
    ' if sql_id in self.golden_map:',
    ' golden = self.golden_map.get(sql_id, [])',
    ' try:',
    ' is_same = self.evaluator.evaluate_single_sql(golden, rows)',
    ' except Exception:',
    ' is_same = False',
    '',
    ' if is_same:',
    ' return True, "【Result Match】domain_term_75124eb3d0，domain_term_4b3c9650f8 HistoryGuard domain_term_80144e2e73。"',
    ' return (',
    ' False,',
    ' "[Fatal Error] This question was previously solved CORRECTLY, "',
    ' "but your current SQL produces a DIFFERENT result set.\\n"',
    ' f"Previous (Correct) Row Count: {len(golden)}\\n"',
    ' f"Current Row Count: {len(rows)}\\n"',
    ' "You MUST modify logic to match the previous correct data distribution.",',
    ' )',
    '',
    ' # 2) domain_term_a78c440808：domain_term_4e22c25a02',
    ' batches = self.error_batches.get(sql_id)',
    ' if not batches:',
    ' return True, ""',
    ' for idx, batch in enumerate(batches, start=1):',
    ' try:',
    ' is_same = self.evaluator.evaluate_single_sql(batch, rows)',
    ' except Exception:',
    ' is_same = False',
    ' if is_same:',
    ' advice_str = (',
    ' "1. **Check Output Alignment**: \\n"',
    ' " - Is the result granularity correct (e.g., User level vs. Event level)...\\n"',
    ' " - **Critical**: Are you outputting the EXACT ID type requested (e.g., QQ vs. WXID)...\\n"',
    ' "2. **Check Time & Filter Logic (High-Frequency Error)**: \\n"',
    ' " - **Critical**: Tables often have multiple time columns (e.g., `dteventtime` vs `tdbank_imp_date`). They often contain DIFFERENT data. You MUST probe/verify ALL time columns to select the one that matches the question\'s intent.\\n"',
    ' " - Are there date boundary issues (e.g., exclusive vs inclusive)...\\n"',
    ' " - Your logic reproduces a KNOWN ERROR. Did you miss a hidden condition...\\n"',
    ' "3. **Verify Business Intent & Strategy**: \\n"',
    ' " - **Accuracy > Efficiency**: Do not worry about query performance. Complex joins or subqueries are acceptable if they yield the correct result.\\n"',
    ' " - Re-read the question\'s definition of metrics (e.g., \'Churn\', \'Retention\').\\n"',
    ' " - Are you querying the correct table... (e.g., `dwd` vs `dws` difference)."',
    ' )',
    ' return (',
    ' False,',
    ' f"**[Trap Detected]** Your result matches a known INCORRECT submission (Error Batch #{idx}).\\n"',
    ' "This means you have reproduced a specific past mistake. You MUST change your logic.\\n\\n"',
    ' f"**Diagnostic Protocol**:\\n{advice_str}\\n\\n"',
    ' "**Action**: Do not guess. Use \'PROBE\' to verify which of the above 3 points caused this error.",',
    ' )',
    '',
    ' return True, "【Path Avoidance】domain_term_137b14f8ac，domain_term_408f72691a。"',
    '',
    '',
    'def call_llm_text(',
    ' client: OpenAI,',
    ' model: str,',
    ' provider: str,',
    ' messages: List[Dict[str, str]],',
    ') -> str:',
    ' """domain_term_b1fb011bbf LLM domain_term_93d4bdf816 (domain_term_376eb40fc1 Meta-Analyzer)，domain_term_35d40b6e6f API key domain_term_5c5a62109c。"""',
    ' def _single_call(',
    ' cur_client: OpenAI,',
    ' cur_model: str,',
    ' use_strict_json: bool,',
    ' tag: str,',
    ' ) -> Tuple[Optional[str], str]:',
    ' try:',
    ' resp = cur_client.chat.completions.create(',
    ' model=cur_model,',
    ' messages=messages,',
    ' temperature=0.3,',
    ' )',
    ' text = resp.choices[0].message.content or ""',
    ' return text, "ok"',
    ' except Exception as e:',
    ' msg = str(e)',
    ' safe_msg = msg.replace("¥", "Y")',
    ' print(f"[Meta-Analyzer][{tag}] domain_term_1d1d87767f: {safe_msg}")',
    ' # domain_term_e1d7012c15 quota，domain_term_8be09a9c96 key',
    ' if "insufficient_user_quota" in msg or "domain_term_4358ab83e8" in msg:',
    ' return None, "quota"',
    ' # domain_term_2c2ed6a84f/domain_term_b84cbb8357 busy，domain_term_8da5d7ac85 key domain_term_a80c57055e',
    ' busy_keywords = [',
    ' "domain_term_c24344522f",',
    ' "domain_term_58bba2f93f",',
    ' "domain_term_ce20bdc9b1",',
    ' "domain_term_4cf3d3f7c7",',
    ' "Too Many Requests",',
    ' "too many requests",',
    ' "rate limit",',
    ' "Rate limit",',
    ' "429",',
    ' "API rate limit exceeded",',
    ' ]',
    ' if any(k in msg for k in busy_keywords):',
    ' return None, "busy"',
    ' # domain_term_84cd222db5 key',
    ' return None, "error"',
    '',
    ' def _try_with_keys(',
    ' api_keys: List[str],',
    ' base_url: str,',
    ' model_name: str,',
    ' use_strict_json: bool,',
    ' tag_prefix: str,',
    ' use_initial_client: bool = False,',
    ' provider_name: str = "",',
    ' ) -> Optional[str]:',
    ' if provider_name == "gemini":',
    ' dead_keys = DEAD_GEMINI_KEYS',
    ' elif provider_name == "openai":',
    ' dead_keys = DEAD_OPENAI_KEYS',
    ' else:',
    ' dead_keys = set()',
    '',
    ' for key_index, api_key in enumerate(api_keys):',
    ' if not api_key or api_key in dead_keys:',
    ' continue',
    ' attempt = 0',
    ' while True:',
    ' attempt += 1',
    ' tag = f"{tag_prefix}-k{key_index + 1}-try{attempt}"',
    ' if use_initial_client and key_index == 0 and attempt == 1:',
    ' cur_client = client',
    ' else:',
    ' try:',
    ' cur_client = OpenAI(api_key=api_key, base_url=base_url)',
    ' except Exception as e:',
    ' print(f"[Meta-Analyzer][{tag}] {e}")',
    ' break',
    '',
    ' result, err_type = _single_call(',
    ' cur_client, model_name, use_strict_json, tag=tag',
    ' )',
    ' if result is not None:',
    ' return result',
    ' if err_type == "quota":',
    ' dead_keys.add(api_key)',
    ' print(',
    ' f"[Meta-Analyzer] Key #{key_index + 1} has insufficient quota."',
    ' )',
    ' break',
    ' if err_type == "busy":',
    ' print(',
    ' f"[Meta-Analyzer] Key #{key_index + 1} is busy. Retrying in 30 seconds..."',
    ' )',
    ' time.sleep(30)',
    ' continue',
    ' print(',
    ' f"[Meta-Analyzer] Key #{key_index + 1} failed after {attempt} attempts."',
    ' )',
    ' return None',
    '',
    ' provider_l = (provider or "").lower()',
    ' is_gemini = provider_l == "gemini"',
    '',
    ' if is_gemini:',
    ' primary_keys = [k for k in GEMINI_API_KEYS if k]',
    ' if not primary_keys and GEMINI_API_KEY:',
    ' primary_keys = [GEMINI_API_KEY]',
    ' primary_base_url = GEMINI_BASE_URL',
    ' use_strict_json = False',
    ' else:',
    ' primary_keys = [k for k in OPENAI_API_KEYS if k]',
    ' if not primary_keys and OPENAI_API_KEY:',
    ' primary_keys = [OPENAI_API_KEY]',
    ' primary_base_url = OPENAI_BASE_URL',
    ' use_strict_json = False',
    '',
    ' action = _try_with_keys(',
    ' api_keys=primary_keys,',
    ' base_url=primary_base_url,',
    ' model_name=model,',
    ' use_strict_json=use_strict_json,',
    ' tag_prefix="primary",',
    ' use_initial_client=True,',
    ' provider_name=provider_l,',
    ' )',
    ' if action is not None:',
    ' return action',
    '',
    ' print("[Meta-Analyzer] All primary keys exhausted.")',
    '',
    ' if is_gemini:',
    ' all_gem_keys = [k for k in GEMINI_API_KEYS if k]',
    ' if all_gem_keys and all(k in DEAD_GEMINI_KEYS for k in all_gem_keys):',
    ' print(',
    ' "[Meta-Analyzer] All Gemini keys have insufficient quota. Fallback to OpenAI."',
    ' )',
    ' return "（domain_term_4ddd438a90，domain_term_496ed026a8）"',
    '',
    ' if provider_l == "openai":',
    ' print("[Meta-Analyzer] OpenAI primary keys exhausted. Fallback to backup keys.")',
    ' return "（domain_term_4ddd438a90，domain_term_496ed026a8）"',
    '',
    ' backup_keys = [k for k in OPENAI_API_KEYS if k]',
    ' if not backup_keys and OPENAI_API_KEY:',
    ' backup_keys = [OPENAI_API_KEY]',
    ' if not backup_keys:',
    ' print("[Meta-Analyzer] No backup keys available.")',
    ' return "（domain_term_4ddd438a90，domain_term_496ed026a8）"',
    '',
    ' action = _try_with_keys(',
    ' api_keys=backup_keys,',
    ' base_url=OPENAI_BASE_URL,',
    ' model_name=OPENAI_MODEL,',
    ' use_strict_json=False,',
    ' tag_prefix="fallback-openai",',
    ' use_initial_client=False,',
    ' provider_name="openai",',
    ' )',
    ' if action is not None:',
    ' return action',
    '',
    ' return "（domain_term_4ddd438a90，domain_term_496ed026a8）"',
    '',
    '',
    'def analyze_deadlock(',
    ' client: OpenAI,',
    ' model: str,',
    ' provider: str,',
    ' history: List[Dict[str, str]],',
    ' guard_msg: str,',
    ') -> str:',
    ' """domain_term_2e4fa943d4，domain_term_d97c04e8ae Agent domain_term_512810a41e。"""',
    '',
    ' # domain_term_f0dd12f8cd，domain_term_c9cb131794',
    ' recent_history = history',
    '',
    ' # domain_term_4170cd5063 history domain_term_de0c6eea13',
    ' history_text = json.dumps(recent_history, ensure_ascii=False, indent=2)',
    '',
    ' analysis_prompt = f"""',
    'You are a Lead Data Scientist coaching a Junior Data Agent.',
    'The Agent is trying to solve a SQL problem but is stuck in a loop or making logical errors.',
    'The system has blocked their submission with the following error:',
    '"{guard_msg}"',
    '',
    'Here is the conversation history so far (last 15 turns):',
    '{history_text}',
    '',
    '**Your Task:**',
    'Analyze *why* the agent is failing. Look for these common patterns:',
    '1. **Time Column Hallucination**: Did they assume `dteventtime` is empty without checking... Or did they check it incorrectly (e.g., wrong syntax)... Did they ignore `tdbank_imp_date`...',
    "2. **Filter Trap**: Are they filtering for specific values (e.g., `matchresult='ok'`) that PROBEs have shown to be NULL...",
    '3. **Logical Loop**: Are they repeating the exact same logic that was already rejected...',
    '4. **Data Blindness**: Did they ignore a PROBE result that explicitly contradicted their assumption...',
    '',
    '**Output:**',
    'Provide a concise, specific "Breakthrough Suggestion" addressed directly to the Agent (use "You").',
    '- Do NOT rewrite the full SQL.',
    '- Point out the specific assumption that is blocking them.',
    '- Tell them explicitly what column or value to check next.',
    '- Suggest probing BOTH time columns if they are stuck on one.',
    '"""',
    '',
    ' messages = [{"role": "user", "content": analysis_prompt}]',
    '',
    ' print("\\n[System] domain_term_7341b6d48c Meta-Analyzer domain_term_ee6871b378...")',
    ' advice = call_llm_text(client, model, provider, messages)',
    ' return advice',
    '',
    '',
    'def run_agent_loop(sql_id: str, max_turns: int = MAX_TURNS) -> None:',
    ' client, model, provider = get_llm_client()',
    ' history_guard = HistoryGuard(GOLDEN_RESULT_PATH, ERROR_FEEDBACK_PATH)',
    ' user_message = build_initial_user_message(sql_id)',
    '',
    ' history: List[Dict[str, str]] = [',
    ' {"role": "system", "content": SYSTEM_PROMPT},',
    ' {"role": "user", "content": user_message},',
    ' ]',
    '',
    ' last_final_sql: Optional[str] = None',
    ' last_verified_logic: str = ""',
    '',
    ' for turn in range(1, max_turns + 1):',
    ' print(f"\\n================ Data Detective domain_term_52d27a21f8 {turn}/{max_turns} ================")',
    ' action = call_llm_json(client, model, provider, history)',
    ' if not action:',
    ' print("[Agent] domain_term_f05763476c JSON domain_term_f4eca6a6b0，domain_term_2eee5759c3。")',
    ' return',
    '',
    ' phase = str(action.get("phase", "")).upper()',
    ' thought = str(action.get("thought", "")).strip()',
    ' sql = str(action.get("sql", "")).strip()',
    '',
    ' print(f"[Agent] phase={phase}")',
    ' if thought:',
    ' print(f"[Agent] thought: {thought}")',
    ' if sql:',
    ' print(f"[Agent] sql: {sql}")',
    '',
    ' # domain_term_c8e5fbb03e JSON domain_term_f4eca6a6b0',
    ' history.append({"role": "assistant", "content": json.dumps(action, ensure_ascii=False)})',
    '',
    ' if phase == "PROBE":',
    ' if not sql:',
    ' history.append(',
    ' {',
    ' "role": "user",',
    ' "content": "Your PROBE action must contain a non-empty \'sql\' field.",',
    ' }',
    ' )',
    ' continue',
    '',
    ' print("[Env] domain_term_28febba225 PROBE SQL...")',
    ' result = execute_sql(sql)',
    ' print("result:", result)',
    ' if result.error:',
    ' summary = f"Execution error: {result.error}"',
    ' else:',
    ' # domain_term_aaa9bb956f，domain_term_b482fbfa9a JSON domain_term_01dc16eb7e',
    ' try:',
    ' summary = summarize_result(result.rows)',
    ' except TypeError as e:',
    ' error_msg = str(e)',
    ' if "not JSON serializable" in error_msg:',
    ' feedback = (',
    ' f"[System Error] Your SQL result contains data types that are NOT JSON serializable (e.g., timedelta/duration objects). "',
    ' f"Python Error: {error_msg}.\\n"',
    ' "**REQUIRED ACTION**: Please Rewrite your SQL to cast these columns to Strings or Integers (e.g., use `CAST(col AS CHAR)` or `TIMESTAMPDIFF` to get a number)."',
    ' )',
    ' print(f"[Env] domain_term_58a4291a10，domain_term_994001ec27 SQL: {error_msg}")',
    ' history.append({"role": "user", "content": feedback})',
    ' continue',
    ' else:',
    ' # domain_term_41b8ed5062，domain_term_bd92c9471a',
    ' summary = f"Result serialization error: {error_msg}"',
    '',
    ' feedback = (',
    ' "[Execution Result for PROBE]\\n"',
    ' f"SQL:\\n{sql}\\n\\n"',
    ' f"Summary:\\n{summary}\\n\\n"',
    ' "Based on this result, what is your specific deduction regarding the data logic... "',
    ' "If there are still ambiguities, continue with another PROBE. "',
    ' "If key ambiguities are resolved, move to phase \'SOLVE\' with a candidate final SQL."',
    ' )',
    ' history.append({"role": "user", "content": feedback})',
    ' continue',
    '',
    ' if phase == "SOLVE":',
    ' if not sql:',
    ' history.append(',
    ' {',
    ' "role": "user",',
    ' "content": "Your SOLVE action must contain a non-empty \'sql\' field.",',
    ' }',
    ' )',
    ' continue',
    '',
    ' if not any(',
    ' m.get("role") == "user"',
    ' and "STOP. READ THIS BEFORE OUTPUTTING YOUR FINAL SQL." in m.get("content", "")',
    ' for m in history',
    ' ):',
    ' ultimate_warning = (',
    ' "STOP. READ THIS BEFORE OUTPUTTING YOUR FINAL SQL.\\n\\n"',
    ' "You are about to submit a candidate final answer.\\n"',
    ' "This SQL will be executed and its result set will be compared against:\\n"',
    ' "• All historically correct answers (must match 100% if exists)\\n"',
    ' "• 47+ known wrong result patterns from past failed attempts\\n\\n"',
    ' "If your result matches even ONE known wrong pattern, you will be REJECTED immediately "',
    ' "and forced to start over from PROBE.\\n\\n"',
    ' "Agents who ignore this warning fail. Agents who treat this as a minefield succeed.\\n"',
    ' "Ask yourself:\\n"',
    ' "1. Did I verify which time column actually has data...\\n"',
    ' "2. Did I convert between qq/wxid correctly...\\n"',
    ' "3. Is there a hidden filter like saccounttype=\'-100\' I missed...\\n"',
    ' "4. Is my output granularity what the question really wants...\\n\\n"',
    ' "This is not a drill. Double-check your logic now."',
    ' )',
    ' history.append({"role": "user", "content": ultimate_warning})',
    ' continue # domain_term_202514faf8 SOLVE',
    '',
    ' last_final_sql = sql',
    ' last_verified_logic = str(action.get("verified_logic", "") or "")',
    '',
    ' print("[Env] domain_term_28febba225 SOLVE SQL（domain_term_df3d04f15d SQL）...")',
    ' result = execute_sql(sql)',
    ' if result.error:',
    ' feedback = (',
    ' f"[Error] SQL execution failed: {result.error}. "',
    ' "Please fix your SQL and respond with a new JSON action (phase \'SOLVE\' or \'PROBE\')."',
    ' )',
    ' history.append({"role": "user", "content": feedback})',
    ' continue',
    '',
    ' # ========================== domain_term_c89b633ee7：CRITICAL REJECTION ==========================',
    ' if not result.rows:',
    ' feedback = (',
    ' "**[CRITICAL REJECTION] SQL executed successfully but returned 0 rows.**\\n\\n"',
    ' "An empty result is almost certainly INCORRECT. Please review these common pitfalls:\\n\\n"',
    ' "1. **ID & Table Mismatch (Most Likely)**:\\n"',
    ' " - Are you filtering for a specific user type (e.g., `wxid`) in a table that only stores generic IDs or `qq`...\\n"',
    ' " - **Check `table_list`**: Do you need to join a mapping table (e.g., `dim_...idconversion...` or `dim_...2qq...`) to convert IDs before filtering...\\n\\n"',
    ' "2. **Date & Format Issues**:\\n"',
    ' " - **Format**: Is the date column `YYYYMMDD` (string/int) or `YYYY-MM-DD`... Did you match it correctly...\\n"',
    ' " - **Boundaries**: Are you calculating a date range (e.g., `date_sub`) that falls outside the partition availability...\\n\\n"',
    ' "3. **Implicit Filters & Aggregates**:\\n"',
    ' " - Did you forget a necessary partition filter from \'Knowledge\' (e.g., `saccounttype=\'-100\'` for aggregates)...\\n"',
    ' " - Did you use `INNER JOIN` on a condition that never matches... Try `LEFT JOIN` or check the join keys.\\n\\n"',
    ' "4. **String/Enum Codes**:\\n"',
    ' " - Are you filtering `type=1` (int) vs `type=\'1\'` (string)...\\n"',
    ' " - Are you filtering by a Chinese name (e.g., `mode=\'domain_term_77dec717ea\'`) when the DB uses an English ID or integer code...\\n\\n"',
    ' "**REQUIRED ACTION**:\\n"',
    ' "- **Switch to \'PROBE\' phase** immediately.\\n"',
    ' "- Write a query to `SELECT count(*)` with fewer filters to see where data is lost.\\n"',
    ' "- Verify the existence of your filter values (e.g., `SELECT distinct type ...`)."',
    ' )',
    ' print("[Env] domain_term_741746a54c，domain_term_90cfdb312b。")',
    ' history.append({"role": "user", "content": feedback})',
    ' continue',
    ' # ======================== domain_term_1985fe7e52 ========================',
    '',
    ' # 3) domain_term_9f21c7992f HistoryGuard domain_term_40ffb34860',
    ' is_pass, guard_msg = history_guard.check(sql_id, result.rows)',
    ' if not is_pass:',
    ' print(f"[HistoryGuard] domain_term_1981536581: {guard_msg}")',
    '',
    ' # === [domain_term_2cd9e6ce81] Meta-Analyzer domain_term_d23a468d44 ===',
    ' # domain_term_eceace8994',
    ' analysis_advice = analyze_deadlock(client, model, provider, history, guard_msg)',
    '',
    ' print(f"[Meta-Analyzer] domain_term_c5134eb19c:\\n{analysis_advice}")',
    '',
    ' feedback = (',
    ' f"[History Feedback] {guard_msg}\\n\\n"',
    ' f"================ META-ANALYSIS & BREAKTHROUGH SUGGESTION ================\\n"',
    ' f"{analysis_advice}\\n"',
    ' f"=========================================================================\\n"',
    ' "**INSTRUCTION**: \\n"',
    ' "1. Read the analysis above carefully.\\n"',
    ' "2. STOP guessing. Discard assumptions about empty columns (like `dteventtime`) unless you have a fresh PROBE proving it.\\n"',
    ' "3. If suggested, PROBE both time columns (`dteventtime` AND `tdbank_imp_date`) to see which one aligns with the target data.\\n"',
    ' "4. Switch to phase \'PROBE\' to verify the new hypothesis."',
    ' )',
    ' # === [domain_term_76b9880829] ===',
    '',
    ' history.append({"role": "user", "content": feedback})',
    ' continue',
    '',
    ' if guard_msg:',
    ' # domain_term_e1f7efec8d，domain_term_b256cafec6 guard_msg (warnings)，domain_term_3830891a4f',
    ' history.append({"role": "user", "content": f"[History Feedback] {guard_msg}"})',
    '',
    ' # domain_term_2438489f1e Profile domain_term_c37b2aa19a，domain_term_b482fbfa9a JSON domain_term_01dc16eb7e',
    ' try:',
    ' profile = get_result_profile(result.rows)',
    ' profile_text = json.dumps(profile, ensure_ascii=False, cls=EnhancedJSONEncoder, indent=2)',
    ' except TypeError as e:',
    ' error_msg = str(e)',
    ' if "not JSON serializable" in error_msg:',
    ' feedback = (',
    ' f"[System Error] Your SOLVE SQL result contains columns that are NOT JSON serializable (e.g., timedelta). "',
    ' f"Python Error: {error_msg}.\\n"',
    ' "This prevents me from verifying the result profile.\\n"',
    ' "**REQUIRED ACTION**: Please modify your SQL (phase \'SOLVE\') to CAST duration/time columns to Strings or Numbers explicitly."',
    ' )',
    ' print(f"[Env] SOLVE domain_term_be6367c02c，domain_term_1fa8906254: {error_msg}")',
    ' history.append({"role": "user", "content": feedback})',
    ' continue',
    ' else:',
    ' # domain_term_9e0f46d61a：domain_term_954d18c997，domain_term_44285571aa',
    ' print(f"[Env] domain_term_491148f59d: {e}")',
    ' return',
    '',
    ' review_prompt = (',
    ' "[System Check]\\n"',
    ' "Your SOLVE SQL has been executed successfully. Here is the result profile:\\n"',
    ' f"{profile_text}\\n\\n"',
    ' "Please REVIEW: Does this magnitude and distribution match the user\'s question... "',
    ' "Did you forget any critical filters (e.g., time range, status, game mode)...\\n\\n"',
    ' "If the SQL is correct, reply with a JSON object:\\n"',
    ' " {\\n"',
    ' " \\"phase\\": \\"CONFIRM\\",\\n"',
    ' " \\"thought\\": \\"why the result is reasonable\\",\\n"',
    ' " \\"verified_logic\\": \\"final refined logic summary\\"\\n"',
    ' " }\\n\\n"',
    ' "If the SQL is NOT correct, reply with a JSON object:\\n"',
    ' " {\\n"',
    ' " \\"phase\\": \\"SOLVE\\",\\n"',
    ' " \\"thought\\": \\"what was wrong and how you fix it\\",\\n"',
    ' " \\"sql\\": \\"new SELECT ... SQL\\",\\n"',
    ' " \\"verified_logic\\": \\"updated logic summary\\"\\n"',
    ' " }\\n"',
    ' )',
    '',
    ' history.append({"role": "user", "content": review_prompt})',
    ' continue',
    '',
    ' if phase == "CONFIRM":',
    ' if not last_final_sql:',
    ' print("[Env] domain_term_e37d13e3d7 CONFIRM，domain_term_460cb3306f SOLVE SQL，domain_term_d84129b8be。")',
    ' history.append(',
    ' {',
    ' "role": "user",',
    ' "content": "CONFIRM received but no previous successful SOLVE SQL. Please send a SOLVE action.",',
    ' }',
    ' )',
    ' continue',
    '',
    ' verified_logic = str(action.get("verified_logic", "") or last_verified_logic)',
    ' entry = {',
    ' "sql_id": sql_id,',
    ' "final_sql": last_final_sql,',
    ' "verified_logic": verified_logic,',
    ' "timestamp": datetime.utcnow().isoformat() + "Z",',
    ' }',
    ' append_verified_entry(entry)',
    ' print(f"[Env] domain_term_0b882dba29 {VERIFIED_KB_PATH}。")',
    ' print(json.dumps(entry, ensure_ascii=False, indent=2, cls=EnhancedJSONEncoder))',
    ' return',
    '',
    ' # domain_term_d9c32a4c3d phase',
    ' history.append(',
    ' {',
    ' "role": "user",',
    ' "content": "Your JSON must contain field \'phase\' with value one of: PROBE, SOLVE, CONFIRM.",',
    ' }',
    ' )',
    '',
    ' print("[Agent] domain_term_38ce225127，domain_term_7c828fc304。")',
    '',
    '',
    'def main() -> None:',
    ' parser = argparse.ArgumentParser(description="Data Detective (domain_term_5daa37ca98)")',
    ' parser.add_argument("--max-turns", type=int, default=MAX_TURNS, help="domain_term_4fd40b3334")',
    ' args = parser.parse_args()',
    '',
    ' completed = get_completed_sql_ids()',
    ' if completed:',
    ' print(f"[Agent] domain_term_e43bf9dd77: {sorted(completed)}")',
    ' print(f"[Agent] domain_term_964c776e27: {VERIFIED_KB_PATH}")',
    ' else:',
    ' print(f"[Agent] domain_term_964c776e27: {VERIFIED_KB_PATH} (domain_term_c979ad4227)")',
    '',
    ' for sql_id in SQL_ID_LIST:',
    ' if sql_id in completed:',
    ' print(f"[Agent] domain_term_978bae37a8 {sql_id}")',
    ' continue',
    ' print(f"\\n=========== domain_term_8d6fedc36a {sql_id} ===========")',
    ' run_agent_loop(sql_id, max_turns=args.max_turns)',
    '',
    '',
    'if __name__ == "__main__":',
    ' main()',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
