# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `1.knowledge_base/1.1_schema_completion_knowledge_base/analyze_data.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    'import mysql.connector',
    'import json',
    'import os',
    'import re',
    'from datasketch import MinHash',
    'from tqdm import tqdm',
    'import warnings',
    'import decimal',
    '',
    '# --- 1. domain_term_d7d7ce790b ---',
    '',
    '# !! domain_term_0829c90725 !!',
    '# !! domain_term_675710c391 !!',
    'DB_CONFIG = {',
    " 'host': '172.22.194.247',",
    " 'port': 9030,",
    " 'user': 'root',",
    " 'password': '',",
    " 'database': 'final_algorithm_competition' # <--- domain_term_54b307ed71",
    '}',
    '',
    "SCHEMA_FILE = 'schema.json'",
    "OUTPUT_DIR = 'profiling_output_per_table' # domain_term_3c0fa6e308",
    'MINHASH_PERMUTATIONS = 128',
    'TOP_K_COUNT = 10',
    'PREFIX_COUNT = 5',
    'CHARSET_SAMPLE_SIZE = 100',
    'MINHASH_SAMPLE_SIZE = 10000 # domain_term_d6a80d904c N=10000',
    '',
    '# --- 2. domain_term_0025bb7dd1 ---',
    '',
    '# domain_term_c95040b419',
    "REGEX_NUMERIC = re.compile(r'^[0-9\\.\\,\\-]+$') # domain_term_e7fdf5d139、domain_term_1cc3e96233、domain_term_365c5928ec、domain_term_f7c9364728",
    "REGEX_ALPHA = re.compile(r'^[a-zA-Z]+$')",
    "REGEX_ALPHANUM = re.compile(r'^[a-zA-Z0-9]+$')",
    '',
    'def analyze_charset(samples):',
    ' """',
    ' domain_term_9c7839d206。',
    ' """',
    ' stats = {',
    ' "count": len(samples),',
    ' "all_numeric": True,',
    ' "all_alpha": True,',
    ' "all_alphanumeric": True,',
    ' "json_like_pct": 0.0,',
    ' "other_special_char_pct": 0.0',
    ' }',
    ' if not samples:',
    ' return {"error": "no samples found"}',
    '',
    ' json_like_count = 0',
    ' other_count = 0',
    '',
    ' for s in samples:',
    ' s_str = str(s) # domain_term_c8862e4360',
    ' if not REGEX_NUMERIC.match(s_str):',
    ' stats["all_numeric"] = False',
    ' if not REGEX_ALPHA.match(s_str):',
    ' stats["all_alpha"] = False',
    ' if not s_str.isalnum():',
    ' stats["all_alphanumeric"] = False',
    '',
    " if (s_str.startswith('{') and s_str.endswith('}')) or (s_str.startswith('[') and s_str.endswith(']')):",
    ' json_like_count += 1',
    '',
    ' # domain_term_89bf8f49c7，domain_term_6a376714d5，domain_term_0264a42224',
    ' if not s_str.isalnum() and not REGEX_NUMERIC.match(s_str) and not REGEX_ALPHA.match(s_str):',
    ' other_count += 1',
    '',
    ' # domain_term_6d362c7b93 len(samples) > 0',
    ' if len(samples) > 0:',
    ' stats["json_like_pct"] = round((json_like_count / len(samples)) * 100, 2)',
    ' stats["other_special_char_pct"] = round((other_count / len(samples)) * 100, 2)',
    '',
    ' # domain_term_ae6793819c',
    ' if stats["all_numeric"]:',
    ' stats["all_alpha"] = False',
    ' stats["all_alphanumeric"] = False',
    '',
    ' return stats',
    '',
    'def get_minhash(samples):',
    ' """',
    ' domain_term_6b53e5e634 MinHash domain_term_8ba46c43fe。',
    ' """',
    ' m = MinHash(num_perm=MINHASH_PERMUTATIONS)',
    ' if not samples:',
    ' return None',
    ' for d in samples:',
    ' if d is not None:',
    " m.update(str(d).encode('utf8'))",
    '',
    ' # domain_term_11d0241540 hashvalues domain_term_d46f82fdf0，domain_term_4f37457fe8 JSON domain_term_0aa2f4ad8a',
    ' return m.hashvalues.tolist()',
    '',
    'def safe_json_serialize(obj):',
    ' """',
    ' domain_term_ed6473b1d2（domain_term_76ce4f0238 Decimal）domain_term_c2787f5124 JSON domain_term_2b48048279。',
    ' """',
    ' if isinstance(obj, decimal.Decimal):',
    ' return float(obj)',
    ' if isinstance(obj, bytes):',
    ' try:',
    " return obj.decode('utf-8')",
    ' except UnicodeDecodeError:',
    ' return obj.hex()',
    ' return str(obj)',
    '',
    '# --- 3. domain_term_97583db9e6 ---',
    '',
    'def profile_database():',
    ' """',
    ' domain_term_526044b109 schema.json domain_term_72173a5ab9/domain_term_53fe24d348。',
    ' """',
    ' # domain_term_d84129b8be mysql-connector domain_term_288ee01642',
    ' # (domain_term_b65e008458)',
    ' # warnings.filterwarnings("ignore", category=mysql.connector.errors.MySQLWarning)',
    '',
    ' # domain_term_837e9a9c6b (domain_term_884d3fe35c)',
    " if DB_CONFIG['database'] == 'PLEASE_FILL_IN_DATABASE_NAME':",
    ' print("="*50)',
    ' print("!! domain_term_b859c7be75：domain_term_20cbd9fe98 `DATABASE_NAME` domain_term_b418ca60d4。")',
    ' print("="*50)',
    ' return',
    '',
    ' # domain_term_b148eb03ce',
    ' os.makedirs(OUTPUT_DIR, exist_ok=True)',
    ' print(f"domain_term_c82a1257b1: {os.path.abspath(OUTPUT_DIR)}")',
    '',
    ' # domain_term_3363f3729b schema',
    ' try:',
    " with open(SCHEMA_FILE, 'r', encoding='utf-8') as f:",
    ' schema = json.load(f)',
    ' except FileNotFoundError:',
    ' print(f"!! domain_term_b859c7be75：domain_term_df5ccaf092 {SCHEMA_FILE}。domain_term_2629b39db7。")',
    ' return',
    ' except json.JSONDecodeError:',
    ' print(f"!! domain_term_b859c7be75：{SCHEMA_FILE} domain_term_9395aacc51 JSON domain_term_49deaf7da2。")',
    ' return',
    '',
    ' print(f"domain_term_b19bae5d13 schema，domain_term_f896fb3776 {len(schema)} domain_term_5026aa811e。")',
    '',
    ' conn = None',
    ' try:',
    ' # --- domain_term_f50c79f4a9 ---',
    ' print(f"domain_term_ceee3680e6 {DB_CONFIG[\'host\']}:{DB_CONFIG[\'port\']}...")',
    ' conn = mysql.connector.connect(**DB_CONFIG)',
    ' print("domain_term_eb06635875。")',
    '',
    ' # --- domain_term_605cb28c0d ---',
    ' for table in tqdm(schema, desc="domain_term_562d1d2725 (domain_term_6a954390e3)"):',
    " table_name = table['table_name']",
    '',
    ' # --- domain_term_2e0e9bb579：domain_term_e700997184 ---',
    ' total_records = 0',
    ' try:',
    ' with conn.cursor() as cursor:',
    ' # domain_term_fae6ef7721 ` ` domain_term_5f7dc8b5b5',
    ' cursor.execute(f"SELECT COUNT(*) FROM `{table_name}`")',
    ' total_records = cursor.fetchone()[0]',
    ' except Exception as e:',
    ' print(f"domain_term_b859c7be75：domain_term_ff991d6c91 {table_name} domain_term_b9af9b2593: {e}")',
    ' print("domain_term_d2475dc119...")',
    '',
    ' # *** domain_term_2cd9e6ce81：domain_term_e236ccb257，domain_term_d252ecd894 ***',
    ' error_profile = {',
    ' "table_name": table_name,',
    ' "table_description": table.get("table_description", ""),',
    ' "total_records": 0,',
    ' "errors": [f"domain_term_6201cf408a: {e}"],',
    ' "columns_profile": []',
    ' }',
    ' output_filename = os.path.join(OUTPUT_DIR, f"profile_{table_name}.json")',
    ' try:',
    " with open(output_filename, 'w', encoding='utf-8') as f:",
    ' json.dump(error_profile, f, ensure_ascii=False, indent=4)',
    ' except Exception as write_e:',
    ' print(f"!! domain_term_491148f59d: domain_term_7a7c603268 JSON domain_term_49deaf7da2 {output_filename}: {write_e}")',
    '',
    ' continue # domain_term_ce46f8ae9a',
    '',
    ' # *** domain_term_2cd9e6ce81：domain_term_465bd638b0 ***',
    ' all_columns_profile = []',
    '',
    ' # --- domain_term_e9f997ce2b ---',
    ' for column in tqdm(table[\'columns\'], desc=f"domain_term_16d0f4b1ea {table_name}", leave=False):',
    " col_name = column['col']",
    " col_type = column['type']",
    '',
    ' # domain_term_b7a385ec00 StarRocks domain_term_bc35551682（domain_term_76ce4f0238 BITMAP）domain_term_b859443fad',
    " is_complex_type = col_type.lower() in ['bitmap', 'hll', 'percentile', 'json']",
    '',
    ' # domain_term_196e111309 *domain_term_d97b59b582* domain_term_5cba4c1609',
    ' column_profile = {',
    ' "column_name": col_name,',
    ' "column_type": col_type,',
    ' "null_values": None,',
    ' "cardinality": None,',
    ' "shape": {',
    ' "min_length": None,',
    ' "max_length": None,',
    ' "avg_length": None,',
    ' "min_value": None,',
    ' "max_value": None,',
    ' "charset_analysis": None,',
    ' "top_prefixes": None',
    ' },',
    ' "top_k_values": None,',
    ' "minhash_signature": None,',
    ' "errors": []',
    ' }',
    '',
    ' # --- domain_term_8c0f5ef8b1（NULL, domain_term_080e485aa9, domain_term_c04e0db9ef） ---',
    ' if not is_complex_type:',
    ' try:',
    ' q1_sql = f"""',
    ' SELECT',
    ' COUNT(CASE WHEN `{col_name}` IS NULL THEN 1 END),',
    ' COUNT(DISTINCT `{col_name}`),',
    ' MIN(LENGTH(CAST(`{col_name}` AS STRING))),',
    ' MAX(LENGTH(CAST(`{col_name}` AS STRING))),',
    ' AVG(LENGTH(CAST(`{col_name}` AS STRING)))',
    ' FROM `{table_name}`',
    ' """',
    ' with conn.cursor() as cursor:',
    ' cursor.execute(q1_sql)',
    ' res = cursor.fetchone()',
    ' column_profile["null_values"] = int(res[0])',
    ' column_profile["cardinality"] = int(res[1])',
    ' column_profile["shape"]["min_length"] = int(res[2]) if res[2] is not None else None',
    ' column_profile["shape"]["max_length"] = int(res[3]) if res[3] is not None else None',
    ' column_profile["shape"]["avg_length"] = float(res[4]) if res[4] is not None else None',
    ' except Exception as e:',
    ' error_msg = f"domain_term_711363c424 1 (Combined Stats) domain_term_3e3c8068bb: {e}"',
    ' print(f"domain_term_5521e368d8: {table_name}.{col_name} - {error_msg}")',
    ' column_profile["errors"].append(error_msg)',
    '',
    ' # --- Min/Max domain_term_711363c424（domain_term_8fa7401e90 CAST，domain_term_e53202585e/domain_term_d34978b195） ---',
    ' if not is_complex_type:',
    ' try:',
    ' q_minmax_sql = f"SELECT MIN(`{col_name}`), MAX(`{col_name}`) FROM `{table_name}` WHERE `{col_name}` IS NOT NULL"',
    ' with conn.cursor() as cursor:',
    ' cursor.execute(q_minmax_sql)',
    ' res = cursor.fetchone()',
    ' column_profile["shape"]["min_value"] = safe_json_serialize(res[0])',
    ' column_profile["shape"]["max_value"] = safe_json_serialize(res[1])',
    ' except Exception as e:',
    ' error_msg = f"domain_term_711363c424 1.5 (Min/Max) domain_term_3e3c8068bb: {e}"',
    ' print(f"domain_term_5521e368d8: {table_name}.{col_name} - {error_msg}")',
    ' column_profile["errors"].append(error_msg)',
    '',
    ' # --- Top-K domain_term_711363c424 ---',
    ' try:',
    ' q2_sql = f"SELECT `{col_name}`, COUNT(*) as Freq FROM `{table_name}` WHERE `{col_name}` IS NOT NULL GROUP BY `{col_name}` ORDER BY Freq DESC LIMIT {TOP_K_COUNT}"',
    ' with conn.cursor() as cursor:',
    ' cursor.execute(q2_sql)',
    ' column_profile["top_k_values"] = [',
    ' [safe_json_serialize(row[0]), int(row[1])] for row in cursor.fetchall()',
    ' ]',
    ' except Exception as e:',
    ' error_msg = f"domain_term_711363c424 2 (Top-K) domain_term_3e3c8068bb: {e}"',
    ' print(f"domain_term_5521e368d8: {table_name}.{col_name} - {error_msg}")',
    ' column_profile["errors"].append(error_msg)',
    '',
    ' # --- domain_term_6f0e081f16 ---',
    ' if not is_complex_type:',
    ' try:',
    ' q3_sql = f"SELECT LEFT(CAST(`{col_name}` AS STRING), 1) as Prefix, COUNT(*) as Freq FROM `{table_name}` WHERE `{col_name}` IS NOT NULL GROUP BY Prefix ORDER BY Freq DESC LIMIT {PREFIX_COUNT}"',
    ' with conn.cursor() as cursor:',
    ' cursor.execute(q3_sql)',
    ' column_profile["shape"]["top_prefixes"] = [',
    ' [safe_json_serialize(row[0]), int(row[1])] for row in cursor.fetchall()',
    ' ]',
    ' except Exception as e:',
    ' error_msg = f"domain_term_711363c424 3 (Prefixes) domain_term_3e3c8068bb: {e}"',
    ' print(f"domain_term_5521e368d8: {table_name}.{col_name} - {error_msg}")',
    ' column_profile["errors"].append(error_msg)',
    '',
    ' # --- domain_term_22d9064fc3 (domain_term_376eb40fc1 Charset domain_term_9a3eb34097 MinHash) ---',
    ' samples_for_charset = []',
    ' samples_for_minhash = []',
    ' try:',
    ' q4_sql = f"SELECT `{col_name}` FROM `{table_name}` WHERE `{col_name}` IS NOT NULL LIMIT {CHARSET_SAMPLE_SIZE}"',
    ' with conn.cursor() as cursor:',
    ' cursor.execute(q4_sql)',
    ' samples_for_charset = [row[0] for row in cursor.fetchall() if row[0] is not None]',
    '',
    ' q5_sql = f"SELECT DISTINCT `{col_name}` FROM `{table_name}` WHERE `{col_name}` IS NOT NULL LIMIT {MINHASH_SAMPLE_SIZE}"',
    ' with conn.cursor() as cursor:',
    ' cursor.execute(q5_sql)',
    ' samples_for_minhash = [row[0] for row in cursor.fetchall() if row[0] is not None]',
    '',
    ' except Exception as e:',
    ' error_msg = f"domain_term_711363c424 4/5 (Sampling) domain_term_3e3c8068bb: {e}"',
    ' print(f"domain_term_5521e368d8: {table_name}.{col_name} - {error_msg}")',
    ' column_profile["errors"].append(error_msg)',
    '',
    ' # --- Python domain_term_7efb37f6d8 ---',
    ' if samples_for_charset:',
    ' column_profile["shape"]["charset_analysis"] = analyze_charset(samples_for_charset)',
    '',
    ' if samples_for_minhash:',
    ' column_profile["minhash_signature"] = get_minhash(samples_for_minhash)',
    '',
    ' # *** domain_term_2cd9e6ce81：domain_term_a9c83eb940 ***',
    ' all_columns_profile.append(column_profile)',
    '',
    ' # --- (domain_term_50f30fdc5a) ---',
    '',
    ' # *** domain_term_2cd9e6ce81：domain_term_b1f553e76c JSON ***',
    ' final_table_profile = {',
    ' "table_name": table_name,',
    ' "table_description": table.get("table_description", ""), # domain_term_8ab977960a schema.json domain_term_7e2b70264d',
    ' "total_records": int(total_records),',
    ' "errors": [], # domain_term_10d6ee0b9f（domain_term_c7edaf4d2b，domain_term_5922408183 continue domain_term_a5933e2a9e）',
    ' "columns_profile": all_columns_profile',
    ' }',
    '',
    ' # *** domain_term_2cd9e6ce81：domain_term_33eb1c5664 *domain_term_6a954390e3* domain_term_0746bd6249 JSON domain_term_49deaf7da2 ***',
    ' output_filename = os.path.join(OUTPUT_DIR, f"profile_{table_name}.json")',
    ' try:',
    " with open(output_filename, 'w', encoding='utf-8') as f:",
    ' json.dump(final_table_profile, f, ensure_ascii=False, indent=4)',
    ' except Exception as e:',
    ' print(f"!! domain_term_491148f59d: domain_term_28c4af8279 JSON domain_term_49deaf7da2 {output_filename}: {e}")',
    '',
    ' # --- (domain_term_85611180bb) ---',
    '',
    ' except mysql.connector.Error as err:',
    ' print(f"!! domain_term_491148f59d: domain_term_b74fcc1269: {err}")',
    ' if err.errno == 1045: # Access denied',
    ' print("domain_term_677a5a011d。")',
    ' elif err.errno == 1049: # Unknown database',
    ' print(f"domain_term_f4dbbc63a5 \'{DB_CONFIG[\'database\']}\' domain_term_0d864b52e3。domain_term_71a9bfa51c `DATABASE_NAME` domain_term_b418ca60d4。")',
    " elif err.errno == 2003: # Can't connect",
    ' print(f"domain_term_8784f98596 {DB_CONFIG[\'host\']}:{DB_CONFIG[\'port\']}。domain_term_c1f9b4d9ec、domain_term_bb95fb731d。")',
    ' finally:',
    ' if conn and conn.is_connected():',
    ' conn.close()',
    ' print("\\ndomain_term_e542fc120f。")',
    '',
    ' print("="*50)',
    ' print("domain_term_fe0ccad125！")',
    ' print(f"domain_term_b9cb93f230 \'{OUTPUT_DIR}\' domain_term_3b3a590eb0 JSON domain_term_49deaf7da2。")',
    ' print("="*50)',
    '',
    '# --- 4. domain_term_15d71d4241 ---',
    'if __name__ == "__main__":',
    ' profile_database()',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
