# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `1.knowledge_base/1.1_schema_completion_knowledge_base/analyza_join.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    'import mysql.connector',
    'import json',
    'import os',
    'import glob',
    'import itertools',
    'from datasketch import MinHash',
    'from tqdm import tqdm',
    'import warnings',
    'import decimal',
    '',
    '# --- 1. domain_term_d7d7ce790b ---',
    '',
    '# domain_term_e3de09d5c5 (domain_term_8ab977960a profile domain_term_7f57f6630b)',
    'DB_CONFIG = {',
    " 'host': '172.22.194.247',",
    " 'port': 9030,",
    " 'user': 'root',",
    " 'password': '',",
    " 'database': 'final_algorithm_competition' # domain_term_79cc4e05ff",
    '}',
    '',
    '# domain_term_06a360a3fc JSON domain_term_0fd3a9b4ea',
    "DATASET_FILE = 'final_dataset.json' # domain_term_f896fb3776 table_list domain_term_0746bd6249 JSON domain_term_49deaf7da2",
    "PROFILING_DIR = 'profiling_output_per_table' # domain_term_da2b363c48",
    "OUTPUT_FILE = 'join_candidates_verified.json' # domain_term_946e037dc8",
    '',
    '# domain_term_c8e8a8ce25',
    'MINHASH_PERMUTATIONS = 128 # domain_term_31087384ef1domain_term_4c53896b87',
    'JACCARD_THRESHOLD = 0.8 # Jaccard domain_term_aafc354587 80% domain_term_dec47adc6e',
    '# 1. domain_term_1d05ac1206，domain_term_a466ccfa6e 1',
    'MIN_CARDINALITY_FOR_JOIN = 1 # domain_term_2ef658910c：domain_term_c99ef0b972 1 domain_term_7247f21016“domain_term_c9b0ce97f7”',
    '',
    '# --- 2. domain_term_95c0581f3a ---',
    '',
    'def load_all_profiles():',
    ' """',
    ' domain_term_c063eb33ce JSON domain_term_49deaf7da2，domain_term_da9401c66e。',
    ' domain_term_11d0241540: dict[table_name, list_of_column_profiles]',
    ' """',
    ' all_profiles_by_table = {}',
    ' json_files = glob.glob(os.path.join(PROFILING_DIR, "*.json"))',
    '',
    ' if not json_files:',
    ' print(f"!! domain_term_b859c7be75：domain_term_686b703f41 \'{PROFILING_DIR}\' domain_term_8c4c2b1cd6 JSON domain_term_49deaf7da2。")',
    ' print("domain_term_fa303a7e8f \'profile_database_per_table.py\' domain_term_7fbccbeb8a。")',
    ' return None',
    '',
    ' print(f"domain_term_4665eb89e7 {len(json_files)} domain_term_6bd916be82...")',
    '',
    ' for f_path in tqdm(json_files, desc="domain_term_4cc627a46f"):',
    ' try:',
    " with open(f_path, 'r', encoding='utf-8') as f:",
    ' table_profile = json.load(f)',
    '',
    ' table_name = table_profile.get("table_name")',
    ' total_records = table_profile.get("total_records", 0)',
    '',
    ' if total_records == 0 or not table_name:',
    ' continue # domain_term_18f5927956',
    '',
    ' table_columns = []',
    ' for col_profile in table_profile.get("columns_profile", []):',
    ' signature = col_profile.get("minhash_signature")',
    ' cardinality = col_profile.get("cardinality")',
    '',
    ' # ** domain_term_2ef658910c：domain_term_8639be0721 MinHash domain_term_b64e9b6e0d, domain_term_e10fdfcea0，domain_term_6c222ec9a1 **',
    ' if signature and cardinality and cardinality > MIN_CARDINALITY_FOR_JOIN:',
    ' # domain_term_4170cd5063 MinHash domain_term_8ba46c43fe（domain_term_d46f82fdf0）domain_term_a0b2aaea5d MinHash domain_term_539cb3b0a6',
    ' try:',
    ' col_profile["minhash_obj"] = MinHash(num_perm=MINHASH_PERMUTATIONS, hashvalues=signature)',
    ' table_columns.append(col_profile)',
    ' except ValueError:',
    ' print(f"domain_term_5521e368d8：{table_name}.{col_profile.get(\'column_name\')} domain_term_1657d68f99。")',
    '',
    ' if table_columns:',
    ' all_profiles_by_table[table_name] = table_columns',
    '',
    ' except Exception as e:',
    ' print(f"domain_term_5521e368d8：domain_term_5f86a4e01b {f_path}: {e}")',
    '',
    ' print(f"domain_term_1f5ac46896。domain_term_523e40a074 {len(all_profiles_by_table)} domain_term_ff2c6a7386。")',
    ' return all_profiles_by_table',
    '',
    '# --- 3. domain_term_358e6d8097 (domain_term_98f32fad0a) ---',
    '',
    'def verify_join_with_db(t1_name, c1_name, t2_name, c2_name, conn):',
    ' """',
    ' 2. domain_term_e8ea96edb8 JOIN LIMIT 1 domain_term_9c708fcf34。',
    ' """',
    ' query = f"""',
    ' SELECT 1',
    ' FROM `{t1_name}` AS t1',
    ' INNER JOIN `{t2_name}` AS t2 ON t1.`{c1_name}` = t2.`{c2_name}`',
    ' LIMIT 1',
    ' """',
    ' try:',
    ' with conn.cursor() as cursor:',
    ' cursor.execute(query)',
    ' cursor.fetchone() # domain_term_d3dd227068',
    ' return True # domain_term_eabbc2c9be',
    ' except mysql.connector.Error as e:',
    ' # domain_term_24a9af6fab JOIN domain_term_3e3c8068bb（domain_term_a420c3da03），domain_term_97b2c7fdd5 False',
    ' # print(f" domain_term_31231e79d7: {t1_name}.{c1_name} x {t2_name}.{c2_name} | domain_term_b859c7be75: {e}")',
    ' return False',
    ' except Exception as e:',
    ' # domain_term_592067fa8d',
    ' # print(f" domain_term_1ceec7bdef: {e}")',
    ' return False',
    '',
    '# --- 4. domain_term_ea94027944 MinHash (domain_term_b53173a378) ---',
    '',
    'def analyze_join_candidates(table_a_name, table_a_cols, table_b_name, table_b_cols, conn):',
    ' """',
    ' domain_term_ecba342e8b。',
    ' """',
    ' candidates = []',
    '',
    ' for col_a in table_a_cols:',
    ' for col_b in table_b_cols:',
    '',
    ' col_a_name = col_a["column_name"]',
    ' col_b_name = col_b["column_name"]',
    '',
    ' try:',
    ' # domain_term_27849e9d21 Jaccard domain_term_087f8c3c44',
    ' jaccard = col_a["minhash_obj"].jaccard(col_b["minhash_obj"])',
    '',
    ' # domain_term_f3cabdba58...',
    ' if jaccard >= JACCARD_THRESHOLD:',
    '',
    ' # 2. domain_term_c2b95a49b7',
    ' is_verified = verify_join_with_db(',
    ' table_a_name, col_a_name,',
    ' table_b_name, col_b_name,',
    ' conn',
    ' )',
    '',
    ' if is_verified:',
    ' candidates.append({',
    ' "column_A": f"{table_a_name}.{col_a_name}",',
    ' "column_B": f"{table_b_name}.{col_b_name}",',
    ' "jaccard_similarity": round(jaccard, 4),',
    ' "cardinality_A": col_a["cardinality"],',
    ' "cardinality_B": col_b["cardinality"],',
    ' "verified_by_db_join": True',
    ' })',
    ' # else:',
    ' # (domain_term_53e32830a5) domain_term_1f02338673 MinHash domain_term_03091d8aee JOIN domain_term_2d7d10f6ab',
    ' # print(f" MinHash domain_term_03091d8aee JOIN domain_term_3e3c8068bb: {table_a_name}.{col_a_name} <-> {table_b_name}.{col_b_name}")',
    '',
    ' except Exception as e:',
    ' print(f"domain_term_5521e368d8：domain_term_ea94027944 {table_a_name}.{col_a_name} domain_term_9a3eb34097 {table_b_name}.{col_b_name} domain_term_e1349a1021: {e}")',
    '',
    ' return candidates',
    '',
    '# --- 5. domain_term_152e14c461 (domain_term_327faed623) ---',
    '',
    'def main():',
    ' # domain_term_981b3b9b4b',
    ' all_profiles_by_table = load_all_profiles()',
    ' if not all_profiles_by_table:',
    ' return',
    '',
    ' # 3. domain_term_2450cc0d6f',
    ' try:',
    " with open(DATASET_FILE, 'r', encoding='utf-8') as f:",
    ' tasks = json.load(f)',
    ' # domain_term_51b538bb37',
    ' if not isinstance(tasks, list):',
    ' tasks = [tasks]',
    ' except FileNotFoundError:',
    ' print(f"!! domain_term_b859c7be75：domain_term_df5ccaf092 {DATASET_FILE}。domain_term_e36808b03e。")',
    ' print(f"domain_term_1a3acaa8f4:\\n[ {json.dumps(json.loads(user_request_snippet), indent=4)} ]")',
    ' return',
    ' except Exception as e:',
    ' print(f"!! domain_term_b859c7be75：domain_term_3363f3729b {DATASET_FILE} domain_term_3e3c8068bb: {e}")',
    ' return',
    '',
    ' all_join_candidates = []',
    ' processed_pairs = set() # domain_term_705dd070ae',
    '',
    ' conn = None',
    ' try:',
    ' # domain_term_4ce8688515，domain_term_aa052cea6d',
    ' print(f"domain_term_ceee3680e6 {DB_CONFIG[\'host\']}:{DB_CONFIG[\'port\']} domain_term_b9db7de396 JOIN...")',
    ' conn = mysql.connector.connect(**DB_CONFIG)',
    ' print("domain_term_eb06635875。")',
    '',
    ' # 3. domain_term_bdb50b62e3',
    ' for task in tqdm(tasks, desc="domain_term_f269c84db9"):',
    ' table_list = task.get("table_list")',
    ' if not table_list or len(table_list) < 2:',
    ' continue',
    '',
    ' # domain_term_b7a385ec00 list domain_term_1071d810d7',
    ' for table_a_name, table_b_name in itertools.combinations(table_list, 2):',
    ' pair_key = tuple(sorted((table_a_name, table_b_name)))',
    ' if pair_key in processed_pairs:',
    ' continue # domain_term_c4a837368b',
    ' processed_pairs.add(pair_key)',
    '',
    ' # domain_term_45d4f8c4ee',
    ' table_a_cols = all_profiles_by_table.get(table_a_name)',
    ' table_b_cols = all_profiles_by_table.get(table_b_name)',
    '',
    ' if not table_a_cols:',
    ' print(f"domain_term_5521e368d8：domain_term_a0ba472b80 \'{table_a_name}\' domain_term_cdd4581a3c，domain_term_31a98593f1。")',
    ' continue',
    ' if not table_b_cols:',
    ' print(f"domain_term_5521e368d8：domain_term_a0ba472b80 \'{table_b_name}\' domain_term_cdd4581a3c，domain_term_31a98593f1。")',
    ' continue',
    '',
    ' # domain_term_cd9fab4d2b',
    ' candidates = analyze_join_candidates(',
    ' table_a_name, table_a_cols,',
    ' table_b_name, table_b_cols,',
    ' conn',
    ' )',
    ' all_join_candidates.extend(candidates)',
    '',
    ' except mysql.connector.Error as err:',
    ' print(f"!! domain_term_491148f59d: domain_term_b74fcc1269: {err}")',
    ' return',
    ' finally:',
    ' if conn and conn.is_connected():',
    ' conn.close()',
    ' print("\\ndomain_term_e542fc120f。")',
    '',
    ' # --- 6. domain_term_66f2b8b09f ---',
    '',
    ' # domain_term_29b20565f2（domain_term_c2f36bf3f3）',
    ' unique_candidates = {json.dumps(dict(sorted(c.items()))): c for c in all_join_candidates}.values()',
    ' sorted_candidates = sorted(unique_candidates, key=lambda x: x["jaccard_similarity"], reverse=True)',
    '',
    ' print("="*50)',
    ' print(f"domain_term_1f481168be。domain_term_523e40a074 {len(sorted_candidates)} domain_term_f7b2a6ee68 *domain_term_b2a8bb0e10* domain_term_d6247af2db：")',
    '',
    ' # domain_term_7f4fc1b308 20 domain_term_b3feeeef41',
    ' for cand in sorted_candidates[:20]:',
    ' print(f" - {cand[\'jaccard_similarity\'] * 100:.1f}%: {cand[\'column_A\']} <-> {cand[\'column_B\']}")',
    '',
    ' if len(sorted_candidates) > 20:',
    ' print(f" ... (domain_term_46870e4b89 {len(sorted_candidates) - 20} domain_term_f7b2a6ee68)")',
    '',
    ' # domain_term_c7b497c5ec JSON',
    ' try:',
    " with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:",
    ' json.dump(sorted_candidates, f, ensure_ascii=False, indent=4)',
    ' print(f"\\ndomain_term_f5189c859f: {os.path.abspath(OUTPUT_FILE)}")',
    ' except Exception as e:',
    ' print(f"\\n!! domain_term_491148f59d: domain_term_28c4af8279 JSON domain_term_49deaf7da2 {OUTPUT_FILE}: {e}")',
    '',
    'if __name__ == "__main__":',
    ' # domain_term_6be2da059b main() domain_term_32f0ac82cc',
    ' user_request_snippet = """',
    ' {',
    ' "sql_id": "sql_1",',
    ' "question": "...",',
    ' "table_list": [',
    ' "dws_mgamejp_login_user_activity_di",',
    ' "dim_vplayerid_vies_df"',
    ' ]',
    ' }',
    ' """',
    ' main()',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
