# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `1.knowledge_base/1.1_schema_completion_knowledge_base/merge_llm_to_schema.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    'import json',
    'import argparse',
    'from pathlib import Path',
    'from typing import Dict, List, Optional',
    '',
    'from config import BASE_DIR',
    '',
    '',
    'DATA_DIR = BASE_DIR / "data"',
    'SCHEMA_FILE = DATA_DIR / "schema.json"',
    'PROFILING_DIR = DATA_DIR / "profiling_output_merged"',
    'OUTPUT_FILE = DATA_DIR / "schema_all.json"',
    'RUN_AGENT_SCHEMA_FILE = BASE_DIR / "run" / "agent" / "schema.json"',
    'COLUMN_MISS_REPORT_FILE = BASE_DIR / "run" / "agent" / "column_miss_empty_report.json"',
    '',
    '',
    'def _load_json(path: Path) -> Optional[dict]:',
    ' try:',
    ' with path.open("r", encoding="utf-8") as f:',
    ' return json.load(f)',
    ' except FileNotFoundError:',
    ' print(f"[warn] domain_term_ffcf0a1eb0: {path}")',
    ' return None',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"[warn] domain_term_d9f607a200 {path}: {e}")',
    ' return None',
    '',
    '',
    'def _load_all_null_columns() -> Dict[str, List[str]]:',
    ' """domain_term_8ab977960a column_miss_empty_report.json domain_term_d2718b0604。',
    '',
    ' domain_term_4ea192405d: {table_name: [col1, col2, ...]}',
    ' domain_term_06d0f9552a，domain_term_a9e322769d dict，domain_term_415011d214。',
    ' """',
    '',
    ' if not COLUMN_MISS_REPORT_FILE.exists():',
    ' return {}',
    '',
    ' data = _load_json(COLUMN_MISS_REPORT_FILE)',
    ' if not isinstance(data, list):',
    ' print(',
    ' f"[warn] {COLUMN_MISS_REPORT_FILE} domain_term_747bdc1344(domain_term_e5d9c6c8a8 list)，domain_term_37f16c0b35。",',
    ' )',
    ' return {}',
    '',
    ' result: Dict[str, List[str]] = {}',
    ' for item in data:',
    ' try:',
    ' if not item.get("is_all_null"):',
    ' continue',
    ' t_name = item.get("table")',
    ' c_name = item.get("column")',
    ' if not t_name or not c_name:',
    ' continue',
    ' result.setdefault(t_name, []).append(c_name)',
    ' except Exception: # noqa: BLE001',
    ' continue',
    '',
    ' if result:',
    ' total_cols = sum(len(v) for v in result.values())',
    ' print(f"[info] domain_term_822bf46bb1 schema domain_term_0edf483077 {total_cols} domain_term_f7b2a6ee68【domain_term_0141116169】domain_term_77a49f2c38。")',
    ' return result',
    '',
    '',
    'def load_profiles(profiling_dir: Path) -> Dict[str, dict]:',
    ' """domain_term_7792a80e9f profile_* domain_term_49deaf7da2，domain_term_fb2ea9e2df table_name domain_term_ba4fa8969d。"""',
    ' profiles: Dict[str, dict] = {}',
    ' if not profiling_dir.exists():',
    ' print(f"[error] domain_term_085cc3ed60: {profiling_dir}")',
    ' return profiles',
    '',
    ' for f_path in sorted(profiling_dir.glob("profile_*.json")):',
    ' data = _load_json(f_path)',
    ' if not data:',
    ' continue',
    ' t_name = data.get("table_name")',
    ' if not t_name:',
    ' print(f"[warn] domain_term_3ee90ec982 table_name: {f_path}")',
    ' continue',
    ' profiles[t_name] = data',
    ' print(f"[info] domain_term_b19bae5d13 {len(profiles)} domain_term_f7b2a6ee68 profile_* domain_term_49deaf7da2。")',
    ' return profiles',
    '',
    '',
    'def merge_schema_with_llm(',
    ' schema_path: Path = SCHEMA_FILE,',
    ' profiling_dir: Path = PROFILING_DIR,',
    ' output_path: Path = OUTPUT_FILE,',
    ') -> None:',
    ' schema = _load_json(schema_path)',
    ' if not schema:',
    ' print("[error] domain_term_346677626f schema.json，domain_term_2eee5759c3。")',
    ' return',
    '',
    ' profiles = load_profiles(profiling_dir)',
    ' if not profiles:',
    ' print("[error] domain_term_5f1c7dfa0e profile_* domain_term_49deaf7da2，domain_term_2eee5759c3。")',
    ' return',
    '',
    ' # domain_term_17c38184b7（domain_term_16593aa84d check_column_miss_empty.py domain_term_e040700d43）',
    ' all_null_cols_map = _load_all_null_columns()',
    '',
    ' table_missing_profiles: List[str] = []',
    ' column_miss: List[str] = []',
    '',
    ' for table in schema:',
    ' t_name = table.get("table_name")',
    ' if not t_name:',
    ' continue',
    ' profile = profiles.get(t_name)',
    ' if not profile:',
    ' table_missing_profiles.append(t_name)',
    ' continue',
    '',
    ' # domain_term_e12cac0842，domain_term_81fc1c7427 columns domain_term_d5b8c63a3a',
    ' if t_name in all_null_cols_map and table.get("columns"):',
    ' to_drop = set(all_null_cols_map[t_name])',
    ' old_cols = table.get("columns") or []',
    ' new_cols: List[dict] = []',
    ' for col in old_cols:',
    ' c_name = col.get("col")',
    ' if c_name and c_name in to_drop:',
    ' # domain_term_e90cf30fef',
    ' continue',
    ' new_cols.append(col)',
    ' if len(new_cols) != len(old_cols):',
    ' table["columns"] = new_cols',
    '',
    ' # domain_term_d0102a7431 LLM domain_term_412f54dc38',
    ' t_short = profile.get("llm_table_short_description")',
    ' t_long = profile.get("llm_table_long_description")',
    ' if t_short:',
    ' table["table_description_llm_short"] = t_short',
    ' # domain_term_9fb728c60e',
    ' if not table.get("table_description"):',
    ' table["table_description"] = t_short',
    ' if t_long:',
    ' table["table_description_llm_long"] = t_long',
    '',
    ' # domain_term_ead3492911 LLM domain_term_412f54dc38',
    ' col_map = {',
    ' c.get("column_name"): c for c in profile.get("columns_profile", []) or []',
    ' }',
    ' for col in table.get("columns", []) or []:',
    ' c_name = col.get("col")',
    ' if not c_name:',
    ' continue',
    ' p_col = col_map.get(c_name)',
    ' if not p_col:',
    ' column_miss.append(f"{t_name}.{c_name}")',
    ' continue',
    ' c_short = p_col.get("llm_short_description")',
    ' c_long = p_col.get("llm_long_description")',
    ' if c_short:',
    ' col["llm_short_description"] = c_short',
    ' if not col.get("description"):',
    ' col["description"] = c_short',
    ' if c_long:',
    ' col["llm_long_description"] = c_long',
    '',
    ' with output_path.open("w", encoding="utf-8") as f:',
    ' json.dump(schema, f, ensure_ascii=False, indent=2)',
    '',
    ' print(f"[done] domain_term_0418d9c990(schema_all): {output_path}")',
    '',
    ' # domain_term_ce4e52349e run/agent/schema.json，domain_term_7f2c11c795 agent domain_term_0e2d3a3c09',
    ' try:',
    ' RUN_AGENT_SCHEMA_FILE.parent.mkdir(parents=True, exist_ok=True)',
    ' with RUN_AGENT_SCHEMA_FILE.open("w", encoding="utf-8") as f:',
    ' json.dump(schema, f, ensure_ascii=False, indent=2)',
    ' print(f"[done] domain_term_a8fe579a1a schema: {RUN_AGENT_SCHEMA_FILE}")',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"[warn] domain_term_f6b38b538f schema domain_term_3e3c8068bb {RUN_AGENT_SCHEMA_FILE}: {e}")',
    ' if table_missing_profiles:',
    ' print(f"[warn] domain_term_ad57482b31 profile domain_term_49deaf7da2: {len(table_missing_profiles)}")',
    ' for name in table_missing_profiles:',
    ' print(f" - {name}")',
    ' if column_miss:',
    ' print(f"[warn] domain_term_dc568e18f3 profile domain_term_a79a57dbb4: {len(column_miss)} domain_term_bce2ef6151")',
    ' for name in column_miss[:20]:',
    ' print(f" - {name}")',
    ' if len(column_miss) > 20:',
    ' print(f" ... domain_term_12057ae8a8 {len(column_miss) - 20} domain_term_3daa89e2dc")',
    '',
    '',
    'if __name__ == "__main__":',
    ' parser = argparse.ArgumentParser(',
    ' description="domain_term_4170cd5063 profiling_output_merged domain_term_7589bc677d LLM domain_term_056ef0cfdd schema.json，domain_term_4aa2306395 schema_llm_merged.json",',
    ' )',
    ' parser.add_argument(',
    ' "--schema",',
    ' type=Path,',
    ' default=SCHEMA_FILE,',
    ' help="domain_term_a55afe4b5f schema.json domain_term_9132e087f1",',
    ' )',
    ' parser.add_argument(',
    ' "--profiling-dir",',
    ' type=Path,',
    ' default=PROFILING_DIR,',
    ' help="profiling_output_merged domain_term_d9dea994c9",',
    ' )',
    ' parser.add_argument(',
    ' "--output",',
    ' type=Path,',
    ' default=OUTPUT_FILE,',
    ' help="domain_term_7796b92e99 schema_llm_merged.json domain_term_9132e087f1",',
    ' )',
    ' args = parser.parse_args()',
    ' merge_schema_with_llm(',
    ' schema_path=args.schema,',
    ' profiling_dir=args.profiling_dir,',
    ' output_path=args.output,',
    ' )',
    '',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
