# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `1.knowledge_base/1.1_schema_completion_knowledge_base/merge_joins_to_profiles.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    'import json',
    'import os',
    'import glob',
    'from tqdm import tqdm',
    'from collections import defaultdict',
    '',
    '# --- 1. domain_term_d7d7ce790b ---',
    '',
    "PROFILING_DIR = 'profiling_output_per_table' # domain_term_46ae558722",
    "JOIN_CANDIDATES_FILE = 'join_candidates_verified.json' # domain_term_0c1a9d4a35",
    "OUTPUT_DIR = 'profiling_output_merged' # 【domain_term_7b8a6bebd3】domain_term_8c256d471d",
    '',
    '# --- 2. domain_term_152e14c461 ---',
    '',
    'def merge_join_info_to_profiles():',
    ' """',
    ' domain_term_4170cd5063 join_candidates_verified.json domain_term_b2fd812aff，',
    ' domain_term_0159d30c98。',
    ' """',
    '',
    ' # --- domain_term_d13bfa13ca 1: domain_term_896a935f53 ---',
    ' try:',
    " with open(JOIN_CANDIDATES_FILE, 'r', encoding='utf-8') as f:",
    ' join_candidates = json.load(f)',
    ' except FileNotFoundError:',
    ' print(f"!! domain_term_b859c7be75：domain_term_df5ccaf092 {JOIN_CANDIDATES_FILE}。")',
    ' print("domain_term_fa303a7e8f \'analyze_joins.py\' domain_term_7fbccbeb8a。")',
    ' return',
    ' except Exception as e:',
    ' print(f"!! domain_term_b859c7be75：domain_term_3363f3729b {JOIN_CANDIDATES_FILE} domain_term_3e3c8068bb: {e}")',
    ' return',
    '',
    ' print(f"domain_term_b19bae5d13 {len(join_candidates)} domain_term_edd487a003。")',
    '',
    ' # --- domain_term_d13bfa13ca 2: domain_term_cbb955bc4d ---',
    ' join_map = defaultdict(list)',
    '',
    ' for cand in join_candidates:',
    ' col_a = cand["column_A"]',
    ' col_b = cand["column_B"]',
    '',
    ' # domain_term_b7a385ec00 A domain_term_e970c210a6（domain_term_9c7565ba38 B）',
    ' join_map[col_a].append({',
    ' "link_column": col_b,',
    ' "jaccard_similarity": cand["jaccard_similarity"],',
    ' "cardinality_A": cand["cardinality_A"],',
    ' "cardinality_B": cand["cardinality_B"],',
    ' "verified_by_db_join": cand["verified_by_db_join"]',
    ' })',
    '',
    ' # domain_term_b7a385ec00 B domain_term_e970c210a6（domain_term_9c7565ba38 A）',
    ' join_map[col_b].append({',
    ' "link_column": col_a,',
    ' "jaccard_similarity": cand["jaccard_similarity"],',
    ' "cardinality_A": cand["cardinality_B"], # domain_term_f08b55c42c A/B domain_term_ecd89c0159',
    ' "cardinality_B": cand["cardinality_A"], # domain_term_f08b55c42c A/B domain_term_ecd89c0159',
    ' "verified_by_db_join": cand["verified_by_db_join"]',
    ' })',
    '',
    ' print(f"domain_term_2061e6b0d1 {len(join_map)} domain_term_b66ea6f4dc。")',
    '',
    ' # --- domain_term_d13bfa13ca 3: domain_term_22a3dc3057、domain_term_03c118e8a1 ---',
    '',
    ' # 【domain_term_7b8a6bebd3】domain_term_87bd40eb5e',
    ' os.makedirs(OUTPUT_DIR, exist_ok=True)',
    ' print(f"domain_term_a350a02a4a: {os.path.abspath(OUTPUT_DIR)}")',
    '',
    ' json_files = glob.glob(os.path.join(PROFILING_DIR, "*.json"))',
    '',
    ' if not json_files:',
    ' print(f"!! domain_term_b859c7be75：domain_term_686b703f41 \'{PROFILING_DIR}\' domain_term_623cad2a0c。")',
    ' return',
    '',
    ' print(f"domain_term_62e5156191 {len(json_files)} domain_term_8c46ea618b...")',
    '',
    ' for f_path in tqdm(json_files, desc="domain_term_ffe98e068c"):',
    ' try:',
    ' # domain_term_747145342a',
    " with open(f_path, 'r', encoding='utf-8') as f:",
    ' table_profile = json.load(f)',
    '',
    ' table_name = table_profile.get("table_name")',
    ' if not table_name:',
    ' continue',
    '',
    ' # domain_term_3d23bfbb9e',
    ' for col_profile in table_profile.get("columns_profile", []):',
    ' col_name = col_profile.get("column_name")',
    ' full_name = f"{table_name}.{col_name}"',
    '',
    ' # (domain_term_53e32830a5) domain_term_4aa59b70ab "link_column" domain_term_5a8c893cd4',
    ' if "link_column" in col_profile:',
    ' del col_profile["link_column"]',
    '',
    ' # domain_term_c736b5bb61',
    ' if full_name in join_map:',
    ' # domain_term_94191ce210“potential_links”domain_term_d46f82fdf0',
    ' sorted_links = sorted(join_map[full_name], key=lambda x: x["jaccard_similarity"], reverse=True)',
    ' col_profile["potential_links"] = sorted_links # domain_term_33a15e1afb',
    '',
    ' # domain_term_4f3a92ee82，domain_term_c2c21671d3 MinHash',
    ' if "minhash_signature" in col_profile:',
    ' del col_profile["minhash_signature"]',
    '',
    ' # 5. 【domain_term_7b8a6bebd3】domain_term_9e93bdccb2 *domain_term_7b8a6bebd3* domain_term_49deaf7da2',
    ' # domain_term_66b99f617c',
    ' original_filename = os.path.basename(f_path)',
    ' # domain_term_76f2abc348',
    ' output_filename = os.path.join(OUTPUT_DIR, original_filename)',
    '',
    " with open(output_filename, 'w', encoding='utf-8') as f:",
    ' json.dump(table_profile, f, ensure_ascii=False, indent=4)',
    '',
    ' except Exception as e:',
    ' print(f"domain_term_5521e368d8：domain_term_13e5977e4b {f_path} domain_term_3e3c8068bb: {e}")',
    '',
    ' print("="*50)',
    ' print("domain_term_c89473aa2c！")',
    ' print(f"\'{OUTPUT_DIR}\' domain_term_4aee36e519 JSON domain_term_cb352f531b。")',
    ' print(f"domain_term_e78afeb589 \'{PROFILING_DIR}\' domain_term_2ff9c72471。")',
    ' print("="*50)',
    '',
    'if __name__ == "__main__":',
    ' merge_join_info_to_profiles()',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
