# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `1.knowledge_base/1.1_schema_completion_knowledge_base/schema_llm_pipeline.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    'import json',
    'import time',
    'from collections import defaultdict',
    'from pathlib import Path',
    'from typing import Any, Dict, List, Optional, Tuple',
    '',
    'import mysql.connector',
    'from tqdm import tqdm',
    'from openai import OpenAI',
    '',
    'from config import (',
    ' BASE_DIR,',
    ' GEMINI_BASE_URL,',
    ' GEMINI_MODEL,',
    ' GEMINI_API_KEY_LIST,',
    ' GEMINI_API_KEY,',
    ' DB_HOST,',
    ' DB_PORT,',
    ' DB_USER,',
    ' DB_PASSWORD,',
    ' DB_DATABASE,',
    ' ADDED_KNOWLEDGE_LIST_PATH,',
    ')',
    '',
    'DATA_DIR: Path = BASE_DIR / "data"',
    'PROFILING_DIR: Path = DATA_DIR / "profiling_output_merged"',
    'SCHEMA_FILE: Path = DATA_DIR / "schema.json"',
    'TASK_FILE: Path = DATA_DIR / "final_dataset.json"',
    'COMMON_KNOWLEDGE_FILE: Path = DATA_DIR / "common_knowledge.md"',
    'KNOWLEDGE_ADD_FILE: Path = ADDED_KNOWLEDGE_LIST_PATH',
    '',
    '',
    'GEMINI_KEYS: List[str] = [k for k in GEMINI_API_KEY_LIST if k] or (',
    ' [GEMINI_API_KEY] if GEMINI_API_KEY else []',
    ')',
    'CURRENT_GEMINI_KEY_INDEX: int = 0',
    '',
    '',
    'DB_CONFIG: Dict[str, Any] = {',
    ' "host": DB_HOST,',
    ' "port": DB_PORT,',
    ' "user": DB_USER,',
    ' "password": DB_PASSWORD,',
    ' "database": DB_DATABASE,',
    '}',
    '',
    '',
    'def _extract_message_text(resp: Any) -> str:',
    ' try:',
    ' choice = resp.choices[0]',
    ' except Exception:',
    ' return ""',
    ' msg = getattr(choice, "message", None)',
    ' if msg is not None:',
    ' txt = getattr(msg, "content", None)',
    ' if isinstance(txt, str):',
    ' return txt',
    ' if isinstance(txt, list):',
    ' parts: List[str] = []',
    ' for p in txt:',
    ' if isinstance(p, dict) and isinstance(p.get("text"), str):',
    ' parts.append(p["text"])',
    ' else:',
    ' t = getattr(p, "text", None)',
    ' if isinstance(t, str):',
    ' parts.append(t)',
    ' return "".join(parts).strip()',
    ' return txt or ""',
    ' txt = getattr(choice, "text", None)',
    ' return txt or ""',
    '',
    '',
    'def _chat_complete_gemini(',
    ' messages: List[Dict[str, str]],',
    ' model: Optional[str] = None,',
    ' max_attempts: int = 6,',
    ' json_mode: bool = True,',
    ') -> str:',
    ' if not GEMINI_KEYS:',
    ' raise RuntimeError("GEMINI_API_KEY_LIST / GEMINI_API_KEY domain_term_63595e95b7")',
    '',
    ' global CURRENT_GEMINI_KEY_INDEX',
    ' use_model = model or GEMINI_MODEL',
    ' last_error: Optional[Exception] = None',
    '',
    ' for attempt in range(1, max_attempts + 1):',
    ' key_index = CURRENT_GEMINI_KEY_INDEX % len(GEMINI_KEYS)',
    ' key = GEMINI_KEYS[key_index]',
    ' print(',
    ' f" ... domain_term_b1fb011bbf Gemini: model={use_model}, key #{key_index + 1}, "',
    ' f"domain_term_31d1e44656 {attempt}/{max_attempts}"',
    ' )',
    ' start = time.time()',
    ' try:',
    ' client = OpenAI(api_key=key, base_url=GEMINI_BASE_URL)',
    ' kwargs: Dict[str, Any] = {',
    ' "model": use_model,',
    ' "messages": messages,',
    ' "temperature": 1,',
    '',
    ' }',
    ' if json_mode:',
    ' kwargs["response_format"] = {"type": "json_object"}',
    ' resp = client.chat.completions.create(**kwargs)',
    ' text = _extract_message_text(resp) or ""',
    ' cost = time.time() - start',
    ' print(f" ... domain_term_620d86831b，domain_term_a9704e1997 {cost:.2f}s")',
    ' if not text.strip():',
    ' raise RuntimeError("domain_term_a335366316")',
    ' return text',
    ' except Exception as e: # noqa: BLE001',
    ' last_error = e',
    ' msg = str(e)',
    ' print(f" !!! Gemini domain_term_ae19471a31: {e}")',
    ' if ("insufficient_user_quota" in msg) or ("domain_term_4358ab83e8" in msg):',
    ' if len(GEMINI_KEYS) > 1:',
    ' CURRENT_GEMINI_KEY_INDEX = (key_index + 1) % len(GEMINI_KEYS)',
    ' print(" !!! domain_term_25e74dceac Key domain_term_a61b66ab7d，domain_term_8d95e79477 Key domain_term_31f39d3fee...")',
    ' else:',
    ' print(" !!! domain_term_de8976bf9e 1 domain_term_f7b2a6ee68 Gemini Key，domain_term_2ebf8453bc Key")',
    ' time.sleep(1.0)',
    '',
    ' raise RuntimeError(f"Gemini domain_term_118ccc786a: {last_error}")',
    '',
    '',
    'def _call_llm_json(system_prompt: str, user_prompt: str) -> Dict[str, Any]:',
    ' messages = [',
    ' {"role": "system", "content": system_prompt},',
    ' {"role": "user", "content": user_prompt},',
    ' ]',
    ' raw = _chat_complete_gemini(messages, json_mode=True)',
    ' text = raw.strip()',
    ' if text.startswith("```"):',
    ' text = text.strip("`")',
    ' if text.lower().startswith("json"):',
    ' text = text[4:].strip()',
    ' try:',
    ' return json.loads(text)',
    ' except Exception as e: # noqa: BLE001',
    ' raise RuntimeError(f"domain_term_af57b02c34 LLM JSON domain_term_3e3c8068bb: {e}; domain_term_93cfca64c3 200 domain_term_2618f37326: {text[:200]}")',
    '',
    '',
    'def load_sme_metadata(schema_file: Path) -> Tuple[Dict[str, str], Dict[str, List[str]]]:',
    ' try:',
    ' with schema_file.open("r", encoding="utf-8") as f:',
    ' schema = json.load(f)',
    ' sme_meta: Dict[str, str] = {}',
    ' table_neighbors: Dict[str, List[str]] = {}',
    ' for table in schema:',
    ' t_name = table.get("table_name")',
    ' if not t_name:',
    ' continue',
    ' neighbors: List[str] = []',
    ' for col in table.get("columns", []):',
    ' c_name = col.get("col")',
    ' if not c_name:',
    ' continue',
    ' full_name = f"{t_name}.{c_name}"',
    ' sme_meta[full_name] = col.get("description", "")',
    ' neighbors.append(c_name)',
    ' table_neighbors[t_name] = neighbors',
    ' return sme_meta, table_neighbors',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_a4bd5678eb schema domain_term_49deaf7da2 {schema_file}: {e}")',
    ' return {}, {}',
    '',
    '',
    'def load_table_descriptions(schema_file: Path) -> Dict[str, str]:',
    ' """domain_term_8ab977960a schema.json domain_term_451e87bf27 SME domain_term_412f54dc38 (table_description)。"""',
    '',
    ' try:',
    ' with schema_file.open("r", encoding="utf-8") as f:',
    ' schema = json.load(f)',
    ' table_desc_map: Dict[str, str] = {}',
    ' for table in schema:',
    ' t_name = table.get("table_name")',
    ' if not t_name:',
    ' continue',
    ' t_desc = (table.get("table_description") or "").strip()',
    ' if t_desc:',
    ' table_desc_map[t_name] = t_desc',
    ' print(f"domain_term_79a9863b2b schema domain_term_3363f3729b {len(table_desc_map)} domain_term_e967ebda97 SME domain_term_412f54dc38。")',
    ' return table_desc_map',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_a2772cd501 schema domain_term_412f54dc38 {schema_file}: {e}")',
    ' return {}',
    '',
    '',
    'def load_common_knowledge(filename: Path) -> str:',
    ' try:',
    ' with filename.open("r", encoding="utf-8") as f:',
    ' return f.read()',
    ' except FileNotFoundError:',
    ' print(f"!! domain_term_5521e368d8：domain_term_10f839bb24 {filename}")',
    ' return "N/A"',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_52abba91d9 {filename}: {e}")',
    ' return "N/A"',
    '',
    '',
    'def load_advanced_knowledge(task_file: Path, add_knowledge_file: Path) -> Dict[str, str]:',
    ' """domain_term_c11dbb197d。',
    '',
    ' 1. domain_term_8ab977960a final_dataset.json domain_term_3363f3729b (sql_id -> table_list) domain_term_aec4f2ac1d knowledge（domain_term_ea33615ec6）。',
    ' 2. domain_term_8ab977960a knowledge_add_clean_list.json domain_term_3363f3729b (sql_id -> domain_term_45b863ef62)。',
    ' 3. domain_term_0cf0f7eeef knowledge domain_term_cd1875ae0b「domain_term_6a954390e3」domain_term_72fa9ecdc4，domain_term_ca65efc94e / domain_term_d0102a7431 Prompt domain_term_0e2d3a3c09。',
    ' """',
    '',
    ' print("--- domain_term_8f73a1638a ---")',
    '',
    ' # 1) domain_term_1fec75151c（domain_term_f896fb3776 table_list domain_term_86562493fa knowledge）',
    ' try:',
    ' with task_file.open("r", encoding="utf-8") as f:',
    ' raw_tasks = json.load(f)',
    ' if not isinstance(raw_tasks, list):',
    ' raw_tasks = [raw_tasks]',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_3363f3729b {task_file} domain_term_3e3c8068bb: {e}")',
    ' return {}',
    '',
    ' table_knowledge_map: defaultdict[str, List[str]] = defaultdict(list)',
    ' sql_id_to_tables: Dict[str, List[str]] = {}',
    '',
    ' for task in raw_tasks:',
    ' sid = task.get("sql_id")',
    ' tables = task.get("table_list", []) or []',
    ' raw_k = (task.get("knowledge") or "").strip()',
    '',
    ' # domain_term_9058a1c2c5 sql_id -> tables domain_term_3f69679473，domain_term_e6ea724d17',
    ' if sid:',
    ' sql_id_to_tables[sid] = tables',
    '',
    ' # domain_term_a6294b3684 knowledge domain_term_03540d74d4「domain_term_338f6517eb」domain_term_c6f162ac7f',
    ' if raw_k and tables:',
    ' for tbl in tables:',
    ' k_entry = f"【domain_term_338f6517eb ({sid})】: {raw_k}"',
    ' if k_entry not in table_knowledge_map[tbl]:',
    ' table_knowledge_map[tbl].append(k_entry)',
    '',
    ' # 2) domain_term_e9652c3dd9（domain_term_45b863ef62），domain_term_e99f9e57da',
    ' if add_knowledge_file.exists():',
    ' try:',
    ' with add_knowledge_file.open("r", encoding="utf-8") as f:',
    ' add_tasks = json.load(f)',
    ' if not isinstance(add_tasks, list):',
    ' add_tasks = [add_tasks]',
    '',
    ' print(f"domain_term_b034a28dba {add_knowledge_file}，domain_term_f896fb3776 {len(add_tasks)} domain_term_84b6d147f7。")',
    '',
    ' for item in add_tasks:',
    ' sid = item.get("sql_id")',
    ' clean_k = (item.get("knowledge") or "").strip()',
    '',
    ' if not sid or not clean_k:',
    ' continue',
    '',
    ' # domain_term_bdf1a7fa18 sql_id domain_term_4dc58bfb08',
    ' target_tables = sql_id_to_tables.get(sid, [])',
    ' if not target_tables:',
    ' print(',
    ' f" [Warn] domain_term_48dcd47aae sql_id={sid}，domain_term_b200d7ad1d table_list，domain_term_31a98593f1。",',
    ' )',
    ' continue',
    '',
    ' # domain_term_ced9a17a57（domain_term_27ec2d53e8，domain_term_4307874407）',
    ' for tbl in target_tables:',
    ' k_entry = f"⚠️【domain_term_db9068bfcb ({sid})】: {clean_k}"',
    ' if k_entry not in table_knowledge_map[tbl]:',
    ' table_knowledge_map[tbl].insert(0, k_entry)',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_dd91b5564f: {e}")',
    ' else:',
    ' print(f"domain_term_ab3656a956：domain_term_df8f26124a {add_knowledge_file}，domain_term_b2c36f82e9。")',
    '',
    ' # 3) domain_term_1354ea4f95，domain_term_e5a877bd3b',
    ' final_map: Dict[str, str] = {}',
    ' for tbl, k_list in table_knowledge_map.items():',
    ' final_map[tbl] = "\\n\\n".join(k_list)',
    '',
    ' print(f"domain_term_940ac7725c：domain_term_c0e8e4843b {len(final_map)} domain_term_47ceb2ef80。")',
    ' return final_map',
    '',
    '',
    'def is_time_column(col_name: str, col_type: Any) -> bool:',
    ' """domain_term_3cd92696b0：domain_term_10c7d013d6/domain_term_c884cb6b41。"""',
    '',
    ' name_lower = (col_name or "").lower()',
    ' if any(x in name_lower for x in ["date", "time", "day", "dt", "ds", "ymd"]):',
    ' return True',
    '',
    ' type_lower = str(col_type or "").lower()',
    ' if ("date" in type_lower) or ("time" in type_lower):',
    ' return True',
    '',
    ' return False',
    '',
    '',
    'def get_deep_stats(conn: mysql.connector.MySQLConnection, table_name: str, col_profile: Dict[str, Any]) -> Optional[Dict[str, Any]]:',
    ' """domain_term_cff810c945。',
    '',
    ' - domain_term_969cd5d6ab：MIN/MAX + COUNT domain_term_5cdf1b377c + COUNT DISTINCT',
    ' - domain_term_de518f732a：domain_term_e32b082b48（domain_term_4c5dfceda4 50 domain_term_3353299ae3）',
    ' """',
    '',
    ' col_name = col_profile.get("column_name")',
    ' if not col_name:',
    ' return None',
    '',
    ' col_type = col_profile.get("type", "")',
    '',
    ' # 1) domain_term_e260f7ab3f',
    ' if is_time_column(col_name, col_type):',
    ' try:',
    ' with conn.cursor() as cursor:',
    ' query = f"""',
    ' SELECT',
    ' MIN(`{col_name}`),',
    ' MAX(`{col_name}`),',
    ' COUNT(`{col_name}`),',
    ' COUNT(DISTINCT `{col_name}`)',
    ' FROM `{table_name}`',
    ' """',
    ' cursor.execute(query)',
    ' row = cursor.fetchone()',
    ' if not row:',
    ' return None',
    ' min_val, max_val, total_count, distinct_count = row',
    ' return {',
    ' "is_time": True,',
    ' "min": str(min_val),',
    ' "max": str(max_val),',
    ' "total_present": int(total_count or 0),',
    ' "distinct_count": int(distinct_count or 0),',
    ' }',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"domain_term_d4a448c467 {table_name}.{col_name}: {e}")',
    ' return None',
    '',
    ' # 2) domain_term_a0c3fbc7ea（domain_term_448e75cfb9）',
    ' cardinality = col_profile.get("cardinality", 1000)',
    ' if cardinality is not None and cardinality < 50 and not is_time_column(col_name, col_type):',
    ' try:',
    ' with conn.cursor() as cursor:',
    ' query = f"SELECT DISTINCT `{col_name}` FROM `{table_name}` LIMIT 50"',
    ' cursor.execute(query)',
    ' values = [str(row[0]) for row in cursor.fetchall()]',
    ' return {',
    ' "is_enum": True,',
    ' "all_values": values,',
    ' }',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"domain_term_28d1714ead {table_name}.{col_name}: {e}")',
    ' return None',
    '',
    ' return None',
    '',
    '',
    'def verify_table_continuity(',
    ' conn: mysql.connector.MySQLConnection,',
    ' table_name: str,',
    ' date_col: str,',
    ' id_col: str,',
    ' check_days: int = 14,',
    ') -> Optional[Dict[str, Any]]:',
    ' """domain_term_f286fe2a56(_df)domain_term_7f980de73f(_di)。',
    '',
    ' domain_term_f26c2b4e8a：',
    ' - domain_term_711bc704c7（domain_term_fb2ea9e2df date_col domain_term_a4c38f3ce2），domain_term_d0c73fec9e date_count',
    ' - domain_term_5b3f9cf65e ID',
    ' - domain_term_374dae334b ID domain_term_cf30e9a086 date_count domain_term_58d446b20c distinct domain_term_f02ba3a546',
    ' - domain_term_d5d3661709 = freq / date_count，domain_term_b08100c57a',
    ' """',
    '',
    ' cursor = conn.cursor()',
    ' try:',
    ' # 1) domain_term_5368b6fba9 check_days domain_term_c11d116505',
    ' query_dates = (',
    ' f"SELECT DISTINCT `{date_col}` FROM `{table_name}` "',
    ' f"ORDER BY `{date_col}` DESC LIMIT {int(check_days)}"',
    ' )',
    ' cursor.execute(query_dates)',
    ' recent_dates = [row[0] for row in cursor.fetchall()]',
    ' if len(recent_dates) < 3:',
    ' return {',
    ' "type": "UNKNOWN",',
    ' "reason": "domain_term_a41a965a7c，domain_term_b9ef74ca6d",',
    ' }',
    '',
    ' latest_date = recent_dates[0]',
    ' earliest_date = recent_dates[-1]',
    ' date_count = len(recent_dates)',
    '',
    ' # 2) domain_term_3460fa15a6：domain_term_7abce56703 ID（domain_term_b817ddaffb LIMIT 10 domain_term_9b3589f364）',
    ' query_sample = (',
    ' f"SELECT `{id_col}` FROM `{table_name}` "',
    ' f"WHERE `{date_col}` = \'{latest_date}\' LIMIT 10"',
    ' )',
    ' cursor.execute(query_sample)',
    ' sample_ids = [str(row[0]) for row in cursor.fetchall()]',
    ' if not sample_ids:',
    ' return {',
    ' "type": "UNKNOWN",',
    ' "reason": "domain_term_075ae548d7",',
    ' }',
    '',
    ' # 3) domain_term_374dae334b ID domain_term_cf30e9a086 date_count domain_term_a8d125f797',
    ' ids_formatted = ",".join([f"\'{sid}\'" for sid in sample_ids])',
    ' check_query = f"""',
    ' SELECT `{id_col}`, COUNT(DISTINCT `{date_col}`) AS freq',
    ' FROM `{table_name}`',
    ' WHERE `{id_col}` IN ({ids_formatted})',
    " AND `{date_col}` >= '{earliest_date}'",
    ' GROUP BY `{id_col}`',
    ' """',
    ' cursor.execute(check_query)',
    ' results = cursor.fetchall()',
    '',
    ' total_coverage = 0.0',
    ' valid_samples = 0',
    ' for _id_val, freq in results:',
    ' try:',
    ' freq_int = int(freq or 0)',
    ' except Exception: # noqa: BLE001',
    ' continue',
    ' if date_count <= 0:',
    ' continue',
    ' coverage = freq_int / float(date_count)',
    ' total_coverage += coverage',
    ' valid_samples += 1',
    '',
    ' avg_coverage = total_coverage / valid_samples if valid_samples > 0 else 0.0',
    '',
    ' inferred_type = "UNKNOWN"',
    ' confidence = "low"',
    ' if avg_coverage > 0.9:',
    ' inferred_type = "SNAPSHOT_FULL (_df)"',
    ' confidence = "high"',
    ' elif avg_coverage > 0.7:',
    ' inferred_type = "SNAPSHOT_LIKELY (_df)"',
    ' confidence = "medium"',
    ' else:',
    ' inferred_type = "INCREMENT_LOG (_di)"',
    ' confidence = "high"',
    '',
    ' return {',
    ' "type": inferred_type,',
    ' "avg_coverage": f"{avg_coverage:.1%}",',
    ' "sample_size": valid_samples,',
    ' "check_period_days": date_count,',
    ' "id_col_used": id_col,',
    ' "date_col_used": date_col,',
    ' "confidence": confidence,',
    ' }',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"domain_term_31231e79d7 {table_name}: {e}")',
    ' return None',
    ' finally:',
    ' try:',
    ' cursor.close()',
    ' except Exception: # noqa: BLE001',
    ' pass',
    '',
    '',
    'def _infer_date_and_id_columns(table_profile: Dict[str, Any]) -> Tuple[Optional[str], Optional[str]]:',
    ' """domain_term_f1ce311a08 deep_stats domain_term_e4b5a7a2c9 date_col domain_term_9a3eb34097 id_col。"""',
    '',
    ' cols = table_profile.get("columns_profile", []) or []',
    ' date_col: Optional[str] = None',
    ' id_col: Optional[str] = None',
    '',
    ' # 1) domain_term_fad5f75864：domain_term_efacdd188d deep_stats.is_time，domain_term_9e2d00da94',
    ' candidate_dates: List[str] = []',
    ' for col in cols:',
    ' name = col.get("column_name") or ""',
    ' ds = col.get("deep_stats") or {}',
    ' if ds.get("is_time") or is_time_column(name, col.get("type")):',
    ' candidate_dates.append(name)',
    '',
    ' if candidate_dates:',
    ' # domain_term_c883a2b3c5',
    ' def _date_priority(n: str) -> int:',
    ' n = n.lower()',
    ' if "dtstatdate" in n:',
    ' return 0',
    ' if n in ("dt", "ds"):',
    ' return 1',
    ' if "dt" in n or "ds" in n:',
    ' return 2',
    ' if "date" in n or "day" in n:',
    ' return 3',
    ' if "time" in n:',
    ' return 4',
    ' return 5',
    '',
    ' candidate_dates.sort(key=_date_priority)',
    ' date_col = candidate_dates[0]',
    '',
    ' # 2) domain_term_4ab7348381 ID domain_term_ad3ee64830：domain_term_9d9a29f2eb',
    ' for col in cols:',
    ' name = (col.get("column_name") or "").lower()',
    ' if any(k in name for k in ["roleid", "role_id", "userid", "user_id", "playerid", "player_id", "uid"]):',
    ' id_col = col.get("column_name")',
    ' break',
    ' if id_col is None:',
    ' for col in cols:',
    ' name = (col.get("column_name") or "").lower()',
    ' if name.endswith("id") or name == "id":',
    ' id_col = col.get("column_name")',
    ' break',
    '',
    ' return date_col, id_col',
    '',
    '',
    'def enrich_profiles_with_db() -> None:',
    ' """domain_term_c1f509ec91，domain_term_b7a385ec00 profiling_output_merged domain_term_e66319c2d2 deep_stats domain_term_2da40f4073。',
    '',
    ' - domain_term_306dd2b4ff deep_stats domain_term_0377e12bdf，domain_term_c647ec1342。',
    ' - domain_term_cd43d5ade4，domain_term_bd99000814，domain_term_e4460cd896 LLM domain_term_024bbc64cb。',
    ' """',
    '',
    ' print("=== domain_term_dae828fe4f 0 domain_term_5274e916ac：domain_term_1a4d158ac8（deep_stats） ===")',
    '',
    ' if not PROFILING_DIR.exists():',
    ' print(f"!! domain_term_b859c7be75：domain_term_085cc3ed60: {PROFILING_DIR}")',
    ' return',
    '',
    ' json_files = sorted(PROFILING_DIR.glob("*.json"))',
    ' if not json_files:',
    ' print(f"!! domain_term_ab3656a956：domain_term_686b703f41 \'{PROFILING_DIR}\' domain_term_623cad2a0c，domain_term_31a98593f1 deep_stats domain_term_1dd014a84e。")',
    ' return',
    '',
    ' try:',
    ' conn = mysql.connector.connect(**DB_CONFIG)',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_75fa7eb79a，domain_term_31a98593f1 deep_stats domain_term_1dd014a84e: {e}")',
    ' return',
    '',
    ' enhanced_cols = 0',
    ' try:',
    ' for f_path in tqdm(json_files, desc="deep_stats domain_term_1dd014a84e (domain_term_6a954390e3)"):',
    ' try:',
    ' with f_path.open("r", encoding="utf-8") as f:',
    ' table_profile = json.load(f)',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_4389f43950 {f_path}: {e}")',
    ' continue',
    '',
    ' table_name = table_profile.get("table_name")',
    ' if not table_name:',
    ' continue',
    '',
    ' is_modified = False',
    ' for col in table_profile.get("columns_profile", []):',
    ' # domain_term_6e30e30629 deep_stats，domain_term_1575b74375，domain_term_729cb08868 DB',
    ' if "deep_stats" in col:',
    ' continue',
    '',
    ' stats = get_deep_stats(conn, table_name, col)',
    ' if stats:',
    ' col["deep_stats"] = stats',
    ' is_modified = True',
    ' enhanced_cols += 1',
    '',
    ' # domain_term_41705b6a70（domain_term_8999f2d0bd verification_stats domain_term_4baa853150）',
    ' if "verification_stats" not in table_profile:',
    ' date_col, id_col = _infer_date_and_id_columns(table_profile)',
    ' if date_col and id_col:',
    ' vstats = verify_table_continuity(conn, table_name, date_col, id_col)',
    ' if vstats:',
    ' table_profile["verification_stats"] = vstats',
    ' is_modified = True',
    '',
    ' if is_modified:',
    ' try:',
    ' with f_path.open("w", encoding="utf-8") as f:',
    ' json.dump(table_profile, f, ensure_ascii=False, indent=4)',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_cf46b16401 {f_path}: {e}")',
    ' finally:',
    ' try:',
    ' conn.close()',
    ' except Exception: # noqa: BLE001',
    ' pass',
    '',
    ' print(f"=== deep_stats domain_term_c98698adba，domain_term_0dae9024ff {enhanced_cols} domain_term_bc92ff5e14 ===")',
    '',
    '',
    'def build_mechanical_description(col_profile: Dict[str, Any], total_records: Optional[int]) -> str:',
    ' desc: List[str] = []',
    ' col_name = col_profile.get("column_name")',
    '',
    ' if col_profile.get("null_values") is not None and total_records is not None:',
    ' null_pct = 0.0',
    ' if total_records > 0:',
    ' null_pct = round(',
    ' (col_profile["null_values"] / total_records) * 100,',
    ' 1,',
    ' )',
    ' desc.append(',
    ' f"domain_term_77a49f2c38 \'{col_name}\' domain_term_686b703f41 {total_records} domain_term_886a5011e3 "',
    ' f"{col_profile[\'null_values\']} domain_term_f7b2a6ee68 NULL domain_term_321b955840 ({null_pct}%)。",',
    ' )',
    '',
    ' if col_profile.get("cardinality") is not None:',
    ' desc.append(f"domain_term_a30650cf41 {col_profile[\'cardinality\']} domain_term_992d356fca。")',
    '',
    ' shape = col_profile.get("shape", {}) or {}',
    ' if (',
    ' shape.get("min_length") is not None',
    ' and shape.get("max_length") is not None',
    ' ):',
    ' if shape["min_length"] == shape["max_length"]:',
    ' desc.append(f"domain_term_414302639a {shape[\'min_length\']}。")',
    ' else:',
    ' avg_len = shape.get("avg_length", 0) or 0',
    ' desc.append(',
    ' f"domain_term_2f9d37d495 {shape[\'min_length\']} domain_term_792bbe6e08 {shape[\'max_length\']} "',
    ' f"(domain_term_d1454ec022 {avg_len:.1f})。",',
    ' )',
    '',
    ' if (',
    ' shape.get("min_value") not in [None, "None"]',
    ' and shape.get("max_value") not in [None, "None"]',
    ' ):',
    ' desc.append(',
    ' f"domain_term_db15f89a5d \'{shape[\'min_value\']}\' domain_term_792bbe6e08 \'{shape[\'max_value\']}\'。",',
    ' )',
    '',
    ' charset = shape.get("charset_analysis") or {}',
    ' if charset and charset.get("count", 0) > 0:',
    ' if charset.get("all_numeric"):',
    ' desc.append("domain_term_722b335126。")',
    ' elif charset.get("json_like_pct", 0) > 50:',
    ' desc.append(f"domain_term_fbd5b75066 {charset[\'json_like_pct\']}% domain_term_183e9a00a7 JSON。")',
    ' elif charset.get("other_special_char_pct", 0) > 10:',
    ' desc.append("domain_term_d7cdcba33d。")',
    '',
    ' top_k = col_profile.get("top_k_values")',
    ' if top_k:',
    ' top_k_list = [',
    ' f"\'{val[0]}\' (domain_term_a0fadbb048 {val[1]} domain_term_5e5b8169ee)" for val in top_k[:5]',
    ' ]',
    ' desc.append(',
    ' f"domain_term_65c315dd92: {\', \'.join(top_k_list)}。",',
    ' )',
    '',
    ' return " ".join(desc)',
    '',
    '',
    'def build_field_llm_prompt(',
    ' table_profile: Dict[str, Any],',
    ' col_profile: Dict[str, Any],',
    ' sme_description: str,',
    ' neighbors: List[str],',
    ' common_knowledge: str,',
    ' task_knowledge: str,',
    ') -> tuple[str, str]:',
    ' table_name = table_profile.get("table_name")',
    ' col_name = col_profile.get("column_name")',
    '',
    ' mechanical_desc = build_mechanical_description(',
    ' col_profile,',
    ' table_profile.get("total_records"),',
    ' )',
    ' context_lines = [',
    ' f"domain_term_584c112b78 (Table): `{table_name}`",',
    ' f"domain_term_def4ee41bc (Table Description): \\"{table_profile.get(\'table_description\', \'N/A\')}\\"",',
    ' f"domain_term_074a5eecfc (Column): `{col_name}`",',
    ' f"SME domain_term_0c03eba6b1 (SME Description): \\"{sme_description}\\"",',
    ' f"domain_term_36f945ef4c (Neighbors): {\', \'.join(neighbors[:10])}{\'...\' if len(neighbors) > 10 else \'\'}",',
    ' ]',
    ' context = "\\n".join(context_lines)',
    '',
    ' link_info_lines: List[str] = []',
    ' potential_links = col_profile.get("potential_links")',
    ' if potential_links and isinstance(potential_links, list):',
    ' link_info_lines.append("\\n**domain_term_92cedd179d**: domain_term_7f914ec041：")',
    ' for link in potential_links[:3]:',
    ' try:',
    ' jacc = float(link.get("jaccard_similarity", 0) or 0) * 100',
    ' except Exception: # noqa: BLE001',
    ' jacc = 0.0',
    ' link_info_lines.append(',
    ' f" - `{link.get(\'link_column\')}` (Jaccard domain_term_087f8c3c44: {jacc:.1f}%)",',
    ' )',
    ' if len(potential_links) > 3:',
    ' link_info_lines.append(',
    ' f" ... (domain_term_46870e4b89 {len(potential_links) - 3} domain_term_f7b2a6ee68)",',
    ' )',
    ' link_info = "\\n".join(link_info_lines)',
    '',
    ' # deep_stats domain_term_95b501cd48',
    ' deep_stats = col_profile.get("deep_stats") or {}',
    ' deep_desc = ""',
    ' special_instruction = ""',
    '',
    ' if deep_stats.get("is_enum"):',
    ' all_vals = deep_stats.get("all_values") or []',
    ' all_vals_str = ", ".join(str(v) for v in all_vals)',
    ' deep_desc = (',
    ' f"【domain_term_e32b082b48】domain_term_7e6cfc8ee1，domain_term_c9fb69cea0: [{all_vals_str}]"',
    ' )',
    ' special_instruction = """',
    '[domain_term_da19be609a - domain_term_e47246f84d]',
    'domain_term_0375a10fb8。domain_term_40c13e2c8d [domain_term_1dda51f9e3] domain_term_47342624d4**domain_term_2b7bbceafa**domain_term_ad33f2e00d。',
    'domain_term_86a44956f2：`domain_term_321b955840` = domain_term_104d11e42e。',
    'domain_term_79638e7026，domain_term_0b24f83997，domain_term_32464c8544(domain_term_4ab7348381)。',
    '"""',
    ' elif deep_stats.get("is_time"):',
    ' min_val = deep_stats.get("min")',
    ' max_val = deep_stats.get("max")',
    ' total_present = deep_stats.get("total_present")',
    ' distinct_count = deep_stats.get("distinct_count")',
    ' deep_desc = (',
    ' "【domain_term_f5c80cfb72】 "',
    ' f"domain_term_785b52eb97 {min_val} domain_term_792bbe6e08 {max_val}; "',
    ' f"domain_term_5086254ede: {total_present}; "',
    ' f"domain_term_ff5468724c: {distinct_count}"',
    ' )',
    ' special_instruction = """',
    '[domain_term_da19be609a - domain_term_7e26fddcfe]',
    'domain_term_f41d5454ef/domain_term_c884cb6b41，domain_term_696790a40f（domain_term_714946f313）。',
    'domain_term_6605f1334a，domain_term_5066343333“domain_term_6783902498（domain_term_ca8ffc3990/domain_term_d93549676d）”domain_term_31fd0bc3de“domain_term_a6121f0caf（domain_term_d4247a7d1e、domain_term_570df2c0f9）”，domain_term_61316e37e6。',
    '"""',
    '',
    ' system_prompt = f"""',
    '[domain_term_3172b317f9]',
    'domain_term_b7be39bca6。',
    'domain_term_3f531b5ace“SME domain_term_412f54dc38”、“domain_term_0786a268bf”domain_term_9a3eb34097“domain_term_1dda51f9e3”，domain_term_b7a9b7aa28“domain_term_2e0f9da5f9”domain_term_1ef6cc1ff9“domain_term_2689f46941”。',
    '',
    '[domain_term_1dda51f9e3 - domain_term_1a0fdce8f8]',
    '{common_knowledge}',
    '',
    '[domain_term_f6b16c9d22 - domain_term_b7f4670752]',
    'domain_term_941991006b【domain_term_e1504ee9d4】domain_term_5f39f6f47e SQL domain_term_5863174e2e「domain_term_6a954390e3」domain_term_fd66925fa5，domain_term_87838f3cc6**domain_term_055bf36c8e**，domain_term_fec28bb56c**domain_term_c03d626da3**：',
    '1. domain_term_5b6b9753af `⚠️【domain_term_db9068bfcb`，domain_term_41ff82bc80“domain_term_890e87b370”“domain_term_2fe9614f04”“domain_term_ca2b9a71dc”domain_term_eb0884d2fe，domain_term_552badebca**domain_term_4195e3e3c8**，domain_term_7bf651a73a，domain_term_11d25c6dc3。',
    '2. domain_term_5b6b9753af `【domain_term_338f6517eb` domain_term_61910a56ae，domain_term_ca0e65c10c SQL domain_term_7e65e8a43b。domain_term_699f43389f，domain_term_f75e1c067d：“domain_term_518e937212/domain_term_625b392c7b，domain_term_3bf98aaa5e A、B、C domain_term_3d3e17a162，domain_term_b110cc7041。”',
    '3. domain_term_ed77d5b67c，domain_term_18aa782a31，domain_term_1f04586c27“domain_term_db9068bfcb”domain_term_959532f1b7，domain_term_5c8b899efc**domain_term_13a3bf52f3**。',
    '',
    '[domain_term_cbe6334ba3]',
    '- “domain_term_2e0f9da5f9” (llm_short_description):',
    ' domain_term_b70bd154ee**domain_term_3998e47152**、**domain_term_ca29088bab**domain_term_9a3eb34097**domain_term_7e13a8ed2b**。',
    ' **[domain_term_3a40c21b0a 1 (domain_term_42ecb2c427)]：** domain_term_5630b886f9**domain_term_890e87b370**domain_term_9eedf1e79e**domain_term_074a5eecfc (Column Name)** domain_term_9a3eb34097 **[domain_term_1dda51f9e3 - domain_term_1a0fdce8f8]** domain_term_46e0c2112f**domain_term_7dbfd6641c**。',
    ' domain_term_46930b1ccf：domain_term_24a9af6fab SME domain_term_41bbf59fbe“domain_term_b6fed9af83”，domain_term_355d55528f `dtstatdate` domain_term_30f4d7cfe8 `ds`，domain_term_9e05e1b687 `_di` domain_term_30f4d7cfe8 `_df`，domain_term_c43271bb4e[domain_term_1dda51f9e3 - domain_term_1a0fdce8f8]domain_term_3b0fdfda34**domain_term_e5d9c6c8a8**“domain_term_f23de2ec9d”，domain_term_95a4409ecc“domain_term_fb607281c2，domain_term_9d2601c843 YYYYMMDD”。',
    ' domain_term_46930b1ccf：domain_term_4b4517a1e7 `cbitmap`，domain_term_c43271bb4e[domain_term_1dda51f9e3 - domain_term_1a0fdce8f8]domain_term_679e333165“100domain_term_98b824a19c”。',
    '',
    ' **[domain_term_3a40c21b0a 2 (domain_term_9d2601c843)]：** domain_term_24a9af6fab SME domain_term_d7ca1989c1（domain_term_46930b1ccf "domain_term_b6fed9af83", "domain_term_4fea859859", "domain_term_a3359e4c58"），domain_term_5630b886f9**domain_term_890e87b370**domain_term_0e2d3a3c09 [domain_term_0786a268bf] domain_term_30509fc42f（domain_term_71facee776 Top-K domain_term_321b955840、domain_term_8a78e7e6a9）domain_term_910754b168。domain_term_89291361ba [domain_term_1dda51f9e3 - domain_term_159d6b015f] domain_term_0addeca145（domain_term_46930b1ccf String vs Bigint/Int）domain_term_996bd86cb3；domain_term_60a68d982f（domain_term_43fdb1f3c4 BIGINT domain_term_aa66cd7319）domain_term_bfcdfa5f79，domain_term_841c575d1f。',
    '',
    '{special_instruction}',
    '',
    '- “domain_term_2689f46941” (llm_long_description):',
    ' domain_term_c855b53e55“domain_term_2e0f9da5f9”domain_term_25829b81c4，domain_term_8966a194a3“domain_term_0786a268bf”domain_term_056b9acb6b（domain_term_46930b1ccf Top-K domain_term_321b955840、domain_term_0125d86a95）。',
    ' **[domain_term_3a40c21b0a 3 (domain_term_7328deebb5)]：** domain_term_b391474fa9**domain_term_9ac31c687f** [domain_term_0786a268bf] domain_term_00cd1da269 "domain_term_92cedd179d" domain_term_2da40f4073（domain_term_e99f9e57da）。',
    ' **[domain_term_3a40c21b0a 4 (domain_term_afd9251450)]：** domain_term_24a9af6fab [domain_term_1dda51f9e3 - domain_term_159d6b015f] domain_term_cc32666890（domain_term_46930b1ccf `sgamecode`），domain_term_5630b886f9**domain_term_890e87b370**domain_term_5f7cf9919b（domain_term_46930b1ccf“domain_term_1a9722a044”domain_term_0a7d5f4bcd）domain_term_e62237ef97；domain_term_edd08cf999【domain_term_338f6517eb】domain_term_145cda01f2/domain_term_c77a3dc2a2，domain_term_88a7b3c997“domain_term_f6b16c9d22”domain_term_fa1dfd2a62**domain_term_24f63f370b**，domain_term_30ba384296。domain_term_6ee8f3321e，domain_term_ca29af1e4e，[domain_term_1dda51f9e3 - domain_term_159d6b015f] domain_term_477d2895b5。domain_term_be3f031c15 `{table_name}`，domain_term_b2b9a7d564（domain_term_c1bac54645）domain_term_4d6b9640e4，domain_term_b59ce2b216。',
    '',
    '[domain_term_b015409988]',
    'domain_term_a4f286dbf2 JSON domain_term_b6bc15e2cf，domain_term_fd1510b265：',
    '{{',
    ' "llm_short_description": "...",',
    ' "llm_long_description": "..."',
    '}}',
    '"""',
    '',
    ' user_prompt = f"""',
    '[domain_term_1dda51f9e3 - domain_term_159d6b015f]',
    '{task_knowledge if task_knowledge else "N/A"}',
    '',
    '---',
    '[domain_term_0b94744802]',
    '',
    '[domain_term_d9aa9fe0d6]',
    '{context}',
    '',
    '[domain_term_0786a268bf (Profiling Report)]',
    '{mechanical_desc}',
    '{link_info}',
    '',
    '"""',
    '',
    ' if deep_desc:',
    ' user_prompt += f"\\n\\n[domain_term_6decccdb96 (Deep Stats)]\\n{deep_desc}"',
    '',
    ' return system_prompt, user_prompt',
    '',
    '',
    'def build_table_llm_prompt(',
    ' table_profile: Dict[str, Any],',
    ' columns_short_descriptions: List[str],',
    ' common_knowledge: str,',
    ' task_knowledge: str,',
    ') -> tuple[str, str]:',
    ' table_name = table_profile.get("table_name")',
    ' table_desc = table_profile.get("table_description", "N/A")',
    ' columns_block = "\\n".join(columns_short_descriptions) if columns_short_descriptions else "N/A"',
    '',
    ' # domain_term_34534295b1 deep_stats domain_term_2da40f4073',
    ' time_cols_info: List[str] = []',
    ' for col in table_profile.get("columns_profile", []):',
    ' ds = col.get("deep_stats") or {}',
    ' if ds.get("is_time"):',
    ' time_cols_info.append(',
    ' "- `{}.`{}: domain_term_785b52eb97[{} ~ {}], domain_term_5086254ede={}, domain_term_ff5468724c={}".format(',
    ' table_name,',
    ' col.get("column_name"),',
    ' ds.get("min"),',
    ' ds.get("max"),',
    ' ds.get("total_present"),',
    ' ds.get("distinct_count"),',
    ' )',
    ' )',
    ' time_context = "\\n".join(time_cols_info) if time_cols_info else "domain_term_4559e42d76 (deep_stats)"',
    '',
    ' # domain_term_b6b97ac60d Python domain_term_f408ab9f80',
    ' verify_info = table_profile.get("verification_stats") or {}',
    ' inferred_type = verify_info.get("type", "UNKNOWN")',
    ' coverage = verify_info.get("avg_coverage", "N/A")',
    ' check_days = verify_info.get("check_period_days", "N/A")',
    ' confidence = verify_info.get("confidence", "unknown")',
    '',
    ' suffix = ""',
    ' if table_name and isinstance(table_name, str) and "_" in table_name:',
    ' suffix = table_name.split("_")[-1].lower()',
    '',
    ' warning_msg = ""',
    ' if suffix == "df" and "INCREMENT" in inferred_type:',
    ' warning_msg = (',
    ' "[domain_term_99550d60ab：domain_term_c05f6ab1e8]\\n"',
    ' f"domain_term_9404b51641 `_df`（domain_term_04c5a2b955），domain_term_7db546d305 {check_days} domain_term_820c96145c（{coverage}，domain_term_b78c2dc2e2 {confidence}），\\n"',
    ' f"domain_term_5cbd4b8462：{inferred_type}。\\n"',
    ' "domain_term_03b67caa81 SQL domain_term_a34801ad9c，domain_term_d9794f2c02“domain_term_c41ff6f841”。\\n"',
    ' "domain_term_82640ad857、domain_term_1b2dd4ddc2，domain_term_24713e910c。"',
    ' )',
    ' elif suffix == "di" and "SNAPSHOT" in inferred_type:',
    ' warning_msg = (',
    ' "[domain_term_ab3656a956：domain_term_e0da73811d]\\n"',
    ' f"domain_term_9404b51641 `_di`，domain_term_7db546d305 {check_days} domain_term_820c96145c（{coverage}，domain_term_b78c2dc2e2 {confidence}），\\n"',
    ' f"domain_term_040508d81c：{inferred_type}。\\n"',
    ' "domain_term_25bf60ce5f，domain_term_5be14cca25，domain_term_dec171d2dc。"',
    ' )',
    ' elif inferred_type != "UNKNOWN":',
    ' warning_msg = (',
    ' "[domain_term_899bd6abb5]\\n"',
    ' f"domain_term_9e1b149aa9 {check_days} domain_term_faa1bfaa35 {coverage}，domain_term_b325f2eb5d {inferred_type}，"',
    ' f"domain_term_161d3e19f1 `{suffix}` domain_term_95590bcfb6。"',
    ' )',
    ' else:',
    ' warning_msg = (',
    ' "[domain_term_a85ec6517b]\\n"',
    ' "domain_term_0aa8ae648e，domain_term_ce2b6960a3。\\n"',
    ' "domain_term_52fe616cab，domain_term_a4f02bad26。"',
    ' )',
    '',
    ' system_prompt = f"""',
    '[domain_term_3172b317f9]',
    'domain_term_b7be39bca6。',
    'domain_term_215c3f8286SMEdomain_term_412f54dc38、domain_term_d8cd096054，domain_term_b7a385ec00**domain_term_31d24b2c3f**domain_term_572ff3c9b2“domain_term_2e0f9da5f9”domain_term_1ef6cc1ff9“domain_term_2689f46941”。',
    '',
    '[domain_term_1dda51f9e3 - domain_term_1a0fdce8f8]',
    '{common_knowledge}',
    '',
    '[domain_term_f6b16c9d22 - domain_term_b7f4670752]',
    'domain_term_941991006b【domain_term_e1504ee9d4】domain_term_5f39f6f47e SQL domain_term_ceb215d1cf「domain_term_6a954390e3」domain_term_fd66925fa5：',
    '- domain_term_5631fa9c7c `⚠️【domain_term_db9068bfcb` domain_term_d70752726e**domain_term_4195e3e3c8**（domain_term_20ed092eed、domain_term_890e87b370/domain_term_fc03f2dc09），domain_term_4c2f1d622f；',
    '- domain_term_5631fa9c7c `【domain_term_338f6517eb` domain_term_25ee3fe787，domain_term_51616c695a。',
    '',
    'domain_term_9e7f2cd07f Profile domain_term_a34801ad9c：',
    '1. domain_term_e23c549371“domain_term_db9068bfcb”domain_term_46d17c98e7**domain_term_95a5d96872/domain_term_cf1747c9f0**（domain_term_622495a75d where domain_term_5270860ef0、domain_term_6c503ff027）。',
    '2. domain_term_ce481f7c79“domain_term_338f6517eb”，domain_term_23e7d1330c，domain_term_f75e1c067d“domain_term_02dc2bb268，domain_term_91946dbf26 A、B、C，domain_term_5c2f835884 X/Y domain_term_adbb479817，domain_term_ec640bf5ce”。',
    '3. domain_term_b9657ba3c0（domain_term_76ce4f0238 `_di`、`_df`）domain_term_541bdd065d，domain_term_cc549e1eea，domain_term_3fa9551318。',
    '',
    '[domain_term_796370be1a：domain_term_7e26fddcfe]',
    'domain_term_f25c78d767：',
    '{time_context}',
    '',
    'domain_term_2f3f42be8a，domain_term_effef6209f：',
    '1. **domain_term_ca8ffc3990/domain_term_6783902498**：domain_term_7a8d2a9505**domain_term_2e2a6607e6**domain_term_0b2c440d0e**domain_term_41dcc2ef90**（domain_term_76ce4f0238365domain_term_c3304d1e49）domain_term_0377e12bdf。domain_term_b1183e68bb“domain_term_2322de59a4”。',
    '2. **domain_term_a6121f0caf**：domain_term_d4247a7d1e、domain_term_cfb08a5a71，domain_term_d94a40370f。',
    '3. **domain_term_40ca47026c**：domain_term_9e8d10adb8（domain_term_2e2a6607e6）。',
    '',
    '[domain_term_a017a9dd43]',
    'domain_term_7e69c8e993 Python domain_term_70452534ab：',
    '{warning_msg}',
    '',
    '[domain_term_d981706c7c]',
    '- “domain_term_2e0f9da5f9” (llm_table_short_description):',
    ' domain_term_da7a387500**domain_term_96faf8d5a8**。',
    ' **[domain_term_3a40c21b0a 1 (domain_term_910cd3b9d7)]：** domain_term_6fdda28ed6（domain_term_71facee776 `_di`, `_df`, `_nf` domain_term_c48993524e）domain_term_9a3eb34097 [domain_term_1dda51f9e3 - domain_term_1a0fdce8f8] domain_term_f3274a526b**domain_term_e4e46c7235**（domain_term_46930b1ccf：domain_term_ff4bc7769c, domain_term_ae8b4c82ad, domain_term_710d80eb95, domain_term_1f7802650e）。',
    ' **[domain_term_3a40c21b0a 2 (domain_term_4fea859859)]：** domain_term_087f5cf6a9 [domain_term_1dda51f9e3 - domain_term_159d6b015f] domain_term_4bd6d11873**domain_term_027ae2662e**（domain_term_46930b1ccf：domain_term_e7c31937db, domain_term_6b26695e4d, domain_term_21f1e88275）。',
    '',
    '- “domain_term_2689f46941” (llm_table_long_description):',
    ' domain_term_c855b53e55“domain_term_2e0f9da5f9”domain_term_25829b81c4，domain_term_f9c7768d6d：',
    ' 1. domain_term_d8e70be412**domain_term_3761d64c4d**（domain_term_46930b1ccf "domain_term_b3fbd2bef9..."）。',
    ' 2. domain_term_8aa56da804 [domain_term_d030022925] domain_term_73cbcfe2c2**domain_term_1349c239e2**（domain_term_46930b1ccf：domain_term_502fce2b8d, domain_term_7bc0d789b0, domain_term_08f830f88a）。',
    ' 3. domain_term_1770cfb636**domain_term_da257ba209**（domain_term_46930b1ccf：“domain_term_4318bb5525”，domain_term_30f4d7cfe8“domain_term_9e40369e6c”）。',
    ' 4. domain_term_9eedf1e79e [domain_term_1dda51f9e3 - domain_term_159d6b015f] domain_term_5279445ce5，domain_term_73fadd386c**domain_term_55888db54f**。',
    ' 5. domain_term_9c6cf4f565“domain_term_99550d60ab”，domain_term_28978833d4，domain_term_304c8f0697**domain_term_5dc3742702**（domain_term_46930b1ccf：domain_term_e78a4777c1）。',
    '',
    '[domain_term_b015409988]',
    'domain_term_a4f286dbf2 JSON domain_term_b6bc15e2cf，domain_term_fd1510b265：',
    '{{',
    ' "llm_table_short_description": "...",',
    ' "llm_table_long_description": "..."',
    '}}',
    '"""',
    '',
    ' user_prompt = f"""',
    '[domain_term_c48cadc8f1]',
    'domain_term_584c112b78: `{table_name}`',
    'domain_term_def4ee41bc: "{table_desc}"',
    '',
    '[domain_term_1dda51f9e3 - domain_term_159d6b015f]',
    '{task_knowledge if task_knowledge else "N/A"}',
    '',
    '[domain_term_7e75b8ed1a]',
    '{columns_block}',
    '"""',
    '',
    ' return system_prompt, user_prompt',
    '',
    '',
    'def summarize_fields_with_llm() -> None:',
    ' """domain_term_02b83ec7cc profiling_output_merged domain_term_47b06127a9 *domain_term_77a49f2c38* domain_term_715fb2c0ef LLM domain_term_183f66be3d。"""',
    '',
    ' print("=== domain_term_a3f176f6ce：domain_term_80dd85eb97 ===")',
    ' sme_meta, table_neighbors = load_sme_metadata(SCHEMA_FILE)',
    ' if not sme_meta:',
    ' print("!! schema domain_term_fc19288a47，domain_term_969e4c4929。")',
    ' return',
    '',
    ' common_knowledge = load_common_knowledge(COMMON_KNOWLEDGE_FILE)',
    ' task_knowledge_map = load_advanced_knowledge(TASK_FILE, KNOWLEDGE_ADD_FILE)',
    ' schema_table_desc_map = load_table_descriptions(SCHEMA_FILE)',
    '',
    ' if not PROFILING_DIR.exists():',
    ' print(f"!! domain_term_b859c7be75：domain_term_085cc3ed60: {PROFILING_DIR}")',
    ' return',
    '',
    ' json_files = sorted(PROFILING_DIR.glob("*.json"))',
    ' if not json_files:',
    ' print(f"!! domain_term_b859c7be75：domain_term_686b703f41 \'{PROFILING_DIR}\' domain_term_623cad2a0c。")',
    ' return',
    '',
    ' print(f"domain_term_5f5b329f1d {len(json_files)} domain_term_3bd57797f5（domain_term_84f931fcd5）...")',
    '',
    ' total_called = 0',
    ' total_success = 0',
    ' total_failed = 0',
    '',
    ' for f_path in tqdm(json_files, desc="domain_term_a3f176f6ce (domain_term_6a954390e3)"):',
    ' try:',
    ' with f_path.open("r", encoding="utf-8") as f:',
    ' table_profile = json.load(f)',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_491148f59d：domain_term_5aa1766ab5 {f_path}: {e}")',
    ' continue',
    '',
    ' table_name = table_profile.get("table_name")',
    ' if not table_name:',
    ' continue',
    '',
    ' # domain_term_4170cd5063 schema.json domain_term_ba0ff1b109 SME domain_term_32479058cc',
    ' schema_desc = schema_table_desc_map.get(table_name)',
    ' if schema_desc:',
    ' existing_desc = (table_profile.get("table_description") or "").strip()',
    ' if existing_desc:',
    ' # domain_term_bc6005c71e schema domain_term_412f54dc38，domain_term_53babcef72',
    ' if schema_desc not in existing_desc:',
    ' table_profile["table_description"] = f"{existing_desc}；{schema_desc}"',
    ' else:',
    ' table_profile["table_description"] = schema_desc',
    '',
    ' neighbors = table_neighbors.get(table_name, [])',
    ' task_knowledge = task_knowledge_map.get(table_name, "")',
    ' modified = False',
    '',
    ' for col_profile in table_profile.get("columns_profile", []):',
    ' col_name = col_profile.get("column_name")',
    ' if not col_name:',
    ' continue',
    '',
    ' # domain_term_8c216ee9ec；domain_term_aba1d9f555 "domain_term_3136597313"',
    ' if (',
    ' col_profile.get("llm_short_description")',
    ' and col_profile.get("llm_short_description") != "domain_term_3136597313"',
    ' ):',
    ' continue',
    '',
    ' full_name = f"{table_name}.{col_name}"',
    ' sme_description = sme_meta.get(full_name, "")',
    '',
    ' system_prompt, user_prompt = build_field_llm_prompt(',
    ' table_profile,',
    ' col_profile,',
    ' sme_description,',
    ' neighbors,',
    ' common_knowledge,',
    ' task_knowledge,',
    ' )',
    '',
    ' total_called += 1',
    '',
    ' try:',
    ' result = _call_llm_json(system_prompt, user_prompt)',
    ' short_desc = (result.get("llm_short_description") or "").strip()',
    ' long_desc = (result.get("llm_long_description") or "").strip()',
    ' if not short_desc or not long_desc:',
    ' raise RuntimeError("LLM domain_term_8abf71bfc7 llm_short_description / llm_long_description")',
    '',
    ' col_profile["llm_short_description"] = short_desc',
    ' col_profile["llm_long_description"] = long_desc',
    ' modified = True',
    ' total_success += 1',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_ac6d289a8c: {full_name}: {e}")',
    ' col_profile["llm_short_description"] = "domain_term_3136597313"',
    ' col_profile["llm_long_description"] = "domain_term_3136597313"',
    ' modified = True',
    ' total_failed += 1',
    '',
    ' if modified:',
    ' try:',
    ' with f_path.open("w", encoding="utf-8") as f:',
    ' json.dump(table_profile, f, ensure_ascii=False, indent=4)',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_cf46b16401 {f_path}: {e}")',
    '',
    ' print("=" * 60)',
    ' print("domain_term_a83259e1b6。")',
    ' print(f"domain_term_4c0ab6484b LLM {total_called} domain_term_5e5b8169ee，domain_term_6d17d0d86c {total_success} domain_term_5e5b8169ee，domain_term_3e3c8068bb {total_failed} domain_term_5e5b8169ee。")',
    ' print("=" * 60)',
    '',
    '',
    'def summarize_tables_with_llm() -> None:',
    ' """domain_term_a33cb3b686，domain_term_a57f666576 LLM domain_term_183f66be3d。"""',
    '',
    ' print("=== domain_term_d11ce92d95：domain_term_80dd85eb97 ===")',
    '',
    ' common_knowledge = load_common_knowledge(COMMON_KNOWLEDGE_FILE)',
    ' task_knowledge_map = load_advanced_knowledge(TASK_FILE, KNOWLEDGE_ADD_FILE)',
    ' schema_table_desc_map = load_table_descriptions(SCHEMA_FILE)',
    '',
    ' if not PROFILING_DIR.exists():',
    ' print(f"!! domain_term_b859c7be75：domain_term_085cc3ed60: {PROFILING_DIR}")',
    ' return',
    '',
    ' json_files = sorted(PROFILING_DIR.glob("*.json"))',
    ' if not json_files:',
    ' print(f"!! domain_term_b859c7be75：domain_term_686b703f41 \'{PROFILING_DIR}\' domain_term_623cad2a0c。")',
    ' return',
    '',
    ' print(f"domain_term_5f5b329f1d {len(json_files)} domain_term_0323261479 *domain_term_d0102a7431* domain_term_46d4c1b4e4（domain_term_ee3ac1da5e）...")',
    '',
    ' total_called = 0',
    ' total_success = 0',
    ' total_failed = 0',
    '',
    ' for f_path in tqdm(json_files, desc="domain_term_d11ce92d95 (domain_term_6a954390e3)"):',
    ' try:',
    ' with f_path.open("r", encoding="utf-8") as f:',
    ' table_profile = json.load(f)',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_491148f59d：domain_term_5aa1766ab5 {f_path}: {e}")',
    ' continue',
    '',
    ' table_name = table_profile.get("table_name")',
    ' if not table_name:',
    ' continue',
    '',
    ' # domain_term_ad85548714',
    ' if (',
    ' table_profile.get("llm_table_short_description")',
    ' and table_profile.get("llm_table_short_description") != "domain_term_3136597313"',
    ' ):',
    ' continue',
    '',
    ' # domain_term_4170cd5063 schema.json domain_term_ba0ff1b109 SME domain_term_32479058cc',
    ' schema_desc = schema_table_desc_map.get(table_name)',
    ' if schema_desc:',
    ' existing_desc = (table_profile.get("table_description") or "").strip()',
    ' if existing_desc:',
    ' if schema_desc not in existing_desc:',
    ' table_profile["table_description"] = f"{existing_desc}；{schema_desc}"',
    ' else:',
    ' table_profile["table_description"] = schema_desc',
    '',
    ' task_knowledge = task_knowledge_map.get(table_name, "")',
    '',
    ' columns_short_descriptions: List[str] = []',
    ' for c in table_profile.get("columns_profile", []):',
    ' sd = c.get("llm_short_description")',
    ' if sd and sd != "domain_term_3136597313":',
    ' columns_short_descriptions.append(f"{c.get(\'column_name\')}: {sd}")',
    '',
    ' if not columns_short_descriptions:',
    ' print(f"domain_term_5521e368d8：domain_term_6a954390e3 {table_name} domain_term_e13833c431，domain_term_ff8634a130。")',
    ' continue',
    '',
    ' system_prompt, user_prompt = build_table_llm_prompt(',
    ' table_profile,',
    ' columns_short_descriptions,',
    ' common_knowledge,',
    ' task_knowledge,',
    ' )',
    '',
    ' total_called += 1',
    ' modified = False',
    '',
    ' try:',
    ' result = _call_llm_json(system_prompt, user_prompt)',
    ' short_desc = (result.get("llm_table_short_description") or "").strip()',
    ' long_desc = (result.get("llm_table_long_description") or "").strip()',
    ' if not short_desc or not long_desc:',
    ' raise RuntimeError(',
    ' "LLM domain_term_8abf71bfc7 llm_table_short_description / llm_table_long_description",',
    ' )',
    '',
    ' table_profile["llm_table_short_description"] = short_desc',
    ' table_profile["llm_table_long_description"] = long_desc',
    ' modified = True',
    ' total_success += 1',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_c2b01bc9de: {table_name}: {e}")',
    ' table_profile["llm_table_short_description"] = "domain_term_3136597313"',
    ' table_profile["llm_table_long_description"] = "domain_term_3136597313"',
    ' modified = True',
    ' total_failed += 1',
    '',
    ' if modified:',
    ' try:',
    ' with f_path.open("w", encoding="utf-8") as f:',
    ' json.dump(table_profile, f, ensure_ascii=False, indent=4)',
    ' except Exception as e: # noqa: BLE001',
    ' print(f"!! domain_term_cf46b16401 {f_path}: {e}")',
    '',
    ' print("=" * 60)',
    ' print("domain_term_1b4c2e5c2a。")',
    ' print(f"domain_term_4c0ab6484b LLM {total_called} domain_term_5e5b8169ee，domain_term_6d17d0d86c {total_success} domain_term_5e5b8169ee，domain_term_3e3c8068bb {total_failed} domain_term_5e5b8169ee。")',
    ' print("=" * 60)',
    '',
    '',
    'def main() -> None:',
    ' """domain_term_75d67ca961：domain_term_82d45ef210 DB domain_term_1dd014a84e deep_stats，domain_term_7bb8911142。"""',
    '',
    ' enrich_profiles_with_db()',
    ' summarize_fields_with_llm()',
    ' summarize_tables_with_llm()',
    '',
    '',
    'if __name__ == "__main__":',
    ' main()',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
