# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `1.knowledge_base/1.2_positive_knowledge_sources_and_construction/build_knowledge_prompts.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    'import json',
    'import os',
    'import requests',
    'import shutil',
    'from pathlib import Path',
    'from typing import Dict, Any, List',
    'import sys',
    'from openai import OpenAI',
    '',
    '# domain_term_c6b5001f0b',
    'BASE_DIR = Path(__file__).resolve().parent.parent.parent',
    'DATA_DIR = BASE_DIR / "data"',
    'T2SQL_DIR = BASE_DIR',
    '',
    'FINAL_DATASET_PATH = DATA_DIR / "final_dataset.json"',
    'SCHEMA_SHORT_PATH = DATA_DIR / "schema_all_gemini.json"',
    'CORRECT_SQL_PATH = DATA_DIR / "correct_59.json"',
    'BAD_SQL_JSONL_PATH = T2SQL_DIR / "run/datafile/output/results-finalize.jsonl"',
    'ADDED_KNOWLEDGE_PATH = DATA_DIR / "knowledge_add_clean_list.json"',
    'OUTPUT_PATH = DATA_DIR / "knowledge_ideal_generated.json"',
    '# domain_term_e182e21dfd agent domain_term_add80f7bad，domain_term_0e2d3a3c09 common_knowledge2.md domain_term_5629be91a4',
    'COMMON_KNOWLEDGE_PATH = DATA_DIR / "common_knowledge2.md"',
    'EVAL_INCORRECT_PATH = T2SQL_DIR / "run/datafile/output/eval_incorrect_ids.json"',
    'VERIFIED_KB_PATH = BASE_DIR / "data_detective_knowledge" / "correct_verified_knowledge.json"',
    '',
    '# domain_term_b71806ecbc Gemini domain_term_38719c9968（domain_term_d640a39adc）',
    'GEMINI_MODEL = "gemini-3-pro-preview"',
    '',
    '# domain_term_01b5ce180e run/agent/config.py domain_term_b6b97ac60d GEMINI_API_KEY / GEMINI_MODEL，domain_term_118f47ee51',
    '_RUN_DIR = T2SQL_DIR / "run"',
    '_AGENT_DIR = _RUN_DIR / "agent"',
    'if str(_AGENT_DIR) not in sys.path:',
    ' sys.path.insert(0, str(_AGENT_DIR))',
    '',
    'try:',
    ' from config import (',
    ' GEMINI_API_KEY as CFG_GEMINI_API_KEY,',
    ' GEMINI_MODEL as CFG_GEMINI_MODEL,',
    ' GEMINI_API_KEY_LIST as CFG_GEMINI_API_KEY_LIST,',
    ' GEMINI_BASE_URL as CFG_GEMINI_BASE_URL,',
    ' RESULTS_PATH as CFG_RESULTS_PATH,',
    ' )',
    'except Exception:',
    ' CFG_GEMINI_API_KEY = ""',
    ' CFG_GEMINI_MODEL = None',
    ' CFG_GEMINI_API_KEY_LIST = []',
    ' CFG_GEMINI_BASE_URL = ""',
    ' CFG_RESULTS_PATH = None',
    '',
    'if CFG_GEMINI_MODEL:',
    ' GEMINI_MODEL = CFG_GEMINI_MODEL',
    '',
    'if CFG_RESULTS_PATH:',
    ' BAD_SQL_JSONL_PATH = CFG_RESULTS_PATH',
    '',
    '# domain_term_da48238617 sql_id domain_term_d46f82fdf0',
    'TARGET_SQL_IDS = [',
    ' "sql_1", "sql_11", "sql_24", "sql_26",',
    ' "sql_50" ,"sql_65", "sql_103", "sql_113"',
    ']',
    '',
    '',
    'def load_json(path: Path):',
    ' with open(path, "r", encoding="utf-8") as f:',
    ' return json.load(f)',
    '',
    '',
    'def load_final_dataset() -> Dict[str, Dict[str, Any]]:',
    ' data = load_json(FINAL_DATASET_PATH)',
    ' return {item.get("sql_id"): item for item in data if item.get("sql_id")}',
    '',
    '',
    'def load_schema_short() -> Dict[str, Dict[str, Any]]:',
    ' arr = load_json(SCHEMA_SHORT_PATH)',
    ' return {t.get("table_name"): t for t in arr if t.get("table_name")}',
    '',
    '',
    'def load_correct_sql_map() -> Dict[str, str]:',
    ' arr = load_json(CORRECT_SQL_PATH)',
    ' m: Dict[str, str] = {}',
    ' for item in arr:',
    ' sid = item.get("sql_id")',
    ' sql = item.get("sql")',
    ' if sid and isinstance(sql, str) and sql.strip():',
    ' m[sid] = sql.strip()',
    ' return m',
    '',
    '',
    'def load_bad_sql_map() -> Dict[str, List[str]]:',
    ' """domain_term_8ab977960a Agent / batch domain_term_0fbb0bce3d sql_id domain_term_b4702d6fd8 SQL domain_term_3c9dffb3b8。',
    '',
    ' - domain_term_bbd547c5f9 results-finalize.jsonl:',
    ' * domain_term_3297422a3e final_sql/sql',
    ' * domain_term_f2f623092b candidate.generated_sql',
    ' * domain_term_f2f623092b candidate.used_sql',
    ' domain_term_7b459e4117 4 domain_term_c0e134ae0d SQL + domain_term_9d56f5bf6a SQL（domain_term_b256cafec6），domain_term_4e192abc56 Bad Case。',
    '',
    ' - domain_term_b445ae061e batch domain_term_49deaf7da2:',
    ' * domain_term_67e6e9e172 JSON, domain_term_35d40b6e6f custom_id domain_term_0d31d5d80a response.body.choices.message.content',
    ' """',
    ' m: Dict[str, List[str]] = {}',
    ' if not BAD_SQL_JSONL_PATH.exists():',
    ' return m',
    '',
    ' # domain_term_1ae61906ba seen domain_term_9a522870d2，domain_term_f40d5d1033 sql_id domain_term_1dfc8760ab SQL',
    ' seen: Dict[str, set] = {}',
    '',
    ' def _add_sql(sid: Any, sql: Any):',
    ' if not sid or not isinstance(sql, str):',
    ' return',
    ' s = sql.strip()',
    ' if not s:',
    ' return',
    ' key = str(sid)',
    ' if key not in seen:',
    ' seen[key] = set()',
    ' if s in seen[key]:',
    ' return',
    ' seen[key].add(s)',
    ' m.setdefault(key, []).append(s)',
    '',
    ' # domain_term_17a9a7598d JSON domain_term_6bc9a99588 (finalize_results-3.py / agent.py domain_term_1e2dc87b02)',
    ' try:',
    ' text = BAD_SQL_JSONL_PATH.read_text(encoding="utf-8", errors="ignore")',
    ' stripped = text.lstrip()',
    ' if stripped and stripped[0] in "[{":',
    ' data = json.loads(text)',
    ' if isinstance(data, list):',
    ' for obj in data:',
    ' if not isinstance(obj, dict):',
    ' continue',
    ' sid = obj.get("sql_id") or obj.get("id")',
    ' if not sid:',
    ' continue',
    '',
    ' # 1) domain_term_96fd4c2a7f SQL',
    ' final_sql = obj.get("final_sql") or obj.get("sql")',
    ' _add_sql(sid, final_sql)',
    '',
    ' # 2) domain_term_eba4161da4 candidates domain_term_0746bd6249 generated_sql / used_sql',
    ' cands = obj.get("candidates") or []',
    ' if isinstance(cands, list):',
    ' for cand in cands:',
    ' if not isinstance(cand, dict):',
    ' continue',
    ' _add_sql(sid, cand.get("generated_sql"))',
    ' _add_sql(sid, cand.get("used_sql"))',
    '',
    ' if m:',
    ' return m',
    ' except Exception:',
    ' pass',
    '',
    ' # domain_term_d50f2d344a: domain_term_3b887dd84c JSONL, domain_term_ddd68c5c5e agent domain_term_42ad97ddd0 batch domain_term_953c96d7dd',
    ' with open(BAD_SQL_JSONL_PATH, "r", encoding="utf-8") as f:',
    ' for line in f:',
    ' if not line.strip():',
    ' continue',
    ' try:',
    ' obj = json.loads(line)',
    ' except Exception:',
    ' continue',
    '',
    ' if not isinstance(obj, dict):',
    ' continue',
    '',
    ' # 1) domain_term_1fdb19c4ea agent domain_term_ded698ae1e: {sql_id, final_sql/sql, candidates:[...]}',
    ' sid = obj.get("sql_id") or obj.get("id")',
    ' if sid:',
    ' final_sql = obj.get("final_sql") or obj.get("sql")',
    ' _add_sql(sid, final_sql)',
    '',
    ' cands = obj.get("candidates") or []',
    ' if isinstance(cands, list):',
    ' for cand in cands:',
    ' if not isinstance(cand, dict):',
    ' continue',
    ' _add_sql(sid, cand.get("generated_sql"))',
    ' _add_sql(sid, cand.get("used_sql"))',
    ' continue',
    '',
    ' # 2) domain_term_8d2739697a batch domain_term_ded698ae1e: {custom_id, response.body.choices[0].message.content}',
    ' cid = obj.get("custom_id") or ""',
    ' if "-gen-" not in cid:',
    ' continue',
    ' sql_id = cid.split("-gen-", 1)[0]',
    ' text_val = None',
    ' try:',
    ' body = obj.get("response", {}).get("body", {})',
    ' choices = body.get("choices", [])',
    ' if choices:',
    ' text_val = choices[0].get("message", {}).get("content")',
    ' except Exception:',
    ' text_val = None',
    ' _add_sql(sql_id, text_val)',
    ' return m',
    '',
    '',
    'def load_old_knowledge_map() -> Dict[str, str]:',
    ' arr = load_json(ADDED_KNOWLEDGE_PATH)',
    ' m: Dict[str, str] = {}',
    ' for item in arr:',
    ' sid = item.get("sql_id")',
    ' kn = item.get("knowledge")',
    ' if sid and isinstance(kn, str) and kn.strip():',
    ' m[sid] = kn.strip()',
    ' return m',
    '',
    '',
    'def load_verified_kb_map() -> Dict[str, str]:',
    ' """domain_term_3363f3729b data_detective_knowledge/verified_knowledge_base.json domain_term_a00dca4da5 sql_id domain_term_64f6b0ee67。"""',
    ' if not VERIFIED_KB_PATH.exists():',
    ' return {}',
    ' try:',
    ' data = load_json(VERIFIED_KB_PATH)',
    ' m: Dict[str, str] = {}',
    ' if isinstance(data, list):',
    ' for item in data:',
    ' if not isinstance(item, dict):',
    ' continue',
    ' sid = item.get("sql_id")',
    ' vlogic = item.get("verified_logic")',
    ' if sid and isinstance(vlogic, str) and vlogic.strip():',
    ' m[sid] = vlogic.strip()',
    ' if m:',
    ' print(f"[*] domain_term_f8eeebdf3b {len(m)} domain_term_bce2ef6151 (from {VERIFIED_KB_PATH})")',
    ' return m',
    ' except Exception as e:',
    ' print(f"[!] domain_term_09314905ad: {e}")',
    ' return {}',
    '',
    '',
    'def load_common_knowledge() -> str:',
    ' """domain_term_213c8ae4d7，domain_term_8a31d03da6。',
    '',
    ' domain_term_a710dca9f5 common_knowledge2.md，domain_term_e182e21dfd agent domain_term_219193ba40，',
    ' domain_term_82d28d621c Markdown domain_term_0f02bc3578 JSON domain_term_0a95106968。',
    ' """',
    ' if not COMMON_KNOWLEDGE_PATH.exists():',
    ' return ""',
    ' try:',
    ' return COMMON_KNOWLEDGE_PATH.read_text(encoding="utf-8")',
    ' except Exception:',
    ' return ""',
    '',
    '',
    'def load_incorrect_sql_ids() -> List[str]:',
    ' if not EVAL_INCORRECT_PATH.exists():',
    ' print(f"[!] domain_term_1e8093cce6: {EVAL_INCORRECT_PATH}")',
    ' return []',
    ' try:',
    ' with open(EVAL_INCORRECT_PATH, "r", encoding="utf-8") as f:',
    ' data = json.load(f)',
    ' except Exception as e:',
    ' print(f"[!] domain_term_c673901275: {e}")',
    ' return []',
    '',
    ' if isinstance(data, list):',
    ' return [str(x) for x in data if x]',
    ' if isinstance(data, dict):',
    ' ids = data.get("incorrect_ids") or []',
    ' return [str(x) for x in ids if x]',
    ' return []',
    '',
    '',
    'def _load_existing_knowledge_entries() -> List[Dict[str, Any]]:',
    ' if not ADDED_KNOWLEDGE_PATH.exists():',
    ' return []',
    ' try:',
    ' arr = load_json(ADDED_KNOWLEDGE_PATH)',
    ' if isinstance(arr, list):',
    ' return arr',
    ' except Exception:',
    ' pass',
    ' return []',
    '',
    '',
    'def update_knowledge_base(new_knowledge_map: Dict[str, str]):',
    ' existing_list = _load_existing_knowledge_entries()',
    ' merged: Dict[str, Dict[str, Any]] = {}',
    '',
    ' for item in existing_list:',
    ' if not isinstance(item, dict):',
    ' continue',
    ' sid = item.get("sql_id")',
    ' if not sid:',
    ' continue',
    ' merged[sid] = item',
    '',
    ' for sid, text in new_knowledge_map.items():',
    ' if not sid or not isinstance(text, str):',
    ' continue',
    ' trimmed = text.strip()',
    ' if not trimmed:',
    ' continue',
    ' merged[sid] = {"sql_id": sid, "knowledge": trimmed}',
    '',
    ' merged_list = sorted(merged.values(), key=lambda x: x.get("sql_id", "")) if merged else []',
    '',
    ' if ADDED_KNOWLEDGE_PATH.exists():',
    ' try:',
    ' backup_path = ADDED_KNOWLEDGE_PATH.with_suffix(ADDED_KNOWLEDGE_PATH.suffix + ".bak")',
    ' shutil.copy2(ADDED_KNOWLEDGE_PATH, backup_path)',
    ' print(f"[*] domain_term_c8c468dd7d: {backup_path}")',
    ' except Exception as e:',
    ' print(f"[!] domain_term_fb6caf8a66: {e}")',
    '',
    ' with open(ADDED_KNOWLEDGE_PATH, "w", encoding="utf-8") as f:',
    ' json.dump(merged_list, f, ensure_ascii=False, indent=2)',
    ' print(f"[*] domain_term_433fd7059a: {ADDED_KNOWLEDGE_PATH}")',
    '',
    '',
    'def build_schema_snippet(table_list: List[str], schema_map: Dict[str, Dict[str, Any]]) -> str:',
    ' """domain_term_8aa56da804 table_list domain_term_8ab977960a schema_all_gemini.json domain_term_32306140a4。',
    '',
    ' - domain_term_a0657db9b1 table_description_llm_long，domain_term_ed81d20397 table_description_llm_short，domain_term_321e225c63 table_description。',
    ' - domain_term_ed82a3c48b llm_long_description，domain_term_ed81d20397 llm_short_description，domain_term_f8364b90a2 description。',
    ' - domain_term_f06e2373c0 table_name, table_description, columns[col, type, description]，domain_term_15ceb916f0 LLM。',
    ' """',
    '',
    ' tables: List[Dict[str, Any]] = []',
    ' for name in table_list or []:',
    ' t = schema_map.get(name)',
    ' if not isinstance(t, dict):',
    ' continue',
    '',
    ' # domain_term_67484ee5ba',
    ' table_desc = (',
    ' t.get("table_description_llm_long")',
    ' or t.get("table_description_llm_short")',
    ' or t.get("table_description")',
    ' or ""',
    ' )',
    '',
    ' # domain_term_a6e8eb733c',
    ' cols: List[Dict[str, Any]] = []',
    ' for col in t.get("columns", []):',
    ' if not isinstance(col, dict):',
    ' continue',
    ' col_name = col.get("col") or col.get("name") or col.get("column_name")',
    ' if not col_name:',
    ' continue',
    ' desc = (',
    ' col.get("llm_long_description")',
    ' or col.get("llm_short_description")',
    ' or col.get("description")',
    ' or ""',
    ' )',
    ' cols.append({',
    ' "col": col_name,',
    ' "type": col.get("type"),',
    ' "description": desc,',
    ' })',
    '',
    ' tables.append({',
    ' "table_name": t.get("table_name", name),',
    ' "table_description": table_desc,',
    ' "columns": cols,',
    ' })',
    '',
    ' if not tables:',
    ' return ""',
    ' return json.dumps(tables, ensure_ascii=False, indent=2)',
    '',
    '',
    'SYSTEM_PROMPT = """### domain_term_6b26695e4d',
    'domain_term_3661fc5f50 AI domain_term_14816f768c（Knowledge Engineer）。',
    '',
    '### domain_term_293876c8ad',
    'domain_term_974deb0bcf“domain_term_2e69512ad4”（SQLdomain_term_9261fa6496、domain_term_c9381ae078SQL、domain_term_02728d6287、domain_term_ced238a467），domain_term_48c6d5808a，**domain_term_99ea329bb4“domain_term_11942132d0”**。',
    'domain_term_96fd4c2a7f，domain_term_d065f3c0da、domain_term_c6469e4f74“domain_term_ba909cde98”（Ideal Knowledge Text），domain_term_f457964436 AI domain_term_52a6ea4a4c。',
    '',
    '### domain_term_01e20e520a (Input Specification)',
    'domain_term_686b703f41 User Prompt domain_term_0869071c92，domain_term_2e8c921c95：',
    '1. **SQL domain_term_9261fa6496**：StarRocks。',
    '2. **domain_term_36a1c8b7d3 (Schema)**：domain_term_2169bad2de。',
    '3. **domain_term_eba17158f5**：domain_term_93078e7949。',
    '4. **domain_term_f73d8418d3 SQL (Golden SQL)**：domain_term_619afd43e4“domain_term_c8da6e38bb”。',
    '5. **domain_term_b859c7be75 SQL (Bad Case)**：AI domain_term_0c0bc77f9c。',
    '6. **domain_term_02728d6287 (Reference Knowledge)**：[domain_term_ffc1d065fb] domain_term_984642227e(Evidence)、domain_term_3820254623(Common)domain_term_8d68f1cc89(Verified)。**domain_term_604a0025e1，domain_term_7d519b6550，domain_term_721802cfea。**',
    '7. **domain_term_11942132d0 (Old Knowledge)**：[domain_term_639de75176] domain_term_9899e5d4d0 AI domain_term_9f34b8caa1，domain_term_7a15609575**domain_term_f2cf4f3b04**。',
    '',
    '### domain_term_ddb47cef02 (Ideal Output)',
    '1. **domain_term_28e3935439**：domain_term_ded698ae1e**domain_term_890e87b370**domain_term_33ebd6f362“domain_term_ba909cde98”domain_term_f1926e9b33。',
    '2. **domain_term_08337d2dc1**：domain_term_9536907a0b，domain_term_0959148e3d。domain_term_8d68f258a5、domain_term_c9acc26f65、domain_term_eda4dd3773。',
    '3. **domain_term_9d2601c843**：domain_term_6401a97433、domain_term_794f986189。',
    '',
    '### domain_term_96b2372813',
    '- **domain_term_c5a804b2c0**domain_term_4f3a320ce0、SQL domain_term_110b3d6f02。',
    '- **domain_term_65bb264700“domain_term_851bca3252”。**',
    '"""',
    '',
    '',
    'def build_user_prompt(',
    ' schema_text: str,',
    ' question: str,',
    ' right_sql: str,',
    ' bad_sql_list: List[str],',
    ' old_knowledge: str,',
    ' evidence: str,',
    ' common_kn: str,',
    ' verified_kn: str,',
    ') -> str:',
    '',
    ' schema_block = schema_text or "(domain_term_72077749f7)"',
    '',
    ' # domain_term_5a4995338d SQL domain_term_e44b48e089',
    ' if bad_sql_list:',
    ' labeled_bad_sql = []',
    ' for idx, sql in enumerate(bad_sql_list, start=1):',
    ' labeled_bad_sql.append(f"domain_term_b859c7be75SQL{idx}:\\n{sql}")',
    ' bad_sql_block = "\\n\\n".join(labeled_bad_sql)',
    ' else:',
    ' bad_sql_block = "(domain_term_226b485ce1SQL，domain_term_315a7d660b)"',
    '',
    ' # --- domain_term_81a94d85f0 Reference Knowledge domain_term_e44b48e089 (domain_term_ffc1d065fb/domain_term_b27b76aa15) ---',
    ' ref_parts: List[str] = []',
    ' if common_kn:',
    ' ref_parts.append(f"[Common Knowledge / domain_term_3820254623]\\n{common_kn}")',
    ' if evidence:',
    ' ref_parts.append(f"[Dataset Evidence / domain_term_5132b39387]\\n{evidence}")',
    ' if verified_kn:',
    ' ref_parts.append(f"[Verified Logic / domain_term_79a0d2cb91]\\n{verified_kn}")',
    '',
    ' reference_block = "\\n\\n".join(ref_parts) if ref_parts else "(domain_term_d681d2673a)"',
    '',
    ' # --- domain_term_3e391792b8 ---',
    ' old_kn_block = old_knowledge or "(domain_term_5ba09e7d7b，domain_term_dbf9d45ea7)"',
    '',
    ' return f"""### 1. domain_term_7f22a97b9d (SQL Dialect)',
    'StarRocks',
    '',
    '### 2. domain_term_40f3721952 (Schema)',
    '{schema_block}',
    '',
    '### 3. domain_term_eba17158f5',
    '{question}',
    '',
    '### 4. domain_term_f73d8418d3 SQL (Golden SQL)',
    '{right_sql}',
    '',
    '### 5. domain_term_b859c7be75 SQL (Bad Case)',
    '{bad_sql_block}',
    '',
    '### 6. domain_term_02728d6287 (Reference Knowledge)',
    '**domain_term_f08b55c42c：domain_term_97cf958e79，domain_term_9faec6b853，domain_term_787c2fedd1。**',
    '{reference_block}',
    '',
    '### 7. domain_term_3e391792b8 (Old Knowledge)',
    '**domain_term_f08b55c42c：domain_term_95af62f8a0，domain_term_b553e0ea52。**',
    '{old_kn_block}',
    '"""',
    '',
    '',
    'def get_client() -> List[str]:',
    ' """domain_term_5f49c1c38d Gemini API Key domain_term_d46f82fdf0。',
    '',
    ' domain_term_01b5ce180e config.GEMINI_API_KEY_LIST domain_term_b6b97ac60d，domain_term_420b4b09c4 GEMINI_API_KEY / domain_term_8da07705ab',
    ' GEMINI_API_KEY / GOOGLE_API_KEY。',
    ' """',
    ' keys: List[str] = []',
    ' if CFG_GEMINI_API_KEY_LIST:',
    ' keys = [k for k in CFG_GEMINI_API_KEY_LIST if k]',
    ' if not keys and CFG_GEMINI_API_KEY:',
    ' keys = [CFG_GEMINI_API_KEY]',
    ' if not keys:',
    ' env_key = (',
    ' os.environ.get("GEMINI_API_KEY")',
    ' or os.environ.get("GOOGLE_API_KEY")',
    ' )',
    ' if env_key:',
    ' keys = [env_key]',
    ' if not keys:',
    ' raise RuntimeError("GEMINI_API_KEY domain_term_96fe90e78a config.py domain_term_43179ed575！")',
    ' return keys',
    '',
    '',
    'def call_llm(client_keys: List[str], user_prompt: str, model: str) -> str:',
    ' """domain_term_b1fb011bbf Gemini domain_term_98fd0cbd9c，domain_term_87b5cdbed0。',
    '',
    ' domain_term_c67e02ad78 HTTP domain_term_d59a467f22 Gemini domain_term_9d24532bfc：',
    ' https://gemini-api.poenl.top/v1beta/models/{model}:generateContent',
    ' """',
    ' combined = f"{SYSTEM_PROMPT}\\n\\n{user_prompt}"',
    ' print(combined)',
    '',
    ' last_error = None',
    ' base_url = CFG_GEMINI_BASE_URL or os.environ.get("GEMINI_BASE_URL") or "https://api.gemai.cc/v1"',
    '',
    ' for idx, key in enumerate(client_keys):',
    ' print(f"[*] domain_term_0e2d3a3c09 Gemini Key #{idx + 1}/{len(client_keys)} domain_term_48f737548a...")',
    ' try:',
    ' client = OpenAI(api_key=key, base_url=base_url)',
    ' resp = client.chat.completions.create(',
    ' model=model,',
    ' messages=[',
    ' {"role": "system", "content": SYSTEM_PROMPT},',
    ' {"role": "user", "content": user_prompt},',
    ' ],',
    ' temperature=0.2,',
    ' max_tokens=4096,',
    ' reasoning_effort="high",',
    ' )',
    ' except Exception as e:',
    ' print(f"[!] domain_term_b1fb011bbf Gemini domain_term_a115d4d498 (Key #{idx + 1}): {e}")',
    ' last_error = e',
    ' continue',
    '',
    ' text = ""',
    ' try:',
    ' choice = resp.choices[0]',
    ' msg = getattr(choice, "message", choice)',
    ' content = getattr(msg, "content", None)',
    ' if isinstance(content, str):',
    ' text = content',
    ' elif isinstance(content, list):',
    ' texts: List[str] = []',
    ' for part in content:',
    ' t = getattr(part, "text", None)',
    ' if isinstance(t, str):',
    ' texts.append(t)',
    ' text = "".join(texts)',
    ' except Exception:',
    ' text = ""',
    ' return (text or "").strip()',
    '',
    ' if last_error is not None:',
    ' print(f"[!] domain_term_eba4161da4 Gemini Key domain_term_03b6b1ff09，domain_term_4f2f96fcf2: {last_error}")',
    ' else:',
    ' print("[!] domain_term_eba4161da4 Gemini Key domain_term_03b6b1ff09")',
    ' return ""',
    '',
    '',
    'def main():',
    ' final_dataset = load_final_dataset()',
    ' schema_map = load_schema_short()',
    ' correct_sql_map = load_correct_sql_map()',
    ' bad_sql_map = load_bad_sql_map()',
    ' old_kn_map = load_old_knowledge_map()',
    ' verified_kb_map = load_verified_kb_map()',
    ' common_kn_text = load_common_knowledge()',
    '',
    ' client_keys = get_client()',
    '',
    ' results: Dict[str, str] = {}',
    '',
    ' target_sql_ids = load_incorrect_sql_ids()',
    ' if not target_sql_ids:',
    ' print("[*] domain_term_59a5a3ce95 sql_id，domain_term_ba5c67c110。")',
    ' return',
    '',
    ' for sid in target_sql_ids:',
    ' task = final_dataset.get(sid)',
    ' if not task:',
    ' print(f"[!] domain_term_31a98593f1 {sid}: domain_term_686b703f41 final_dataset.json domain_term_cf23c016c1")',
    ' continue',
    '',
    ' question = task.get("question", "").strip()',
    ' evidence = task.get("evidence", "").strip()',
    ' table_list = task.get("table_list", [])',
    ' schema_text = build_schema_snippet(table_list, schema_map)',
    '',
    ' right_sql = correct_sql_map.get(sid, "").strip()',
    ' if not right_sql:',
    ' # domain_term_d586d0ec98 CORRECT_SQL_PATH.name domain_term_899f63ef83，domain_term_a7d7c43110',
    ' print(f"[!] domain_term_31a98593f1 {sid}: domain_term_686b703f41 {CORRECT_SQL_PATH.name} domain_term_b488cf6422 SQL")',
    ' continue',
    '',
    ' bad_sql_list = bad_sql_map.get(sid, [])',
    ' old_kn = (old_kn_map.get(sid, "") or "").strip()',
    ' vlogic = (verified_kb_map.get(sid, "") or "").strip()',
    ' user_prompt = build_user_prompt(',
    ' schema_text=schema_text,',
    ' question=question,',
    ' right_sql=right_sql,',
    ' bad_sql_list=bad_sql_list,',
    ' old_knowledge=old_kn,',
    ' evidence=evidence,',
    ' common_kn=common_kn_text,',
    ' verified_kn=vlogic,',
    ' )',
    '',
    ' print(f"[*] domain_term_b1fb011bbf Gemini domain_term_4aa2306395 {sid} domain_term_77ae859c13...")',
    ' ideal_text = call_llm(client_keys, user_prompt, GEMINI_MODEL)',
    ' results[sid] = ideal_text',
    '',
    ' # domain_term_03ecc379d0',
    ' out_obj = [',
    ' {"sql_id": sid, "knowledge": txt}',
    ' for sid, txt in results.items()',
    ' ]',
    ' with open(OUTPUT_PATH, "w", encoding="utf-8") as f:',
    ' json.dump(out_obj, f, ensure_ascii=False, indent=2)',
    '',
    ' print(f"[*] domain_term_eafb9604d9 {len(results)} domain_term_f7b2a6ee68 sql_id domain_term_d61ef95768，domain_term_9e93bdccb2 {OUTPUT_PATH}")',
    '',
    ' update_knowledge_base(results)',
    ' print(f"[*] domain_term_0fb25ee255 {ADDED_KNOWLEDGE_PATH}")',
    '',
    '',
    'if __name__ == "__main__":',
    ' main()',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
