# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `1.knowledge_base/1.2_positive_knowledge_sources_and_construction/pipeline_loop_runner.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    'import json',
    'import time',
    'from pathlib import Path',
    'from typing import List',
    '',
    'import sys',
    '',
    'from pipeline_runner import (',
    ' step2_prepare_sql_exe_input,',
    ' step3_run_sql_exe,',
    ' step4_run_evaluation,',
    ' step5_build_knowledge,',
    ')',
    '',
    '',
    '# domain_term_e182e21dfd pipeline_runner / build_knowledge_prompts domain_term_40ac1b9922',
    '_HERE = Path(__file__).resolve()',
    '_RUN_DIR = _HERE.parent.parent',
    '_AGENT_DIR = _RUN_DIR / "agent"',
    'if str(_AGENT_DIR) not in sys.path:',
    ' sys.path.insert(0, str(_AGENT_DIR))',
    '',
    'from config import T2SQL_DIR, BASE_DIR, RESULTS_PATH, FAISS_INDEX_PATH, FINAL_DATASET_PATH',
    '',
    'if str(T2SQL_DIR) not in sys.path:',
    ' sys.path.insert(0, str(T2SQL_DIR))',
    '',
    'import agent as t2_agent',
    '',
    'RUN_DIR = BASE_DIR / "run"',
    'EVAL_INCORRECT_PATH = RUN_DIR / "datafile" / "output" / "eval_incorrect_ids.json"',
    '',
    '# domain_term_917ddc3719 sql_id domain_term_d631bee144（domain_term_413f067545）',
    'FOCUS_SQL_IDS = [',
    ' "sql_1",',
    ' "sql_2",',
    ' "sql_16",',
    ' "sql_50",',
    ' "sql_60",',
    ' "sql_65",',
    ' "sql_68",',
    ' "sql_73",',
    ' "sql_74",',
    ' "sql_78",',
    ' "sql_101",',
    ' "sql_92",',
    ' "sql_94",',
    ' "sql_111",',
    ' "sql_113",',
    ' "sql_116",',
    ' "sql_118",',
    ' "sql_119",',
    ']',
    '',
    '# "sql_16", "sql_50", "sql_60", "sql_65", "sql_68", "sql_73", "sql_74", "sql_101", "sql_113"',
    'def load_incorrect_ids() -> int:',
    ' """domain_term_0a843da3dc（domain_term_8aa56da804 eval_incorrect_ids.json）。',
    '',
    ' domain_term_f7b1c8ba16 incorrect_count domain_term_77a49f2c38；domain_term_dd625d50d7，domain_term_bcccf8b042 incorrect_ids domain_term_a5394989b6；',
    ' domain_term_5dba06c62c，domain_term_97b2c7fdd5 -1 domain_term_2cbb4ab39a。',
    ' """',
    ' if not EVAL_INCORRECT_PATH.exists():',
    ' print(f"[Loop] domain_term_123fddd5d1: {EVAL_INCORRECT_PATH}")',
    ' return -1',
    '',
    ' try:',
    ' with EVAL_INCORRECT_PATH.open("r", encoding="utf-8") as f:',
    ' data = json.load(f)',
    ' except Exception as e:',
    ' print(f"[Loop] domain_term_60469a59c6: {e}")',
    ' return -1',
    '',
    ' # domain_term_a36320ad4b incorrect_count',
    ' if isinstance(data, dict):',
    ' cnt = data.get("incorrect_count")',
    ' if isinstance(cnt, int):',
    ' return cnt',
    ' ids = data.get("incorrect_ids") or []',
    ' if isinstance(ids, list):',
    ' return len(ids)',
    '',
    ' # domain_term_af4cb90432',
    ' if isinstance(data, list):',
    ' return len(data)',
    '',
    ' return -1',
    '',
    '',
    'def load_incorrect_id_list() -> List[str]:',
    ' if not EVAL_INCORRECT_PATH.exists():',
    ' return []',
    ' try:',
    ' with EVAL_INCORRECT_PATH.open("r", encoding="utf-8") as f:',
    ' data = json.load(f)',
    ' except Exception:',
    ' return []',
    ' if isinstance(data, dict):',
    ' ids = data.get("incorrect_ids") or []',
    ' if isinstance(ids, list):',
    ' return [str(x) for x in ids if x]',
    ' if isinstance(data, list):',
    ' return [str(x) for x in data if x]',
    ' return []',
    '',
    '',
    'def load_dataset_ids() -> List[str]:',
    ' try:',
    ' tasks = t2_agent.load_final_tasks()',
    ' except Exception:',
    ' return []',
    ' ids: List[str] = []',
    ' for t in tasks:',
    ' sid = t.get("sql_id")',
    ' if isinstance(sid, str) and sid:',
    ' ids.append(sid)',
    ' return ids',
    '',
    '',
    'def run_agent_for_ids(target_ids: List[str]) -> None:',
    ' if not target_ids:',
    ' return',
    '',
    ' target_set = set(target_ids)',
    '',
    ' try:',
    ' all_tasks = t2_agent.load_final_tasks()',
    ' except Exception:',
    ' all_tasks = []',
    '',
    ' tasks = []',
    ' for task in all_tasks:',
    ' sid = task.get("sql_id")',
    ' if isinstance(sid, str) and sid in target_set:',
    ' tasks.append(task)',
    '',
    ' if not tasks:',
    ' print(f"[Loop] domain_term_bb84373016 sql_id: {sorted(target_set)}")',
    ' return',
    '',
    ' current_ids = sorted({str(t.get("sql_id")) for t in tasks})',
    ' print(f"[Loop] domain_term_8214e43d3d agent domain_term_fc35e59964 {len(current_ids)} domain_term_f7b2a6ee68 sql_id: {current_ids}")',
    '',
    ' schema_map = t2_agent.load_schema_map()',
    ' common_knowledge = t2_agent.load_common_knowledge()',
    ' gold_map = t2_agent.load_gold_map()',
    ' added_knowledge_map = t2_agent.load_added_knowledge_map()',
    ' verified_kb_map = t2_agent.load_verified_kb_map()',
    '',
    ' if not FAISS_INDEX_PATH.exists():',
    ' try:',
    ' import build_vector_db',
    '',
    ' build_vector_db.main()',
    ' except Exception as e:',
    ' print(f"[Loop] domain_term_73d10f8911 FAISS domain_term_4da4ce72a1: {e}")',
    ' t2_agent.t2sql_utils.load_faiss_index()',
    '',
    ' conn = t2_agent.t2sql_utils.connect_db()',
    '',
    ' results_map = {}',
    ' if RESULTS_PATH.exists():',
    ' try:',
    ' with RESULTS_PATH.open("r", encoding="utf-8") as f:',
    ' for line in f:',
    ' line = line.strip()',
    ' if not line:',
    ' continue',
    ' try:',
    ' obj = json.loads(line)',
    ' except Exception:',
    ' continue',
    ' sid = obj.get("sql_id")',
    ' if isinstance(sid, str) and sid and sid not in target_set:',
    ' results_map[sid] = obj',
    ' except Exception as e:',
    ' print(f"[Loop] domain_term_8c0531a01b agent domain_term_a88a5d5404，domain_term_bc81bb8f3a: {e}")',
    ' results_map = {}',
    '',
    ' try:',
    ' with RESULTS_PATH.open("w", encoding="utf-8") as out:',
    ' for task in tasks:',
    ' sid = str(task.get("sql_id"))',
    ' res = t2_agent.process_task(',
    ' conn,',
    ' task,',
    ' schema_map,',
    ' gold_map,',
    ' common_knowledge,',
    ' added_knowledge_map,',
    ' verified_kb_map,',
    ' )',
    ' results_map[sid] = res',
    '',
    ' for sid in sorted(results_map.keys()):',
    ' out.write(',
    ' json.dumps(',
    ' results_map[sid], ensure_ascii=False, default=t2_agent._json_default',
    ' )',
    ' + "\\n"',
    ' )',
    ' finally:',
    ' try:',
    ' conn.close()',
    ' except Exception:',
    ' pass',
    '',
    '',
    'def main(max_rounds: int = 20, sleep_seconds: float = 0.0) -> None:',
    ' """domain_term_e10c780291 pipeline，domain_term_188bd57ac3 max_rounds domain_term_0517c1f9e4。',
    '',
    ' - domain_term_13649d6d01 pipeline_runner.main()（Agent domain_term_4aa2306395 -> domain_term_28febba225 SQL -> domain_term_04503f0a0a -> domain_term_43758bb163）。',
    ' - domain_term_69abe58a84 eval_incorrect_ids.json，domain_term_8dc76cebb0 incorrect_count domain_term_b7a385ec00 0，domain_term_fb07e5e82b。',
    ' - domain_term_3ee16341d4，domain_term_6a1dd5422f sleep domain_term_581b368b0c。',
    ' """',
    ' print("================ Pipeline Loop Runner domain_term_79cc871ca9 ================")',
    ' print(f"[Loop] domain_term_d28b7ea4ed: {max_rounds}")',
    '',
    ' dataset_ids = load_dataset_ids()',
    ' if not dataset_ids:',
    ' print("[Loop] domain_term_05475ea4a5 sql_id，domain_term_76b9880829。")',
    ' return',
    ' print(f"[Loop] domain_term_4290088121 {len(dataset_ids)} domain_term_f7b2a6ee68 sql_id: {dataset_ids}")',
    '',
    ' # domain_term_e7d63642b4，domain_term_f5a1f1a3c7 sql_id domain_term_28443116ed',
    ' focus_set = set(FOCUS_SQL_IDS) if FOCUS_SQL_IDS else set()',
    ' if focus_set:',
    ' dataset_ids = [sid for sid in dataset_ids if sid in focus_set]',
    ' print(f"[Loop] domain_term_49c50382eb {len(dataset_ids)} domain_term_f7b2a6ee68 sql_id domain_term_b6e0919ebe: {dataset_ids}")',
    ' if not dataset_ids:',
    ' print("[Loop] domain_term_963ba461e0 FOCUS_SQL_IDS domain_term_84cbbe428f，domain_term_76b9880829。")',
    ' return',
    '',
    ' for round_idx in range(1, max_rounds + 1):',
    ' print("\\n" + "=" * 30)',
    ' print(f"[Loop] domain_term_a8a20dc12f {round_idx} domain_term_f8880e7f2c Pipeline domain_term_0c3acd446f")',
    ' print("=" * 30)',
    '',
    ' if round_idx == 1:',
    ' target_ids = dataset_ids',
    ' else:',
    ' incorrect_all = load_incorrect_id_list()',
    ' if not incorrect_all:',
    ' print("[Loop] domain_term_96fe90e78a eval_incorrect_ids.json domain_term_084a231f23，domain_term_9b70294ebe。")',
    ' break',
    ' dataset_set = set(dataset_ids)',
    ' target_ids = [sid for sid in incorrect_all if sid in dataset_set]',
    ' if not target_ids:',
    ' print("[Loop] domain_term_f91baa3b24，domain_term_9b70294ebe。")',
    ' break',
    '',
    ' print(f"[Loop] domain_term_0f56cc7b50 sql_id: {target_ids}")',
    '',
    ' run_agent_for_ids(target_ids)',
    '',
    ' if not step2_prepare_sql_exe_input():',
    ' print("[Loop] domain_term_063cf9cb0e sql_exe domain_term_e8850440f2，domain_term_9b70294ebe。")',
    ' break',
    '',
    ' step3_run_sql_exe()',
    ' step4_run_evaluation()',
    ' step5_build_knowledge()',
    '',
    ' # domain_term_0e02aca337，domain_term_c8432c5324',
    ' incorrect_all = load_incorrect_id_list()',
    ' if not incorrect_all:',
    ' print("[Loop] domain_term_e6b3e53ebd eval_incorrect_ids.json domain_term_9c75092ab8。")',
    ' else:',
    ' print(',
    ' f"[Loop] domain_term_a040ab8dd0: {len(incorrect_all)}, IDs: {incorrect_all}"',
    ' )',
    '',
    ' focus_set = set(dataset_ids)',
    ' focus_incorrect = [sid for sid in incorrect_all if sid in focus_set]',
    ' print(',
    ' f"[Loop] domain_term_7c8b101ea4: {len(focus_incorrect)}, IDs: {focus_incorrect}"',
    ' )',
    '',
    ' if not focus_incorrect:',
    ' print(',
    ' f"[Loop] domain_term_53fe6726e2 sql_id domain_term_aa3feeb1e3，domain_term_9b1f4e560a {round_idx} domain_term_68618ecfb5。"',
    ' )',
    ' break',
    '',
    ' if round_idx < max_rounds and sleep_seconds > 0:',
    ' print(f"[Loop] domain_term_25d23b92b2 {sleep_seconds} domain_term_b821dbd88b...")',
    ' time.sleep(sleep_seconds)',
    '',
    ' print("================ Pipeline Loop Runner domain_term_76b9880829 ================")',
    '',
    '',
    'if __name__ == "__main__":',
    ' main()',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
