# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `2.pipeline/config.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    'import os',
    'from pathlib import Path',
    '',
    '# T2SQL_DIR domain_term_9c7565ba38 t2sql-backup domain_term_18755acbbb（domain_term_f896fb3776 run/、model/ domain_term_3dff4d1479）',
    'BASE_DIR = Path(__file__).resolve().parents[2]',
    'T2SQL_DIR = BASE_DIR',
    'DATA_DIR = BASE_DIR / "data"',
    'INDEX_DIR = BASE_DIR / "run" / "indexes"',
    'LOGS_DIR = BASE_DIR / "logs"',
    'RESULTS_PATH = BASE_DIR / "run" / "datafile" / "output" / "results-finalize111.jsonl"',
    'RESUME_FROM_EXISTING_RESULTS = True',
    '',
    'GOLD_SQL_PATH = DATA_DIR / "goldsql.json"',
    '#FINAL_DATASET_PATH = DATA_DIR / "final_dataset.json"D:\\Desktop\\domain_term_bc29091d1b\\domain_term_95517a6370\\domain_term_d4b4f08c89\\data\\correct_52_sorted.json',
    '#FINAL_DATASET_PATH = DATA_DIR / "correct_52_sorted.json"',
    'FINAL_DATASET_PATH = DATA_DIR / "final_dataset.json"',
    '#FINAL_DATASET_PATH = DATA_DIR / "sql_3.json"',
    '#D:\\Desktop\\domain_term_bc29091d1b\\domain_term_95517a6370\\domain_term_d4b4f08c89\\data\\',
    'SCHEMA_PATH = DATA_DIR / "schema_all_gemini.json"',
    'COMMON_KNOWLEDGE_PATH = DATA_DIR / "common_knowledge2.md"',
    'STARROCK_KNOWLEDGE_PATH = DATA_DIR / "starrock_knowledge.md"',
    'ADDED_KNOWLEDGE_LIST_PATH = DATA_DIR / "knowledge_add_clean_list.json"',
    'VERIFIED_KB_PATH = BASE_DIR / "data_detective_knowledge" / "correct_verified_knowledge.json"',
    'DETECTIVE_VERIFIED_KB_PATH = BASE_DIR / "data_detective_knowledge" / "verified_knowledge_base_run.json"',
    '',
    'FAISS_INDEX_PATH = INDEX_DIR / "few_shot.faiss"',
    'FAISS_META_PATH = INDEX_DIR / "few_shot_meta.json"',
    '',
    'OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "9933dfbc-e184-4381-ad8d-bf806760fee")',
    'if os.getenv("LLM_PROVIDER", "gemini").lower() == "openai" and not OPENAI_API_KEY:',
    ' raise ValueError("domain_term_267c6a8c00 OPENAI_API_KEY domain_term_8da07705ab，domain_term_d334c1d208 Ark API Key")',
    'OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://ark.cn-beijing.volces.com/api/v3/")',
    'OPENAI_MODEL = os.getenv("OPENAI_MODEL", "doubao-seed-1-6-251015")',
    'OPENAI_MODEL_CORRECT = os.getenv("OPENAI_MODEL_CORRECT", OPENAI_MODEL)',
    '',
    'GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "sk-Ak2Oj84wzYK6ogzOFzwQe1MaMB5S8YZcfE5Dc1myOiFnSu2p")',
    'GEMINI_BASE_URL = os.getenv("GEMINI_BASE_URL", "https://api.gemai.cc/v1")',
    '#GEMINI_BASE_URL = os.getenv("GEMINI_BASE_URL", "https://gemini-api.poenl.top/v1beta/openai/")',
    '#GEMINI_MODEL = os.getenv("GEMINI_MODEL", "[domain_term_a5b4136649E]gemini-3-pro-preview")',
    'GEMINI_MODEL = os.getenv("GEMINI_MODEL", "[domain_term_d3ae19a351]gpt-5.2")',
    'LLM_PROVIDER = os.getenv("LLM_PROVIDER", "gemini")',
    'GEMINI_API_KEYS = [',
    '',
    '',
    '',
    '',
    '"sk-Df0wN0qG152tkEsQcZl7cvlDfABhduXRAqz56psfgFSDJUAw",',
    '"sk-PQMw3zdBJP4nPS5MlnkRKd4ffbTfsf2bpvfbvgGLNtguPxSu",',
    '"sk-TBi8eXBX4cQFPwZBKkS7sGEOjDT6jPQYT1H6TRTFf3f9aVBr",',
    '"sk-NZ5Ifpvq6evbfufBbGPw7F9MU1BKDrfrlmq1mLxMeV3vm18Z",',
    '"sk-mo0n7r8YYqLQsw4pse3rHYfkHOR69JQXjLHTTTp7sp27d3KZ",',
    '"sk-tPasTEeyALViTF8tB0ltRdAWahPDaoq38hjnsbxILZC1WHtC",',
    '"sk-WiT4hZRqU1bFJy0zKqCSFU2016lt731Bv5ROTblVjgwGONkC",',
    '"sk-KJJ4pyGXCLIUphXaSpyw7j4zym63XRljz5f9eZszIisBdvW0",',
    '"sk-AeZpiEInZ0cZb3HcoMXjRgQFTLUBfKcxaULcst2CoV93T1U1",',
    '"sk-L1fxbt6JGHzDnOLV3ZjpdFFo9LeRRVW6YXs0OsGu7EPL7d7P",',
    '"sk-MgPOXehN0jXP5egrywsEwGYJ0RzhdxOtAmcX4rDNcPfZKmyi",',
    '"sk-6AXUeodM3wmGAHeSkL3xlC9b1hnfEua4ttqSVHZfIX22MSMn",',
    '"sk-6ISWBFtGGQto15k5vtZd4HeRJoghGZu1XjrefYZFYAjR08DG",',
    '"sk-DqrE3LxacoCLXdFGa5OzCsV6tRHZ9zbwcVQLHKnCpetf6wss",',
    '"sk-GiXV9zv9156D9M5um4eQhnuRkpELiF5aNnRoDldUxVYJWSrf",',
    '"sk-6ISWBFtGGQto15k5vtZd4HeRJoghGZu1XjrefYZFYAjR08DG",',
    '"sk-DqrE3LxacoCLXdFGa5OzCsV6tRHZ9zbwcVQLHKnCpetf6wss",',
    '"sk-GiXV9zv9156D9M5um4eQhnuRkpELiF5aNnRoDldUxVYJWSrf",',
    '"sk-AeZpiEInZ0cZb3HcoMXjRgQFTLUBfKcxaULcst2CoV93T1U1",',
    '"sk-L1fxbt6JGHzDnOLV3ZjpdFFo9LeRRVW6YXs0OsGu7EPL7d7P",',
    '"sk-MgPOXehN0jXP5egrywsEwGYJ0RzhdxOtAmcX4rDNcPfZKmyi",',
    '"sk-6AXUeodM3wmGAHeSkL3xlC9b1hnfEua4ttqSVHZfIX22MSMn",',
    '',
    '',
    '"sk-RfsrMTNAeoEnjBuFVke7eQiWkyy6J6NyW5OivdAsU680hcsa",',
    '"sk-HRXxrtrcI1hDC1n5pwuLboFXiwlAXHeHWbFtEoM98RmhUeZv",',
    '"sk-0WxcqVlHqX2k9aF3i165qxQqm5YyIxQcz3BGPfCmgV1lB7A5",',
    '"sk-EIaC1qVK1lJ9NWb6uKbUMWyaFrvwLn4Zxfs1VgvF4xmsu7xg",',
    '"sk-egGvVtt3yaMJPfuwMzSEAmZB2C2yQDb8HiY87upC6qey8HUA",',
    '"sk-awzEBo1nsFMx1qnKPGdAiY0ymrY9lu4WJ1xvCik2JhXOROSm",',
    '"sk-Gqu8HlXFoNRNVgRbVqktN8l80Ibx12TrMmUvipWZKjacbGTg",',
    '"sk-rAAono7vPidosEHfwff0rmTDejnw4PgS2Kiy9u8DFpDPIt3Q",',
    '"sk-aYebVXHoMTSxIkeWEap4MMuX7D39sP54heu77WqgoYNLOp11",',
    '',
    '"sk-VccjUF2WapsvgfiyOjtvFG8NlATwtl6YSteNaMXnvS1k3tDX",',
    '',
    '"sk-ovPWG4f60Ar8oL8mdAlWRCnXjFemtONK7qHFMJgJiTkUgcpX",',
    '"sk-Rb1rjDHLHV64ftkYF01VflU79vMx4A5KuTag95yU0KOtfPVT",',
    '"sk-gY0jg731aoY3ETY65qml4z3bWJvBvfUfSq8RHrXyp0IZVIUl",',
    '"sk-LZEI1TMOLFCJZGbpXP2gNWD5GqpZ11wp5lBoA1izbj9nS5Ac",',
    '',
    '',
    '"sk-yvewRubNuU8ZSEynK74HOf8WEWwM2Sqbqinda1tTCEFsTOaP",',
    '"sk-h3FWUi1kQyGT7Wl8Ph52PjWzr2kQ2ViJWaTTqHAvTMFMzojo",',
    '"sk-vXOaWB7ZAxS4xO0V74bW9ffQTHeisQN6OY8g0skibPY2fAK0",',
    '"sk-PqYqodYEeffz0e6FiEbgAuP84k7xTTG5rqTBCL6PCZKueZ3Q",',
    '',
    '"sk-N93Q6DRpunX9djY6cUIQQLDH1BLCAQhpbwkSPGi5r8vufk0P",',
    ']',
    'if GEMINI_API_KEYS:',
    '',
    ' GEMINI_API_KEY = GEMINI_API_KEYS[0]',
    'GEMINI_API_KEY_LIST = GEMINI_API_KEYS',
    '',
    '# (domain_term_4620913232，domain_term_0e2d3a3c09 BGE domain_term_855241c285 OpenAI embedding)',
    '# 【domain_term_c920e429e2】domain_term_f3a90438d8',
    'EMBEDDING_MODEL_NAME = str(BASE_DIR / "t2sql-backup" / "model" / "bge-large-zh-v1.5")',
    '',
    'FEWSHOT_TOP_K = int(os.getenv("FEWSHOT_TOP_K", "3"))',
    'SIM_THRESHOLD = float(os.getenv("SIM_THRESHOLD", "0.5"))',
    'TOP1_STRICT_THRESHOLD = float(os.getenv("TOP1_STRICT_THRESHOLD", "0.6"))',
    '',
    'DB_HOST = os.getenv("SR_HOST", "172.22.194.247")',
    'DB_PORT = int(os.getenv("SR_PORT", "9030"))',
    'DB_USER = os.getenv("SR_USER", "root")',
    'DB_PASSWORD = os.getenv("SR_PASSWORD", "")',
    'DB_DATABASE = os.getenv("SR_DATABASE", "final_algorithm_competition")',
    'DB_CONNECT_TIMEOUT = int(os.getenv("SR_CONNECT_TIMEOUT", "10"))',
    'DB_READ_TIMEOUT = int(os.getenv("SR_READ_TIMEOUT", "30"))',
    'DB_WRITE_TIMEOUT = int(os.getenv("SR_WRITE_TIMEOUT", "30"))',
    '',
    'RANDOM_SEED = int(os.getenv("RANDOM_SEED", "42"))',
    '',
    '# --- domain_term_229941e8e5 (domain_term_16593aa84d sql_exe.py) ---',
    'DB_CONFIG = {',
    " 'host': '172.22.194.247',",
    " 'user': 'root',",
    " 'password': '', # domain_term_6fa886d246",
    " 'db': 'final_algorithm_competition',",
    " 'port': 9030",
    '}',
    '',
    '# --- domain_term_4ca39faad0 2 domain_term_9132e087f1 (domain_term_2bb6b96feb) ---',
    '# domain_term_21dd0e5ebc LOGS_DIR domain_term_8c640ebcc9',
    'LOGS_DIR = T2SQL_DIR / "logs"',
    '',
    '# domain_term_4ca39faad0 1 domain_term_1e2dc87b02 (domain_term_278c830586)',
    'GENERATION_RESULTS_PATH = T2SQL_DIR / "run" / "datafile" / "output" / "results (19).jsonl"',
    '',
    '# domain_term_4ca39faad0 2 domain_term_1e2dc87b02 (domain_term_6b7bb0306a)',
    'INTERMEDIATE_RESULTS_PATH = T2SQL_DIR / "run" / "datafile" / "output" / "intermediate_results.json"',
    'FIX_INPUT_PATH = T2SQL_DIR / "run" / "datafile" / "output" / "fix_input.jsonl"',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
