# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `2.pipeline/prompts.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    'from typing import List, Dict, Any, Tuple',
    'import json',
    '',
    '# --- SQL domain_term_9578f7b170 ---',
    '',
    'STARROCKS_SYNTAX_RULES = """',
    '### Strict StarRocks SQL Dialect Rules:',
    '1. **Date/Time**:',
    " - Parsing: Use `str_to_date(col, '%Y%m%d')`. ❌ NO `to_date(col, fmt)`.",
    ' - Calc: Use `date_add(col, INTERVAL n DAY)`. ❌ NO `date + n`.',
    '2. **Casting & Quotes**:',
    ' - Use `CAST(val AS TYPE)`. ❌ NO `val::type` (PG syntax).',
    ' - Use single quotes `\'val\'`. ❌ NO double quotes `"val"`.',
    '3. **Hive/Spark Forbidden**:',
    ' - ❌ NO `LATERAL VIEW explode`, `posexplode`, `split(space())`.',
    ' - ❌ NO `collect_set`/`collect_list` (Use `group_concat`/`array_agg`).',
    '4. **Functions**:',
    ' - Use `split_part(str, sep, index)` where index starts at 1.',
    '5. **Logic**:',
    ' - Avoid `WITH RECURSIVE`.',
    ' - GROUP BY original expressions, not aliases.',
    '"""',
    '',
    'SQL_SELF_CHECKLIST = """',
    '### Self-Correction Checklist (domain_term_71fd159461 SQL domain_term_cdc61e2b1d):',
    '- [ ] domain_term_657599e71d Schema domain_term_2266517602。',
    '- [ ] domain_term_3dfaa2125d GROUP BY domain_term_08b5842ab1 SELECT domain_term_ad3ee64830（domain_term_dfac619b92）。',
    '- [ ] domain_term_70d01d6355《Strict StarRocks SQL Dialect Rules》domain_term_01988df37e（domain_term_1c6f2dc4cc、CAST、domain_term_b1b64f6567、domain_term_57a3aa2799 Hive/Spark domain_term_b3e49bded6）。',
    '- [ ] domain_term_c8bb86a87e（domain_term_8c6715c343，domain_term_1bb26500bb）。',
    '- [ ] domain_term_40ffb34860 WHERE / JOIN domain_term_055938045d，domain_term_7ec8913255。',
    '"""',
    '',
    '# 1. domain_term_f282cf6f27 System Prompt (domain_term_975beacd5a、domain_term_74aea8d5b9，domain_term_b191c8c4f5)',
    'SYSTEM_PROMPT_STANDARD = f"""',
    'domain_term_802c089727 Text-to-SQL domain_term_73ca2e3a45。domain_term_83198677e2、domain_term_900b7b99d7，domain_term_572ff3c9b2 100% domain_term_f474a03fe0 StarRocks SQL domain_term_711363c424。',
    '',
    'domain_term_109d36cef1：',
    '1. domain_term_66ec6be1f4（domain_term_2395910f1b），domain_term_d68d8d1a0c JSON。',
    '2. domain_term_3390a99e34 SQL，domain_term_81aabfe451 Markdown domain_term_7c71a1adab，domain_term_b426131d3f：',
    '',
    '```sql',
    '-- domain_term_78d9384ea1 StarRocks SQL',
    'SELECT ...',
    '```',
    '',
    '3. domain_term_67da22d8e5 SQL domain_term_4a0d7dd6bd，domain_term_bafc5acfa7、JSON domain_term_06c72c160a。',
    '',
    '{STARROCKS_SYNTAX_RULES}',
    '',
    '{SQL_SELF_CHECKLIST}',
    '"""',
    '',
    '# 2. domain_term_d972cca9b7 (Ali-CoT)，domain_term_f01b70b9fa/domain_term_5ae3ded301',
    'SYSTEM_PROMPT_ALI_COT = f"""',
    'domain_term_802c089727 Text-to-SQL domain_term_73ca2e3a45。',
    'domain_term_2ec817ce08 **Chain-of-Thought** domain_term_f3c49831c6，domain_term_a2ce1d1a5d，domain_term_a71095424a SQL。',
    '',
    'domain_term_477f088b57：',
    '1. **Reasoning**: domain_term_53d1bc3456。',
    '2. **Columns**: domain_term_909ec53792。',
    '3. **Filters**: domain_term_4a938b7481 WHERE / HAVING domain_term_5f049aff90。',
    '4. **SQL**: domain_term_a9d6ef8d9a SQL，domain_term_b8cade7610 ```sql ... ``` domain_term_7c71a1adab，domain_term_67da22d8e5 SQL。',
    '',
    'domain_term_4aa2306395 SQL domain_term_1c85f43552 StarRocks domain_term_a829fb9187：',
    '',
    '{STARROCKS_SYNTAX_RULES}',
    '',
    '{SQL_SELF_CHECKLIST}',
    '"""',
    '',
    '# domain_term_7752347614：cot domain_term_85b712cb36 ali_cot domain_term_a900957405',
    'SYSTEM_PROMPT_COT = SYSTEM_PROMPT_ALI_COT',
    '',
    '# 3. domain_term_890434606d (Divide & Conquer)，domain_term_645af7e6b3',
    'SYSTEM_PROMPT_DIVIDE = f"""',
    'domain_term_802c089727 Text-to-SQL domain_term_73ca2e3a45。',
    'domain_term_b1ab788d6b，domain_term_2ec817ce08 **Divide and Conquer (domain_term_890434606d)** domain_term_f3c49831c6。',
    'domain_term_58738d3d0a (Sub-questions)，domain_term_8139a36700 (Sub-SQL)，domain_term_8ac8906d0a SQL。',
    '',
    '**domain_term_84c3c1e08f：**',
    '1. **Main Question**: domain_term_00f0807691。',
    '2. **Sub-question 1**: domain_term_dc98a5418a（domain_term_46930b1ccf：domain_term_301952f84d）。',
    ' - **Pseudo SQL**: domain_term_15aac25c68。',
    '3. **Sub-question 2**: domain_term_d86e07e5f0（domain_term_46930b1ccf：domain_term_dfae61aa84）。',
    '4. **Assembly**: domain_term_2f057f772f JOIN domain_term_30f4d7cfe8 IN domain_term_09fd05f623。',
    '',
    '**domain_term_de9468a63c：**',
    '- domain_term_ade31f1651；',
    '- domain_term_a58c1246a1 SQL，domain_term_b8cade7610 ```sql ... ``` domain_term_7c71a1adab，domain_term_67da22d8e5 SQL。',
    '',
    'domain_term_4aa2306395 SQL domain_term_1c85f43552 StarRocks domain_term_a829fb9187：',
    '',
    '{STARROCKS_SYNTAX_RULES}',
    '',
    '{SQL_SELF_CHECKLIST}',
    '"""',
    '',
    '# 4. domain_term_42d270fe69 (Query Plan)，domain_term_912041fac4 Join domain_term_9132e087f1',
    'SYSTEM_PROMPT_PLAN = f"""',
    'domain_term_802c089727 Text-to-SQL domain_term_73ca2e3a45。',
    'domain_term_f0dff5c97a SQL domain_term_b80b52748f，domain_term_d761038be5，domain_term_e997d26e8e **Query Plan (domain_term_42d270fe69)**。',
    '',
    '**domain_term_8d44f01f26：**',
    '1. **Preparation**: domain_term_b8687a2f95 (Location, Info...)。',
    '2. **Matching**: domain_term_5cd7332028 (Scan Table -> Filter Condition)。',
    '3. **Linking**: domain_term_95acc3dba3 (Join Path, Foreign Keys)，domain_term_d9d65bc580。',
    '4. **Delivering**: domain_term_dc0aa67058。',
    '',
    '**domain_term_de9468a63c：**',
    '- domain_term_f9e5b583af Query Plan domain_term_412f54dc38；',
    '- domain_term_a58c1246a1 SQL，domain_term_b8cade7610 ```sql ... ``` domain_term_7c71a1adab，domain_term_67da22d8e5 SQL。',
    '',
    'domain_term_4aa2306395 SQL domain_term_1c85f43552 StarRocks domain_term_a829fb9187：',
    '',
    '{STARROCKS_SYNTAX_RULES}',
    '',
    '{SQL_SELF_CHECKLIST}',
    '"""',
    '',
    '# domain_term_ffa1385bc1（domain_term_6802dfbbef）',
    'SQL_GEN_SYSTEM = SYSTEM_PROMPT_STANDARD',
    '',
    'SQL_FIX_SYSTEM = f"""',
    'domain_term_141137cac6 SQL domain_term_7317708db7。domain_term_6843fa53e3 StarRocks SQL domain_term_711363c424。',
    'domain_term_78f39e380b domain_term_034ad7d208 SQL domain_term_9a3eb34097 domain_term_22a69618b0 StarRocks domain_term_f15cc801a4 domain_term_a38a81c9d5。',
    'domain_term_f8e1956e45，domain_term_e8ae2010ad SQL。',
    '',
    'domain_term_109d36cef1：',
    '1. domain_term_d2827134ea（domain_term_49371c7e7d JSON）。',
    '2. domain_term_0b32e8d622 SQL，domain_term_96fc665a25 ```sql ... ``` domain_term_7c71a1adab，domain_term_67da22d8e5 SQL，domain_term_a51e91be2c JSON。',
    '',
    'domain_term_7017e7b6ff SQL domain_term_1c85f43552 StarRocks domain_term_a829fb9187：',
    '',
    '{STARROCKS_SYNTAX_RULES}',
    '',
    '{SQL_SELF_CHECKLIST}',
    '"""',
    '',
    '',
    'def format_schema_block(schema_tables: List[Dict[str, Any]]) -> str:',
    ' # domain_term_0daa53263a，domain_term_63fbfd8163，domain_term_eb41e655e3 potential_links domain_term_7d91111cc8',
    ' compact_tables = []',
    ' allowed_tables = {t.get("table_name") for t in schema_tables if t.get("table_name")}',
    ' def _filter_links_by_allowed(links):',
    ' try:',
    ' if isinstance(links, dict):',
    ' return {k: v for k, v in links.items() if k in allowed_tables}',
    ' if isinstance(links, list):',
    ' filtered_list = []',
    ' for item in links:',
    ' if isinstance(item, dict):',
    ' target = None',
    ' for k in ("table", "table_name", "target_table", "to_table", "ref_table", "target", "to", "ref", "foreign_table", "fk_table", "join_table", "dst_table"):',
    ' if k in item and isinstance(item[k], str):',
    ' target = item[k].split(".")[0]',
    ' break',
    ' if target is None:',
    ' filtered_list.append(item)',
    ' elif target in allowed_tables:',
    ' filtered_list.append(item)',
    ' elif isinstance(item, str):',
    ' target = item.split(".")[0]',
    ' if target in allowed_tables:',
    ' filtered_list.append(item)',
    ' else:',
    ' filtered_list.append(item)',
    ' return [x for x in filtered_list if x]',
    ' return links',
    ' except Exception:',
    ' return links',
    ' for t in schema_tables:',
    ' obj = {',
    ' "table_name": t.get("table_name"),',
    ' "llm_table_long_description": t.get("llm_table_long_description"),',
    ' }',
    ' cols = []',
    ' for c in t.get("columns", []):',
    ' cc = {',
    ' "column_name": c.get("column_name"),',
    ' "column_type": c.get("column_type"),',
    ' "llm_long_description": c.get("llm_long_description"),',
    ' }',
    ' if "potential_links" in c:',
    ' _pl = _filter_links_by_allowed(c["potential_links"])',
    ' if _pl:',
    ' cc["potential_links"] = _pl',
    ' cols.append(cc)',
    ' obj["columns"] = cols',
    ' if "potential_links" in t:',
    ' _tpl = _filter_links_by_allowed(t["potential_links"])',
    ' if _tpl:',
    ' obj["potential_links"] = _tpl',
    ' compact_tables.append(obj)',
    ' return json.dumps(compact_tables, ensure_ascii=False, indent=2)',
    '',
    '',
    'def format_few_shots(pairs: List[Tuple[str, str]]) -> str:',
    ' blocks = []',
    ' for q, s in pairs:',
    ' blocks.append(f"[Q]: {q}\\n[SQL]:\\n{s}")',
    ' return "\\n\\n" + ("\\n\\n".join(blocks)) if blocks else ""',
    '',
    '',
    'def build_sql_generation_messages(',
    ' schema_tables: List[Dict[str, Any]],',
    ' knowledge_text: str,',
    ' few_shots: List[Tuple[str, str]],',
    ' question: str,',
    ' strategy: str = "standard",',
    '):',
    ' schema_block = format_schema_block(schema_tables)',
    ' fs_block = format_few_shots(few_shots)',
    '',
    ' # domain_term_84e7800ced System Prompt',
    ' if strategy == "divide":',
    ' sys_content = SYSTEM_PROMPT_DIVIDE',
    ' suffix = "domain_term_9bbc0f9397 **Divide and Conquer** domain_term_9c00c951b8："',
    ' elif strategy == "plan":',
    ' sys_content = SYSTEM_PROMPT_PLAN',
    ' suffix = "domain_term_718b571006 **Query Plan**："',
    ' elif strategy in ("ali_cot", "cot"):',
    ' sys_content = SYSTEM_PROMPT_ALI_COT',
    ' suffix = "domain_term_9dc453877f Schema domain_term_9a3eb34097 Values："',
    ' else:',
    ' sys_content = SYSTEM_PROMPT_STANDARD',
    ' suffix = "[SQL]:\\n"',
    '',
    ' user_content = (',
    ' "[domain_term_ad26311a1c (Schema)]\\n---\\n"',
    ' f"{schema_block}\\n\\n"',
    ' "[domain_term_1dda51f9e3 (Knowledge)]\\n---\\n"',
    ' f"{knowledge_text}\\n\\n"',
    ' "[domain_term_58a38b2ab2 (Few-shot Examples)]\\n---\\n"',
    ' f"{fs_block}\\n\\n"',
    ' "[domain_term_403a76b1ba]\\n"',
    ' f"[Q]: {question}\\n"',
    ' f"{suffix}"',
    ' )',
    ' return [',
    ' {"role": "system", "content": sys_content},',
    ' {"role": "user", "content": user_content},',
    ' ]',
    '',
    '',
    'def build_sql_fix_messages(sql_candidate: str, error_message: str, knowledge_text: str = ""):',
    ' kb = ("\\n\\n[domain_term_1dda51f9e3 (Knowledge)]\\n---\\n" + knowledge_text + "\\n") if knowledge_text else "\\n"',
    ' user_content = (',
    ' "[domain_term_034ad7d208 SQL]\\n"',
    ' f"{sql_candidate}\\n\\n"',
    ' "[StarRocks domain_term_a38a81c9d5]\\n"',
    ' f"{error_message}" + kb +',
    ' "[domain_term_cb5ca6439b SQL]\\n"',
    ' )',
    ' return [',
    ' {"role": "system", "content": SQL_FIX_SYSTEM},',
    ' {"role": "user", "content": user_content},',
    ' ]',
    '',
    '',
    '# domain_term_dd97fe060f (Few-shot)',
    'CORRECTION_FEW_SHOTS: Dict[str, str] = {',
    ' # 1. domain_term_b3e49bded6/domain_term_f69fa6f319 (domain_term_232db30568)',
    ' "SyntaxError": """',
    '/* Example of Fixing Syntax or Column Error */',
    '#Question: domain_term_ca8ffc39902024domain_term_bf50c953d0',
    "#Error SQL: SELECT count(*) FROM dws_login WHERE active_date = '2024'",
    "#Error Message: Unknown column 'active_date' in 'where clause'",
    "#Reasoning: The error indicates 'active_date' does not exist. I checked the [Database Schema] and found the correct column is 'dtstatdate'. Also, the format '2024' implies a yearly filter, but the column is yyyymmdd.",
    "#Fixed SQL: SELECT count(*) FROM dws_login WHERE substr(dtstatdate, 1, 4) = '2024'",
    '""",',
    '',
    ' # 2. domain_term_fca0565c04 (domain_term_466c15f561 ID domain_term_3f5492a981)',
    ' "EmptyResult": """',
    '/* Example of Fixing Empty Result */',
    '#Question: domain_term_ca8ffc3990“domain_term_ea8f75edd0”domain_term_0ce1e7b289',
    "#Error SQL: SELECT count(*) FROM dws_round WHERE modename = 'domain_term_ea8f75edd0'",
    '#Error Message: Execution succeeded but returned 0 rows.',
    '#Reasoning: The query returned no data. I checked the [Knowledge] again. It says "domain_term_ea8f75edd0" refers to `modename=\'domain_term_8a6c6ccf17\' AND submodename LIKE \'%domain_term_100fc8d11e%\'`. The previous SQL used the natural language name directly, which was wrong.',
    "#Fixed SQL: SELECT count(*) FROM dws_round WHERE modename='domain_term_8a6c6ccf17' AND submodename LIKE '%domain_term_100fc8d11e%'",
    '""",',
    '',
    ' # 3. domain_term_ac91a75247 (domain_term_509b359ee1)',
    ' "LogicTrap": """',
    '/* Example of Fixing Logic Trap */',
    '#Question: domain_term_6fe5c91f22721domain_term_5e6938d88f',
    "#Error SQL: SELECT * FROM dws_login a JOIN dim_package b ON a.id = b.id WHERE b.pkg = '721'",
    '#Error Message: Execution succeeded but returned 0 rows (or result is wrong).',
    '#Reasoning: The [Knowledge] explicitly says "Do NOT join dim_package". I should use a direct filter or NOT IN logic instead of an INNER JOIN which might filter out valid data.',
    "#Fixed SQL: SELECT * FROM dws_login WHERE id IN ('pkg7', 'pkg2', 'pkg1')",
    '""",',
    '}',
    '',
    '',
    'def build_sql_fix_messages_super(',
    ' schema_tables: List[Dict[str, Any]],',
    ' knowledge_text: str,',
    ' question: str,',
    ' wrong_sql: str,',
    ' error_msg: str,',
    '):',
    ' """',
    ' Super Correction Prompt: domain_term_93d4786288 Knowledge domain_term_9a3eb34097 Schema domain_term_3633a015f9',
    ' """',
    ' error_type = "General"',
    ' lower_msg = str(error_msg).lower()',
    '',
    ' if ("unknown column" in lower_msg) or ("doesn\'t exist" in lower_msg) or ("syntax" in lower_msg):',
    ' error_type = "SyntaxError"',
    ' elif ("returned 0 rows" in lower_msg) or ("empty" in lower_msg):',
    ' error_type = "EmptyResult"',
    ' elif ("join" in wrong_sql.lower()) and ("dim_" in wrong_sql.lower()):',
    ' error_type = "LogicTrap"',
    '',
    ' correction_example = CORRECTION_FEW_SHOTS.get(error_type, CORRECTION_FEW_SHOTS["EmptyResult"])',
    '',
    ' system_content = (',
    ' "You are a **SQL Debugging Expert** for StarRocks.\\n"',
    ' "Your task is to fix the Error SQL based on the Error Message, Schema, and Domain Knowledge.\\n\\n"',
    ' "**DEBUGGING STRATEGY:**\\n"',
    ' "1. **Check Schema**: If the error is \\"Unknown column\\", find the similar valid column in Schema.\\n"',
    ' "2. **Check Knowledge**: If the error is \\"0 rows returned\\", check if you missed a filter condition defined in [Knowledge] or used a wrong string literal.\\n"',
    ' "3. **Check Logic**: Avoid INNER JOIN that filters out rows; consider LEFT JOIN/EXISTS/IN when appropriate.\\n\\n"',
    ' "**OUTPUT FORMAT (VERY IMPORTANT):**\\n"',
    ' "- First, you MAY provide a short natural-language explanation of the root cause (do NOT output JSON).\\n"',
    ' "- Then, you MUST output the corrected SQL wrapped in a single ```sql ... ``` code block. The code block MUST contain only valid StarRocks SQL, no comments, no JSON, no extra text.\\n\\n"',
    ' f"{STARROCKS_SYNTAX_RULES}\\n\\n"',
    ' f"{SQL_SELF_CHECKLIST}\\n"',
    ' )',
    '',
    ' user_content = (',
    ' "[Database Schema] (Reference for Column Names)\\n"',
    ' f"{json.dumps(schema_tables, indent=2, ensure_ascii=False)}\\n\\n"',
    ' "[Domain Knowledge] (CRITICAL: Check mappings here)\\n"',
    ' f"{knowledge_text}\\n\\n"',
    ' "[Correction Example] (How to fix similar errors)\\n"',
    ' f"{correction_example}\\n\\n"',
    ' "-----------------------------------------\\n"',
    ' "[Current Task]\\n"',
    ' "#Question: \\n"',
    ' f"{question}\\n\\n"',
    ' "#Error SQL: \\n"',
    ' f"{wrong_sql}\\n\\n"',
    ' "#Error Message: \\n"',
    ' f"{error_msg}\\n\\n"',
    ' "Please provide the fixed SQL.\\n"',
    ' )',
    ' return [',
    ' {"role": "system", "content": system_content},',
    ' {"role": "user", "content": user_content},',
    ' ]',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
