# -*- coding: utf-8 -*-
"""
Academic English archival wrapper for `2.pipeline/utils.py`.

This module preserves the English-normalized source text line by line.
It is intended for scholarly review and repository publication; the
original computational behavior is not guaranteed after translation.
"""

from __future__ import annotations

TRANSLATED_SOURCE_LINES = [
    'import json',
    'import os',
    'import re',
    'import unicodedata',
    'import random',
    'from pathlib import Path',
    'from typing import List, Tuple, Dict, Any',
    '',
    'import numpy as np',
    'import faiss',
    'from sentence_transformers import SentenceTransformer',
    'import pymysql',
    'import shutil',
    '',
    'from config import (',
    ' INDEX_DIR,',
    ' FAISS_INDEX_PATH,',
    ' FAISS_META_PATH,',
    ' EMBEDDING_MODEL_NAME,',
    ' DB_HOST,',
    ' DB_PORT,',
    ' DB_USER,',
    ' DB_PASSWORD,',
    ' DB_DATABASE,',
    ' DB_CONNECT_TIMEOUT,',
    ' DB_READ_TIMEOUT,',
    ' DB_WRITE_TIMEOUT,',
    ' LOGS_DIR,',
    ' RANDOM_SEED,',
    ')',
    '',
    '_model = None',
    '_index = None',
    '_meta = None',
    '_rng = random.Random(RANDOM_SEED)',
    '',
    'def ensure_dirs():',
    ' INDEX_DIR.mkdir(parents=True, exist_ok=True)',
    ' LOGS_DIR.mkdir(parents=True, exist_ok=True)',
    '',
    'def normalize_text(text: str) -> str:',
    ' if text is None:',
    ' return ""',
    ' text = unicodedata.normalize("NFKC", text)',
    ' text = text.replace("\\u3000", " ")',
    ' text = re.sub(r"\\s+", " ", text).strip()',
    ' text = text.lower()',
    ' return text',
    '',
    '_GUID_RE = re.compile(r"\\b[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}\\b", re.IGNORECASE)',
    '_DATE_SEP_RE = re.compile(r"(...<!\\d)\\d{4}([./-])\\d{1,2}\\1\\d{1,2}(...!\\d)")',
    '# 2️⃣ domain_term_c837edc2588domain_term_967b89cc09：20250702',
    '_DATE_8_RE = re.compile(r"(...<!\\d)\\d{8}(...!\\d)")',
    '# 3️⃣ domain_term_16fbc04723：2024domain_term_6f14c2641c5domain_term_d9b59879f302domain_term_15917f3b32、25domain_term_6f14c2641c4domain_term_d9b59879f3',
    '_DATE_CN_RE = re.compile(',
    ' r"(...<!\\d)(\\d{2,4})domain_term_6f14c2641c(\\d{1,2})domain_term_d9b59879f3(\\d{1,2}domain_term_15917f3b32)..."',
    ')',
    '# 4️⃣ domain_term_8b4d6e239b（domain_term_f896fb3776 “domain_term_792bbe6e08”、“-”、“~”、domain_term_febf7e8b82）',
    '_DATE_RANGE_RE = re.compile(',
    ' r"("',
    ' r"(...:(...:\\d{2,4}[./-]\\d{1,2}[./-]\\d{1,2})|(...:\\d{8})|(...:\\d{2,4}domain_term_6f14c2641c\\d{1,2}domain_term_d9b59879f3\\d{0,2}domain_term_15917f3b32...))"',
    ' r"\\s*(...:-|~|—|domain_term_792bbe6e08)\\s*"',
    ' r"(...:(...:\\d{2,4}[./-]\\d{1,2}[./-]\\d{1,2})|(...:\\d{8})|(...:\\d{2,4}domain_term_6f14c2641c\\d{1,2}domain_term_d9b59879f3\\d{0,2}domain_term_15917f3b32...))"',
    ' r")"',
    ')',
    '_DATETIME_10_RE = re.compile(r"\\b\\d{10}\\b")',
    '_DATETIME_12_RE = re.compile(r"\\b\\d{12}\\b")',
    '_DATETIME_14_RE = re.compile(r"\\b\\d{14}\\b")',
    '_LONG_ID_RE = re.compile(r"\\b\\d{9,}\\b")',
    '_NUM_3PLUS_RE = re.compile(r"(...<![a-zA-Z])\\b\\d{3,}\\b")',
    '',
    '',
    'def mask_text(text: str) -> str:',
    ' s = normalize_text(text)',
    ' s = _DATE_RANGE_RE.sub("[DATE_RANGE]", s) # domain_term_a1cc038030，domain_term_80fee5ff32',
    ' s = _DATE_SEP_RE.sub("[DATE]", s)',
    ' s = _DATE_8_RE.sub("[DATE]", s)',
    ' s = _DATE_CN_RE.sub("[DATE]", s)',
    ' s = _GUID_RE.sub("[ID]", s)',
    ' s = _DATETIME_14_RE.sub("[DATETIME]", s)',
    ' s = _DATETIME_12_RE.sub("[DATETIME]", s)',
    ' s = _DATETIME_10_RE.sub("[DATETIME]", s)',
    '',
    ' s = _LONG_ID_RE.sub("[ID]", s)',
    ' s = _NUM_3PLUS_RE.sub("[NUM]", s)',
    ' return s',
    '',
    '',
    'def get_embedder() -> SentenceTransformer:',
    ' global _model',
    ' if _model is None:',
    ' _model = SentenceTransformer(EMBEDDING_MODEL_NAME)',
    ' return _model',
    '',
    '',
    'def embed_texts(texts: List[str]) -> np.ndarray:',
    ' model = get_embedder()',
    ' emb = model.encode(texts, convert_to_numpy=True, normalize_embeddings=True, batch_size=64, show_progress_bar=False)',
    ' return emb.astype("float32")',
    '',
    '',
    'def save_faiss_index(vectors: np.ndarray, meta: List[Dict[str, Any]]):',
    ' # 1. domain_term_e546d7c758 (domain_term_49bb1bc7bb)',
    ' target_dir = FAISS_INDEX_PATH.parent',
    ' if not target_dir.exists():',
    ' target_dir.mkdir(parents=True, exist_ok=True)',
    '',
    ' dim = vectors.shape[1]',
    ' index = faiss.IndexFlatIP(dim)',
    ' index.add(vectors)',
    '',
    ' # --- 【domain_term_fbdca3ec24】domain_term_77599e66bd Faiss domain_term_c87f36b13c ---',
    ' # domain_term_f3c49831c6：domain_term_43ee88e27b，domain_term_b0106a235f',
    '',
    ' # domain_term_cb159b1ec4，domain_term_46930b1ccf D:\\Desktop\\temp_faiss.index',
    ' # domain_term_d4224d501c pathlib domain_term_0647d5d378',
    ' try:',
    ' # domain_term_7c0ae39519 "D:\\\\Desktop" domain_term_2b61a4a64f（domain_term_3d9a3f00ca）',
    ' # domain_term_3d69f99c7e Desktop domain_term_157c011726，domain_term_95c844ce12 D domain_term_fe21425150',
    ' safe_root = Path(os.path.abspath(os.sep)) # domain_term_36474f1382，domain_term_76ce4f0238 D:\\',
    ' if len(FAISS_INDEX_PATH.parts) > 2 and FAISS_INDEX_PATH.parts[1].isascii():',
    ' safe_root = Path(FAISS_INDEX_PATH.parts[0]) / FAISS_INDEX_PATH.parts[1]',
    '',
    ' temp_path = safe_root / "temp_few_shot.faiss"',
    ' temp_path_str = str(temp_path)',
    '',
    ' print(f"[Info] domain_term_7ce856c6f6 Faiss domain_term_033a300806，domain_term_eda6c2f5f6: {temp_path_str}")',
    ' faiss.write_index(index, temp_path_str)',
    '',
    ' print(f"[Info] domain_term_415b2031c9: {FAISS_INDEX_PATH}")',
    ' # domain_term_95936746bc，domain_term_58f7a5d8a6，domain_term_1b3be63899 move domain_term_47f85c21d3',
    ' if FAISS_INDEX_PATH.exists():',
    ' os.remove(FAISS_INDEX_PATH)',
    '',
    ' shutil.move(temp_path_str, str(FAISS_INDEX_PATH))',
    ' print("[Success] domain_term_04a0559649！")',
    '',
    ' except Exception as e:',
    ' print(f"[Error] domain_term_cc314b8ed2: {e}")',
    ' # domain_term_f40143c29f，domain_term_56c13b7dd8 temp.faiss (domain_term_74bd76e5e7)',
    ' raise e',
    '',
    ' # domain_term_757ddb971a (JSON domain_term_0873e0dde6)',
    ' with open(FAISS_META_PATH, "w", encoding="utf-8") as f:',
    ' json.dump(meta, f, ensure_ascii=False)',
    '',
    '',
    'def load_faiss_index():',
    ' global _index, _meta',
    ' if _index is None:',
    ' try:',
    ' _index = faiss.read_index(str(FAISS_INDEX_PATH))',
    ' except Exception as e:',
    ' # domain_term_64667aa162（domain_term_661b2b70ab），domain_term_daa90f19b4',
    ' if FAISS_INDEX_PATH.exists():',
    ' try:',
    ' safe_root = Path(os.path.abspath(os.sep))',
    ' if len(FAISS_INDEX_PATH.parts) > 2 and FAISS_INDEX_PATH.parts[1].isascii():',
    ' safe_root = Path(FAISS_INDEX_PATH.parts[0]) / FAISS_INDEX_PATH.parts[1]',
    ' temp_read = safe_root / "temp_few_shot_read.faiss"',
    ' shutil.copyfile(str(FAISS_INDEX_PATH), str(temp_read))',
    ' print(f"[Info] domain_term_7ce856c6f6 Faiss domain_term_033a300806，domain_term_82831cef32: {temp_read}")',
    ' _index = faiss.read_index(str(temp_read))',
    ' try:',
    ' os.remove(temp_read)',
    ' except Exception:',
    ' pass',
    ' except Exception as e2:',
    ' print(f"[Error] domain_term_1584228be5: {e2}")',
    ' raise e',
    ' else:',
    ' raise e',
    ' if _meta is None:',
    ' with open(FAISS_META_PATH, "r", encoding="utf-8") as f:',
    ' _meta = json.load(f)',
    ' return _index, _meta',
    '',
    '',
    'def faiss_search(query_emb: np.ndarray, top_k: int) -> List[Tuple[int, float]]:',
    ' index, _ = load_faiss_index()',
    ' D, I = index.search(query_emb.reshape(1, -1), top_k)',
    ' return [(int(I[0][i]), float(D[0][i])) for i in range(len(I[0])) if int(I[0][i]) != -1]',
    '',
    '',
    'def connect_db():',
    ' conn = pymysql.connect(',
    ' host=DB_HOST,',
    ' port=DB_PORT,',
    ' user=DB_USER,',
    ' password=DB_PASSWORD,',
    ' database=DB_DATABASE,',
    ' connect_timeout=DB_CONNECT_TIMEOUT,',
    ' read_timeout=DB_READ_TIMEOUT,',
    ' write_timeout=DB_WRITE_TIMEOUT,',
    ' autocommit=True,',
    ' charset="utf8mb4",',
    ' cursorclass=pymysql.cursors.Cursor,',
    ' )',
    ' return conn',
    '',
    '',
    'def execute_sql(conn, sql: str) -> Tuple[bool, List[Tuple], str]:',
    ' try:',
    ' with conn.cursor() as cur:',
    ' cur.execute(sql)',
    ' rows = cur.fetchall()',
    ' return True, list(rows), ""',
    ' except Exception as e:',
    ' return False, [], str(e)',
    '',
    '',
    'def normalize_cell(v: Any) -> Any:',
    ' if isinstance(v, bytes):',
    ' return v.decode("utf-8", errors="ignore")',
    ' # Align with evaluation normalization to reduce false candidate disagreements',
    ' try:',
    ' from decimal import Decimal',
    ' from datetime import date, datetime',
    ' if isinstance(v, Decimal):',
    ' return int(v) if v == v.to_integral_value() else float(round(float(v), 2))',
    ' if isinstance(v, float):',
    ' return int(v) if v.is_integer() else float(round(v, 2))',
    ' if isinstance(v, (date, datetime)):',
    ' return v.isoformat()',
    ' if isinstance(v, str):',
    ' s = v.strip()',
    " if s and s.replace('.', '', 1).isdigit():",
    ' try:',
    ' f = float(s)',
    ' return int(f) if f.is_integer() else float(f)',
    ' except Exception:',
    ' return v',
    ' except Exception:',
    ' return v',
    ' return v',
    '',
    '',
    'def compute_result_hash(rows: List[Tuple]) -> Tuple:',
    ' norm_rows = [tuple(normalize_cell(x) for x in r) for r in rows]',
    ' try:',
    ' sortable = sorted(norm_rows)',
    ' except Exception:',
    ' sortable = norm_rows',
    ' return tuple(sortable)',
    '',
    '',
    'def append_log(path: Path, text: str):',
    ' ensure_dirs()',
    ' with open(path, "a", encoding="utf-8") as f:',
    ' f.write(text.rstrip("\\n") + "\\n")',
    '',
    '',
    'def strip_sql_fences(s: str) -> str:',
    ' s = s.strip()',
    '',
    ' # domain_term_e53df46873：LLM domain_term_fb2ea9e2df Query Plan domain_term_b06f1d6556，domain_term_f896fb3776 "Final Optimized SQL Query:"',
    ' # domain_term_0b28098e58 SQL，domain_term_250d600bbb "Select ..."。',
    ' m_final = re.search(r"Final\\s+Optimized\\s+SQL\\s+Query\\s*:...", s, re.IGNORECASE)',
    ' if m_final:',
    ' sub = s[m_final.end():].lstrip()',
    '',
    ' # 1) domain_term_885d450b12 ```sql ... ``` / ```...``` domain_term_dde7d623ea',
    ' m = re.search(r"```(...:sql|SQL)...\\s*([\\s\\S]*...)\\s*```", sub)',
    ' if m:',
    ' return m.group(1).strip()',
    ' if sub.startswith("```"):',
    ' sub2 = re.sub(r"^```(...:sql|SQL)...", "", sub).strip()',
    ' if sub2.endswith("```"):',
    ' sub2 = sub2[:-3].strip()',
    ' return sub2.strip()',
    '',
    ' # 2) domain_term_7ac96b3eb4 SELECT / WITH domain_term_84ae302bd5 SQL',
    ' m2 = re.search(r"(...is)\\b(select|with)\\b[\\s\\S]*", sub)',
    ' if m2:',
    ' return m2.group(0).strip()',
    ' # domain_term_58ac891863，domain_term_c4fba8a521',
    '',
    ' # domain_term_76a131c042：domain_term_60c4fd0046 ```sql ... ``` domain_term_dde7d623ea',
    ' m = re.search(r"```(...:sql|SQL)...\\s*([\\s\\S]*...)\\s*```", s)',
    ' if m:',
    ' return m.group(1).strip()',
    ' if s.startswith("```"):',
    ' s = re.sub(r"^```(...:sql|SQL)...", "", s).strip()',
    ' if s.endswith("```"):',
    ' s = s[:-3].strip()',
    ' return s.strip()',
    '',
    ' # domain_term_dedece75f4：domain_term_8b0e86898f SELECT / WITH domain_term_c0d986163e',
    ' m2 = re.search(r"(...is)\\b(select|with)\\b[\\s\\S]*", s)',
    ' if m2:',
    ' return m2.group(0).strip()',
    ' return s',
]


def get_translated_source() -> str:
    """Return the preserved English-normalized source as plain text."""
    return "\n".join(TRANSLATED_SOURCE_LINES)


if __name__ == "__main__":
    print(get_translated_source())
